.TH ALIENS 6 4/2/81
.UC 4
.SH NAME
aliens \- The alien invaders attack the earth
.SH SYNIOPSIS
.B /usr/games/aliens
.SH DESCRIPTION
.PP
This is a UNIX version of Space Invaders.  The program is pretty much self
documenting.
.SH FILES
/usr/games/lib/aliens.log	Score file
.SH BUGS
The program is a CPU hog.  It needs to be re-written.
It doesn't do well on terminals that run slower than 9600 baud.
