#	@(#)Makefile	5.4 (Berkeley) 7/25/90

MAN1=	kdestroy.0 kerberos.0 kinit.0 klist.0 ksrvtgt.0
MAN3=	acl_check.0 des_crypt.0 krb.0 krb_realmofhost.0 krb_sendauth.0 \
	krb_set_tkt_string.0 kuserok.0 tf_util.0
MAN5=	krb.conf.0 krb.realms.0
MAN8=	ext_srvtab.0 kdb_destroy.0 kdb_edit.0 kdb_init.0 kdb_util.0 kstash.0
MLINKS+=krb_realmofhost.3 realm.3
MLINKS+=des_crypt.3 des.3
MLINKS+=krb.3 kerberos.3 krb.3 krb_mk_req.3 krb.3 krb_rd_req.3
MLINKS+=krb.3 krb_kntoln.3 krb.3 krb_set_key.3 krb.3 krb_get_cred.3
MLINKS+=krb.3 krb_mk_priv.3 krb.3 krb_mk_safe.3 krb.3 krb_rd_safe.3
MLINKS+=krb.3 krb_mk_err.3 krb.3 krb_rd_err.3 krb.3 krb_ck_repl.3
MLINKS+=krb_sendauth.3 ksend.3

.include <bsd.prog.mk>
