.\" Copyright (c) 1986, 1991, 1993
.\"	The Regents of the University of California.  All rights reserved.
.\"
.\" %sccs.include.redist.man%
.\"
.\"     @(#)ix.4	8.1 (Berkeley) %G%
.\"
.Dd 
.Dt IX 4 vax
.Os BSD 4.2
.Sh NAME
.Nm ix
.Nd Interlan Np100 10 Mb/s Ethernet interface
.Sh SYNOPSIS
.Cd "device np0 at uba0 csr 166000 vector npintr"
.Sh DESCRIPTION
The
.Nm ix
interface provides access to a 10 Mb/s Ethernet network through
an Interlan Np100 controller used as a link-layer interface.
.Pp
This interface is unusual in that it requires loading firmware
into the controller before it may be used as a network interface.
This is accomplished by opening a character special device,
and writing data to it.
A program to load the image is provided in
.Pa /usr/src/new/np100 .
The sequence of commands would be:
.Bd -literal -offset indent
# ./npload np.image [/dev/np<board #> if other than np00]
# sleep 10
# ifconfig ix0 ...
.Ed
.Pp
Each of the host's network addresses
is specified at boot time with an
.Dv SIOCSIFADDR
.Xr ioctl 2 .
The
.Nm ix
interface employs the address resolution protocol described in
.Xr arp 4
to dynamically map between Internet and Ethernet addresses on the local
network.
.Pp
The interface normally tries to use a
.Dq trailer
encapsulation
to minimize copying data on input and output.
The use of trailers is negotiated with
.Tn ARP .
This negotiation may be disabled, on a per-interface basis,
by setting the
.Dv IFF_NOTRAILERS
flag with an 
.Dv SIOCSIFFLAGS 
.Xr ioctl .
.Sh DIAGNOSTICS
.Bl -diag
.It "ix%d: Req failed, cmd %x, stat %x, ust error %x,%x."
The firmware in the controller refused to honor a request from
.Tn UNIX
in initializing packet level communications.
The board may need to be reset and reloaded.
Or, you may not have allowed enough time between loading the board
and issuing the request to begin unix network operation.
.Pp
.It ix%d: can't initialize.
The interface was unable to obtain unibus resources required for operation.
.Pp
.It ix%d: failed to reinitialize DLA module.
The interface got sick after attempting to reprogram its physical
ethernet address.  Try reloading the firmware.
The attempt is made only when this interfaces is not the first
one configured for
.Tn XNS .
.Pp
.It ix%d: can't handle af%d.
The interface was handed
a message with addresses formatted in an unsuitable address
family; the packet was dropped.
.Pp
.It ix%d: stray xmit interrupt, npreq=%x.
This may happen if the board is reloaded while network processes are still
running.
.Pp
.It ixrint: cqe error %x, %x, %x.
This will result if an 
.Xr ifconfig 8
request is made at an inopportune time, such as not allowing
enough time after loading the firmware.
After 100 such errors are logged, the unix network driver will
shut itself down, saying:
.Pp
.It ixrint: shutting down unix dla.
The recourse is to reload the firmware and allow more time.
.El
.Sh SEE ALSO
.Xr netintro 4 ,
.Xr inet 4 ,
.Xr arp 4 ,
.Xr np 4 .
.Sh HISTORY
The
.Nm
driver appeared in
.Bx 4.3 .
