.\" Copyright (c) 1980,1983 Regents of the University of California.
.\" All rights reserved.  The Berkeley software License Agreement
.\" specifies the terms and conditions for redistribution.
.\"
.\"	@(#)format.8v	6.4 (Berkeley) 5/22/86
.\"
.TH FORMAT 8V "May 22, 1986"
.UC 4
.SH NAME
format \- how to format disk packs
.SH DESCRIPTION
.PP
There are two ways to format disk packs.  The simplest is to
use the
.I format
program.  The alternative is to use the DEC standard formatting
software which operates under the DEC diagnostic supervisor. 
This manual page describes the operation of
.IR format ,
then concludes with some remarks about using the DEC formatter.
.PP
.I Format
is a standalone program used to
format and check disks prior to constructing
file systems.
In addition to the formatting
operation,
.I format
records any bad sectors encountered
according to DEC standard 144. 
Formatting is performed one track at a
time by writing the appropriate
headers and a test pattern and then checking
the sector by reading and verifying the pattern, using
the controller's ECC for error detection.
A sector is marked bad if an unrecoverable media
error is detected, or if a correctable
ECC error too many bits in length
is detected (such errors are indicated as
``ECC'' in the summary printed upon
completing the format operation).
After the entire disk
has been formatted and checked,
the total number of errors are reported,
any bad sectors and skip sectors are marked,
and a bad sector forwarding table
is written to the disk in the first five
even numbered sectors of the last track.
It is also possible to reformat sections of the disk
in units of tracks.
.I Format 
may be used on any UNIBUS or MASSBUS drive
supported by the \fIup\fP and \fIhp\fP device
drivers which uses 4-byte headers (everything except RP's).
.PP
The test pattern used during the media check
may be selected from one of: 0xf00f (RH750 worst case),
0xec6d (media worst case), and 0xa5a5 (alternating
1's and 0's).
Normally the media worst case pattern is used.
.PP
.I Format
also has an option to perform an extended \*(lqsevere burn-in,\*(rq
which makes a number of passes using different patterns.
The number of passes can be selected at run time,
up to a maximum of 48,
with provision for additional passes or termination
after the preselected number of passes.
This test runs for many hours, depending on the disk and processor.
.PP
Each time
.I format
is run to format an entire disk,
a completely new bad sector table is generated
based on errors encountered while formatting.
The device driver, however, will always attempt to
read any existing bad sector table when the device is
first opened.
Thus, if a disk pack has never previously been formatted,
or has been formatted with different sectoring,
five error messages will be printed when the driver attempts
to read the bad sector table; these diagnostics should be ignored.
.PP
Formatting a 400 megabyte disk on a MASSBUS disk controller
usually takes about 20 minutes.
Formatting on a UNIBUS disk controller takes significantly
longer.
For every hundredth cylinder formatted
.I format
prints a message indicating the current cylinder being formatted.
(This message is just to reassure people that nothing is
is amiss.)
.PP
.I Format
uses the standard notation of the standalone I/O library
in identifying a drive to be formatted.  A drive is
specified as
.IR zz ( x , y ),
where 
.I zz
refers to the controller type (either
.I hp
or
.IR up ),
.I x
is the unit number of the drive;
8 times the UNIBUS or MASSBUS
adaptor number plus the MASSBUS drive number or UNIBUS
drive unit number; and
.I y
is the file system partition
on drive
.I x
(this should always be 0). 
For example, ``hp(1,0)'' indicates that drive
1 on MASSBUS adaptor 0 should be formatted; while
``up(10,0)'' indicates that UNIBUS drive 2 on UNIBUS adaptor 1
should be formatted.
.PP
Before each formatting attempt, 
.I format
prompts the user in case debugging should be enabled
in the appropriate device driver.  A carriage return
disables debugging information.
.PP
.I Format
should be used prior to building file systems (with 
.IR newfs (8))
to insure that all sectors with uncorrectable media errors
are remapped.  If a drive develops uncorrectable
defects after formatting, either
.IR bad144 (8)
or
.IR badsect (8)
should be able to avoid the bad sectors.
.SH EXAMPLE
A sample run of 
.I format
is shown below.  
In this example (using a VAX-11/780), 
.I format
is loaded from the console floppy;
on an 11/750
.I format
will be loaded from the root file system with
.IR boot (8)
following a \*(lqB/3\*(rq command.
Boldface means user input.
As usual, ``#'' and ``@'' may be used to edit input.
.nf
.in +0.5i
.ta  1i
.sp 1
>>>\fBL FORMAT\fP
	LOAD DONE, 00004400 BYTES LOADED
>>>\fBS 2\fP
Disk format/check utility
.sp
Enable debugging (0=none, 1=bse, 2=ecc, 3=bse+ecc)? \fB0\fP
Device to format? \fBhp(8,0)\fP
(\fIerror messages may occur as old bad sector table is read\fP)
Formatting drive hp0 on adaptor 1: verify (yes/no)? \fByes\fP
Device data: #cylinders=842, #tracks=20, #sectors=48
Starting cylinder (0):
Starting track (0):
Ending cylinder (841):
Ending track (19):
Available test patterns are:
.in +1.0i
1 - (f00f) RH750 worst case
2 - (ec6d) media worst case
3 - (a5a5) alternating 1's and 0's
4 - (ffff) Severe burnin (up to 48 passes)
.in -1.0i
Pattern (one of the above, other to restart)? \fB2\fP
Maximum number of bit errors to allow for soft ECC (3):
Start formatting...make sure the drive is online
 ...
(\fIsoft ecc's and other errors are reported as they occur\fP)
 ...
(\fIif 4 write check errors were found, the program terminates like this...\fP)
 ...
Errors:
Bad sector: 0
Write check: 4
Hard ECC: 0
Other hard: 0
Marked bad: 0
Skipped: 0
Total of 4 hard errors revectored.
Writing bad sector table at block 808272	
(\fI808272 is the block # of the first block in the bad sector table\fP)
Done
(\fI...program restarts to allow formatting other disks\fP)
(\fI...to abort halt machine with ^P\fP)
.fi
.sp 1
.SH DIAGNOSTICS
The diagnostics are intended to be self explanatory.
.SH "USING DEC SOFTWARE TO FORMAT"
.PP
.B "Warning:  These instructions are for people with 11/780 CPU's."
The steps needed for 11/750 or 11/730 cpu's are similar, but not
covered in detail here.
.I
.PP
The formatting procedures are different for each type of disk.  Listed
here are the formatting procedures for RK07's, RP0X, and RM0X 
disks.
.PP
You should shut down UNIX and halt the machine to do any disk formatting.
Make certain you put in the pack you want formatted.  It is also a good idea
to spin down or write protect the disks you don't want to format, just in case.
.PP
.B "Formatting an RK07."
Load the console floppy labeled, "RX11 VAX DSK LD DEV #1" in
the console disk drive, and type the following commands:
.RS
.nf
>>>BOOT
DIAGNOSTIC SUPERVISOR.  ZZ-ESSAA-X5.0-119  23-JAN-1980 12:44:40.03
DS>ATTACH DW780 SBI DW0 3 5
DS>ATTACH RK611 DMA
DS>ATTACH RK07 DW0 DMA0
DS>SELECT DMA0
DS>LOAD EVRAC
DS>START/SEC:PACKINIT
.fi
.RE
.PP
.B "Formatting an RP0X."
Follow the above procedures except that the
ATTACH and SELECT lines should read:
.RS
.nf
DS>ATTACH RH780 SBI RH0 8 5
DS>ATTACH RP0X RH0 DBA0		(RP0X is, e.g. RP06)
DS>SELECT DBA0
.fi
.RE
.PP
This is for drive 0 on mba0; use 9 instead of 8 for mba1, etc.
.PP
.B "Formatting an RM0X."
Follow the above procedures except that the
ATTACH and SELECT lines should read:
.RS
.nf
DS>ATTACH RH780 SBI RH0 8 5
DS>ATTACH RM0X RH0 DRA0
DS>SELECT DRA0
.fi
.RE
.PP
Don't forget to put your UNIX console floppy back
in the floppy disk drive.
.SH SEE ALSO
bad144(8),
badsect(8),
newfs(8)
.SH BUGS
An equivalent facility should be available which operates under
a running UNIX system. 
.PP
It should be possible to reformat or verify part or all of a disk,
then update the existing bad sector table.
