.TH MOUNT 2 
.SH NAME
mount, umount \- mount or remove file system
.SH SYNOPSIS
.B mount(special, name, rwflag)
.br
.B char *special, *name;
.PP
.B umount(special)
.br
.B char *special;
.SH DESCRIPTION
.I Mount
announces to the system that a removable file system has
been mounted on
the block-structured special file
.I special;
from now on, references to file
.I name
will refer to
the root file on the newly mounted file system.
.I Special
and
.I name
are pointers to null-terminated strings
containing the appropriate path names.
.PP
.I Name
must exist already. 
.I Name
must be a directory (unless the root of the mounted file system
is not a directory).
Its old contents
are inaccessible while the file system
is mounted.
.PP
The
.I rwflag
argument determines whether
the file system can be written on; if it is 0 writing
is allowed, if non-zero no writing is done.
Physically write-protected and magnetic
tape file systems must be mounted read-only or
errors will occur when access times are updated,
whether or not any
explicit write is attempted.
.PP
.I Umount
announces to the system that the
.I special
file is no longer to contain a removable file system.
The associated file reverts to its ordinary interpretation.
.SH "SEE ALSO"
mount(1)
.SH DIAGNOSTICS
.I Mount
returns 0 if the action occurred; \-1 if
.I special
is inaccessible or not an appropriate file; if
.I name
does not exist; if
.I special
is already mounted; if
.I name
is in use; or if
there are already too many
file systems mounted.
.PP
.I Umount
returns 0 if the action occurred; \-1 if
if the special file is inaccessible or
does not have a mounted file system,
or if there are active files in the mounted 
file system.
.SH BUGS
If a file containing holes
(unallocated blocks)
is read, even on a file system mounted read-only,
the system will attempt to fill in the holes
by writing on the device.
.SH "ASSEMBLER (PDP-11)"
(mount = 21.)
.br
.B sys  mount; special; name; rwflag
.PP
(umount = 22.)
.br
.B sys  umount; special
