.\" Copyright (c) 1983 The Regents of the University of California.
.\" All rights reserved.
.\"
.\" Redistribution and use in source and binary forms are permitted
.\" provided that the above copyright notice and this paragraph are
.\" duplicated in all such forms and that any documentation,
.\" advertising materials, and other materials related to such
.\" distribution and use acknowledge that the software was developed
.\" by the University of California, Berkeley.  The name of the
.\" University may not be used to endorse or promote products derived
.\" from this software without specific prior written permission.
.\" THIS SOFTWARE IS PROVIDED ``AS IS'' AND WITHOUT ANY EXPRESS OR
.\" IMPLIED WARRANTIES, INCLUDING, WITHOUT LIMITATION, THE IMPLIED
.\" WARRANTIES OF MERCHANTIBILITY AND FITNESS FOR A PARTICULAR PURPOSE.
.\"
.\"	@(#)sendbug.1	6.4 (Berkeley) 10/25/88
.\"
.TH SENDBUG 1 "October 25, 1988"
.UC 5
.ad
.SH NAME
sendbug \- mail a system bug report to 4bsd-bugs
.SH SYNOPSIS
.B sendbug [ address ]
.SH DESCRIPTION
.PP
Bug reports sent to `4bsd-bugs@Berkeley.EDU' are intercepted
by a program which expects bug reports to conform to a standard format.
.I Sendbug
is a shell script to help the user compose and mail bug reports
in the correct format.
.I Sendbug
works by invoking the editor specified by the environment variable
.I EDITOR
on a temporary copy of the bug report format outline. The user must fill in the
appropriate fields and exit the editor.  The default editor is
.IR vi (1).
.I Sendbug
then mails the completed report to `4bsd-bugs@Berkeley.EDU' or the address
specified on the command line.
.SH FILES
.nf
.ta \w'/usr/ucb/bugformat       'u
/usr/ucb/bugformat	contains the bug report outline
.fi
.SH "SEE ALSO"
vi(1), environ(7), bugfiler(8), sendmail(8)
