.\"
.\" Copyright (c) 1988 Mark Nudleman
.\" Copyright (c) 1988 Regents of the University of California.
.\" All rights reserved.
.\"
.\" Redistribution and use in source and binary forms are permitted
.\" provided that the above copyright notice and this paragraph are
.\" duplicated in all such forms and that any documentation,
.\" advertising materials, and other materials related to such
.\" distribution and use acknowledge that the software was developed
.\" by Mark Nudleman and the University of California, Berkeley.  The
.\" name of Mark Nudleman or the
.\" University may not be used to endorse or promote products derived
.\" from this software without specific prior written permission.
.\" THIS SOFTWARE IS PROVIDED ``AS IS'' AND WITHOUT ANY EXPRESS OR
.\" IMPLIED WARRANTIES, INCLUDING, WITHOUT LIMITATION, THE IMPLIED
.\" WARRANTIES OF MERCHANTIBILITY AND FITNESS FOR A PARTICULAR PURPOSE.
.\"
.\"	@(#)more.1	5.6 (Berkeley) %G%
.\"
.TH MORE 1
.SH NAME
more \- file perusal filter for crt viewing
.SH SYNOPSIS
.B "more [-ceinpus] [-t tag] [-x tabs] [-/ pattern] [-#] [file ...]"
.SH DESCRIPTION
.I More
is a filter for paging through text one screenful at a time.  It
uses
.IR termcap (3)
so it can run on a variety of terminals.  There is even limited support
for hardcopy terminals.  (On a hardcopy terminal, lines which should be
printed at the top of the screen are prefixed with an up-arrow.)
.I File
may be a single dash (``-''), implying stdin.
.SH OPTIONS
Command line options are described below.
Options are also taken from the environment variable "MORE"
(make sure to precede them with a dash (``-'')) but command
line options will override them.
.IP -c
Normally, 
.I more
will repaint the screen by scrolling from the bottom of the screen.
If the -c option is set, when
.I more 
needs to change the entire display, it will paint from the top line down.
.IP -e
Normally
.I more
exits as soon as it reaches end-of-file.  The -e option tells more to
exit the second time it reaches end-of-file.
.IP -i
The -i option causes searches to ignore case; that is,
uppercase and lowercase are considered identical.
.IP -n
The -n flag suppresses line numbers.
The default (to use line numbers) may cause
.I more
to run more slowly in some cases, especially with a very large input file.
Suppressing line numbers with the -n flag will avoid this problem.
Using line numbers means: the line number will be displayed in the 
= command, and the v command will pass the current line number to the editor.
.IP -p
The -p option gives you a colon (``:'') for a prompt, rather than
the more verbose traditional prompt.
.IP -s
The -s option causes
consecutive blank lines to be squeezed into a single blank line.
.IP -t
The -t option, followed immediately by a tag, will edit the file
containing that tag.  For more information, see the
.IR ctags (1)
command.
.IP -u
If the -u option is given, backspaces are always printed as the two
character sequence ``^H''; otherwise, backspaces which appear adjacent
to an underscore character are treated specially: the underlined text
is displayed using the terminal's hardware underlining capability.
Also, backspaces which appear between two identical characters are
treated specially: the overstruck text is printed using the terminal's
hardware boldface capability.
.IP -x
The -x option sets tab stops every
.I N
positions. The default for
.I N
is 8.
.IP -/
The -/ option specifies a string that will be searched for before
each file is displayed.
.SH COMMANDS
Interactive commands for
.I more
are based on
.IR vi (1).
Some commands may be preceeded by a decimal number, called N in the
descriptions below.
In the following descriptions, ^X means control-X.
.IP h
help: display a summary of these commands.
If you forget all the other commands, remember this one.
.PP
.IP "SPACE or f or ^F"
Scroll forward N lines, default one window.
If N is more than the screen size, only the final screenful is displayed.
.PP
.IP "b or ^B"
Scroll backward N lines, default one window (see option -z below).
If N is more than the screen size, only the final screenful is displayed.
.PP
.IP "j or RETURN"
Scroll forward N lines, default 1.
The entire N lines are displayed, even if N is more than the screen size.
.PP
.IP "k"
Scroll backward N lines, default 1.
The entire N lines are displayed, even if N is more than the screen size.
Warning: some systems use ^Y as a special job control character.
.PP
.IP "d or ^D"
Scroll forward N lines, default one half of the screen size.
If N is specified, it becomes the new default for 
subsequent d and u commands.
.PP
.IP "u or ^U"
Scroll backward N lines, default one half of the screen size.
If N is specified, it becomes the new default for 
subsequent d and u commands.
.PP
.IP "g"
Go to line N in the file, default 1 (beginning of file).
.PP
.IP "G"
Go to line N in the file, default the end of the file.
.PP
.IP "p or %"
Go to a position N percent into the file.  N should be between 0
and 100.  (This works if standard input is being read, but only if
.I more
has already read to the end of the file.  It is always fast, but
not always useful.)
.PP
.IP "r or ^L"
Repaint the screen.
.PP
.IP "R"
Repaint the screen, discarding any buffered input.
Useful if the file is changing while it is being viewed.
.PP
.IP m
Followed by any lowercase letter, 
marks the current position with that letter.
.PP
.IP "'"
(Single quote.)
Followed by any lowercase letter, returns to the position which
was previously marked with that letter.
Followed by another single quote, returns to the postion at
which the last "large" movement command was executed.
All marks are lost when a new file is examined.
.PP
.IP /pattern
Search forward in the file for the N-th line containing the pattern.
N defaults to 1.
The pattern is a regular expression, as recognized by
.I ed.
The search starts at the second line displayed.
.PP
.IP ?pattern
Search backward in the file for the N-th line containing the pattern.
The search starts at the line immediately before the top line displayed.
.PP
.IP /!pattern
Like /, but the search is for the N-th line
which does NOT contain the pattern.
.PP
.IP ?!pattern
Like ?, but the search is for the N-th line
which does NOT contain the pattern.
.PP
.IP n
Repeat previous search, for N-th line containing the last pattern
(or NOT containing the last pattern, if the previous search
was /! or ?!).
.PP
.IP "E [filename]"
Examine a new file.
If the filename is missing, the "current" file (see the N and P commands
below) from the list of files in the command line is re-examined.
If the filename is a pound sign (#), the previously examined file is
re-examined.
.PP
.IP "N or :n"
Examine the next file (from the list of files given in the command line).
If a number N is specified (not to be confused with the command N),
the N-th next file is examined.
.PP
.IP "P or :p"
Examine the previous file.
If a number N is specified, the N-th previous file is examined.
.PP
.IP ":t"
Go to supplied tag.
.PP
.IP v
Invokes an editor to edit the current file being viewed.
The editor is taken from the environment variable EDITOR,
or defaults to
.IR vi (1).
.PP
.IP "= or ^G"
These options print out the number of the file currently being displayed
relative to the total number of files there are to display, the current
line number, the current byte number and the total bytes to display, and
what percentage of the file has been displayed.  If
.I more
is reading from stdin, or the file is shorter than a single screen, some
of these items may not be available.  Note, all of these items reference
the first byte of the last line displayed on the screen.
.PP
.IP "q or :q or ZZ"
Exits
.I more.
.SH "SEE ALSO
ctags(1), vi(1)
.SH AUTHOR
This software is derived from software contributed to Berkeley
by Mark Nudleman.
