.\" Copyright (c) 1989 The Regents of the University of California.
.\" All rights reserved.
.\"
.\" %sccs.include.redist.man%
.\"
.\"	@(#)unvis.1	5.1 (Berkeley) %G%
.\"
.TH UNVIS 1 ""
.UC 7
.SH NAME
unvis \- change a visual representation of data back to its original form
.SH SYNOPSIS
.nf
.ft B
unvis [ file ... ]
.ft R
.fi
.SH DESCRIPTION
.I Unvis
P is the inverse function of
.IR vis (1).
It changes a visual representation of data back to its original form on
standard output.
.SH "SEE ALSO
vis(1), vis(3), unvis(3)
