#	@(#)Makefile	8.4 (Berkeley) %G%

SUBDIR=	ansi bib bind-4.9 flex-2.4.6 gawk-2.15.2 emacs-18.57 gas-1.38 \
	gcc-2.3.3 gdb-4.7.lbl groff-1.08 gzip-1.0.7 hunt jove-4.14.6 \
	kermit-5A.188 libg++-2.3 mh-6.8 nvi perl-4.036 rcs-V5.6

cleandir: clean

obj depend tags: 

.include <bsd.subdir.mk>
