#
# script to run off font catalog
#
all:
	vtroff -3 bocklin titlepage
	vtroff -ms intro.ms
	vtroff -1 apl apl
	vtroff -F basker basker
	vtroff -1 bocklin bocklin
	vtroff -F bodoni bodoni
	vtroff -1 chess chess
	vtroff -1 cyrillic cyrillic
	vtroff -2 delegate.i delegate
	vtroff -1 fix fix
	vtroff -F gacham gacham
	vtroff -1 hebrew hebrew
	vtroff hershey
	vtroff -F meteor meteor
	vtroff -1 microgramma microgramma
	vtroff -1 mona mona
	vtroff -F nonie nonie
	vtroff -1 oldenglish oldenglish
	vtroff -1 pip pip
	vtroff -1 playbill playbill
	vtroff -1 script script
	vtroff -1 shadow shadow
	vtroff -1 sign sign
#	vtroff -1 tengwar tengwar
#	vtroff -1 wumpus wumpus
