.\" Copyright (c) 1983, 1990 The Regents of the University of California.
.\" All rights reserved.
.\"
.\" Redistribution and use in source and binary forms are permitted provided
.\" that: (1) source distributions retain this entire copyright notice and
.\" comment, and (2) distributions including binaries display the following
.\" acknowledgement:  ``This product includes software developed by the
.\" University of California, Berkeley and its contributors'' in the
.\" documentation or other materials provided with the distribution and in
.\" all advertising materials mentioning features or use of this software.
.\" Neither the name of the University nor the names of its contributors may
.\" be used to endorse or promote products derived from this software without
.\" specific prior written permission.
.\" THIS SOFTWARE IS PROVIDED ``AS IS'' AND WITHOUT ANY EXPRESS OR IMPLIED
.\" WARRANTIES, INCLUDING, WITHOUT LIMITATION, THE IMPLIED WARRANTIES OF
.\" MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE.
.\"
.\"     @(#)fp.1	6.4 (Berkeley) 6/26/90
.\"
.Dd June 26, 1990
.Dt FP 1
.Os BSD 4.2
.Sh NAME
.Nm fp
.Nd Functional Programming language compiler/interpreter
.Sh SYNOPSIS
.Nm fp
.Sh DESCRIPTION
.Nm Fp
is an
interpreter/compiler that implements the applicative language proposed
by John Backus.  It is written in
.Em FRANZ LISP .
.Pp
In a  functional programming language
intent is expressed
in  a mathematical style devoid of assignment statements
and variables.
Functions compute by value only; there are no side-effects
since  the result of a computation depends solely on the inputs.
.Pp
.Nm Fp
.Em programs
consist of
.Em functional expressions
\-
primitive and user-defined
.Nm fp
functions
combined by
.Em functional forms .
These forms take functional arguments
and return functional results.
For example, the composition
operator
.Sq Ic @
takes two functional arguments and returns a function
which represents their composition.
.Pp
There exists a single operation in
.Nm fp
\&\-
.Em application .
This operation causes the system to evaluate the indicated function using
the single argument
as input
(all functions are monadic).
.Sh GETTING STARTED
.Pp
.Nm Fp
invokes the system.
.Nm Fp
compiles functions into
.Xr lisp  1
source code;
.Xr lisp  1
interprets this code
(the user may compile this code using the
.Xr liszt 1
compiler to gain a factor of 10 in performance).
.Ic Control D
exits back to the shell.
.Ic Break
terminates any computation in progress  and resets any open file units.
.Ic )help
provides a short summary of all user commands.
.Sh FILES
.Dw liszt
.Di L
.Dp Pa lisp
the FRANZ LISP interpreter
.Dp Pa liszt
the liszt compiler
.\" .Dp Pa /usr/doc/fp
.\" the User's Guide
.Dp
.Sh SEE ALSO
.Xr lisp 1 ,
.Xr liszt 1 ,
.br
.Em The Berkeley FP user's manual ,
available on-line.
The language is described  in  the August 1978 issue of
.Em CACM
(Turing award lecture by John Backus).
.Sh BUGS
If a non-terminating function is applied as the result of loading a file,
then control is returned to the user immediately, everything
after that position in the file is ignored.
.Pp
.Nm Fp
incorrectly marks the location of a syntax error on
large, multi-line function definitions or applications.
.Sh HISTORY
.Nm Fp
appeared in 4.2 BSD.
.Sh AUTHOR
Scott B. Baden
