.\" Copyright (c) 1987 The Regents of the University of California.
.\" All rights reserved.
.\"
.\" This code is derived from software contributed to Berkeley by
.\" Computer Consoles Inc.
.\"
.\" Redistribution and use in source and binary forms are permitted
.\" provided that the above copyright notice and this paragraph are
.\" duplicated in all such forms and that any documentation,
.\" advertising materials, and other materials related to such
.\" distribution and use acknowledge that the software was developed
.\" by the University of California, Berkeley.  The name of the
.\" University may not be used to endorse or promote products derived
.\" from this software without specific prior written permission.
.\" THIS SOFTWARE IS PROVIDED ``AS IS'' AND WITHOUT ANY EXPRESS OR
.\" IMPLIED WARRANTIES, INCLUDING, WITHOUT LIMITATION, THE IMPLIED
.\" WARRANTIES OF MERCHANTIBILITY AND FITNESS FOR A PARTICULAR PURPOSE.
.\"
.\"	@(#)dlmpcc.8	6.3 (Berkeley) %G%
.\"
.TH DLMPCC 8 ""
.UC 7
.SH NAME
dlmpcc \- download MPCC
.SH SYNOPSIS
\fBdlmpcc\fR  [ n ]
.SH DESCRIPTION
\fIDlmpcc\fR downloads CCI's Multi-Protocol
Communication Controller (MPCC).
The controller provides high-speed
synchronous communications for the \s-1POWER 5\s+1 and \s-1POWER 6\s+1 families of computers.
This utility allows you to 
download any or all of the MPCC boards.
The configuration file \fBmpcctab\fR determines
the protocol attributes for each MPCC board. See
\fImpcctab\fR(4) for details. 
.LP
If you specify the command with no argument, then \fIdlmpcc\fR
scans the configuration file and downloads all configured boards
with corresponding protocol software. The 
option \fIn\fR allows you to specify one or
more MPCC boards for downloading. The valid values range from
\fB0-15\fR. For example, the following command line orders \fIdlmpcc\fR
to download only the protocol software identified with board 2:
.nf

        dlmpcc  2

.fi
The next command line orders the download
of the protocols identified with
boards 0 and 3: 
.nf

        dlmpcc  0  3
.fi 
.LP
Typically, this download function is performed at boot time from the
/etc/rc.local file with an entry similar to:
.nf
        /etc/dlmpcc > /dev/console 2>&1
.fi
.SH SEE ALSO
mpcctab(4)
