.\" Copyright (c) 1983 Regents of the University of California.
.\" All rights reserved.
.\"
.\" Redistribution and use in source and binary forms are permitted
.\" provided that this notice is preserved and that due credit is given
.\" to the University of California at Berkeley. The name of the University
.\" may not be used to endorse or promote products derived from this
.\" software without specific prior written permission. This software
.\" is provided ``as is'' without express or implied warranty.
.\"
.\"	@(#)quota.1	6.2 (Berkeley) %G%
.\"
.TH QUOTA 1 ""
.UC 5
.SH NAME
quota \- display disc usage and limits
.SH SYNOPSIS
.B quota
[
.B \-qv
] [
user
]
.SH DESCRIPTION
.I Quota
displays users' disc usage and limits. 
Only the super-user may use the optional
.I user
argument to view the limits of users other than
himself.
.PP
The
.B \-q
flag prints a more terse message,
containing only information
on file systems where usage is over quota.
.PP
If a
.B \-v
flag is supplied, 
.I quota
will also display user's quotas on file systems
where no storage is allocated.
.PP
.I Quota
reports only on file systems which have
disc quotas. 
If 
.I quota
exits with a non-zero status, one or more file
systems are over quota.
.SH "SEE ALSO"
quota(2), quotaon(8)
