.\" Copyright (c) 1983, 1991, 1993
.\"	The Regents of the University of California.  All rights reserved.
.\"
.\" %sccs.include.redist.man%
.\"
.\"     @(#)getdtablesize.2	8.1 (Berkeley) %G%
.\"
.Dd 
.Dt GETDTABLESIZE 2
.Os BSD 4.2
.Sh NAME
.Nm getdtablesize
.Nd get descriptor table size
.Sh SYNOPSIS
.Fd #include <unistd.h>
.Ft int
.Fn getdtablesize void
.Sh DESCRIPTION
Each process has a fixed size descriptor table,
which is guaranteed to have at least 20 slots.  The entries in
the descriptor table are numbered with small integers starting at 0.
The call
.Fn getdtablesize
returns the size of this table.
.Sh SEE ALSO
.Xr close 2 ,
.Xr dup 2 ,
.Xr open 2 ,
.Xr select 2
.Sh HISTORY
The
.Nm
function call appeared in
.Bx 4.2 .
