.\" Copyright (c) 1989 The Regents of the University of California.
.\" All rights reserved.
.\"
.\" %sccs.include.redist.man%
.\"
.\"	@(#)nfssvc.2	6.4 (Berkeley) %G%
.\"
.TH NFSSVC 2 ""
.UC 7
.SH NAME
nfssvc \- create a remote NFS server
.SH SYNOPSIS
.nf
.ft B
.LP
nfssvc(sock)
int sock;
.fi
.ft R
.SH DESCRIPTION
.I Nfssvc
starts an
.SM NFS
daemon listening on socket
.IR sock .
The socket must be in the
.SM AF_INET
family and of type
.SM SOCK_DGRAM .
.SH RETURN VALUE
Normally this system calls does not return unless the server
is terminated by a signal at which time a value of 0 is returned.
Otherwise, \-1 is returned and the global variable
.I errno
is set to indicate the error.
.SH ERRORS
.I Nfssvc
fails if one or more of the following are true:
.TP 15
EBADF
.I fd
is not a valid open file descriptor.
.TP 15
EPERM
The caller is not the super-user.
.SH SEE ALSO
.IR nfsd (8)
