.\" Copyright (c) 1983, 1992, 1993
.\"	The Regents of the University of California.  All rights reserved.
.\"
.\" %sccs.include.redist.man%
.\"
.\"     @(#)sigstack.2	8.1 (Berkeley) %G%
.\"
.Dd 
.Dt SIGSTACK 2
.Os BSD 4.2
.Sh NAME
.Nm sigstack
.Nd set and/or get signal stack context
.Sh DESCRIPTION
The 
.Fn sigstack
function has been deprecated in favor of the interface described in
.Xr sigaltstack 2 .
.Sh SEE ALSO
.Xr sigaltstack 2
.Sh HISTORY
The
.Nm
function call appeared in
.Bx 4.2 .
