.\" Copyright (c) 1987 Regents of the University of California.
.\" All rights reserved.
.\"
.\" Redistribution and use in source and binary forms are permitted
.\" provided that the above copyright notice and this paragraph are
.\" duplicated in all such forms and that any documentation,
.\" advertising materials, and other materials related to such
.\" distribution and use acknowledge that the software was developed
.\" by the University of California, Berkeley.  The name of the
.\" University may not be used to endorse or promote products derived
.\" from this software without specific prior written permission.
.\" THIS SOFTWARE IS PROVIDED ``AS IS'' AND WITHOUT ANY EXPRESS OR
.\" IMPLIED WARRANTIES, INCLUDING, WITHOUT LIMITATION, THE IMPLIED
.\" WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE.
.\"
.\"	@(#)install.1	6.7 (Berkeley) %G%
.\"
.TH INSTALL 1 ""
.UC 5
.SH NAME
install \- install binaries
.SH SYNOPSIS
.B install
[
.B \-cs
] [
.B \-m
mode ] [
.B \-o
owner ] [
.B \-g
group ] file1 file2; or file1 ... fileN directory
.SH DESCRIPTION
The file(s) are moved (or copied if the
.I -c
option is specified) to the target file or directory.
If the destination is a directory, then the
.I file
is moved into
.I directory
with its original filename.
If the target file already exists, it is overwritten if permissions
allow.
.PP
The mode is set to 755; the
.I -m
option may be used to specify an alternate mode.
The specified mode may be either an octal or symbolic value; see
.IR chmod (1)
for a description of possible mode values.
.PP
The
.I -o
and
.I -g
options may be used to specify an owner and/or group, respectively.
.PP
The
.I -s
option causes the file to be stripped.
.I Install
exec's the command
.IR strip (1)
to strip binaries so that install can be portable over a large
number of systems and binary types.
.PP
.I Install
refuses to move a file onto itself.
.PP
Installing ``/dev/null'' creates an empty file.
.SH "RETURN VALUE"
Upon successful completion a value of 0 is returned.
Otherwise, a value of 1 is returned.
.SH "SEE ALSO"
chgrp(1), chmod(1), cp(1), mv(1), strip(1), a.out(5), chown(8)
