#!/bin/sh -
#
# Copyright (c) 1989 Jan-Simon Pendry
# Copyright (c) 1989 Imperial College of Science, Technology & Medicine
# Copyright (c) 1989 The Regents of the University of California.
# All rights reserved.
#
# This code is derived from software contributed to Berkeley by
# Jan-Simon Pendry at Imperial College, London.
#
# Redistribution and use in source and binary forms are permitted provided
# that: (1) source distributions retain this entire copyright notice and
# comment, and (2) distributions including binaries display the following
# acknowledgement:  ``This product includes software developed by the
# University of California, Berkeley and its contributors'' in the
# documentation or other materials provided with the distribution and in
# all advertising materials mentioning features or use of this software.
# Neither the name of the University nor the names of its contributors may
# be used to endorse or promote products derived from this software without
# specific prior written permission.
# THIS SOFTWARE IS PROVIDED ``AS IS'' AND WITHOUT ANY EXPRESS OR IMPLIED
# WARRANTIES, INCLUDING, WITHOUT LIMITATION, THE IMPLIED WARRANTIES OF
# MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE.
LAR PURPOSE.
#
#	@(#)Configure	5.1 (Berkeley) 6/29/90
#
echo "Making ./arch and ./os-type executable ..."
until chmod +x ./arch ./os-type; do echo "Error: chmod command failed" >&2; exit 1; done
echo "Checking ./arch and ./os-type ..."
echo ""
arch="`sh ./arch 2>/dev/null`"
os="`sh ./os-type 2>/dev/null`"
case "$arch" in
"") echo "./arch doesn't produce an answer - please check it" >&2; exit 1;;
esac
case "$os" in
"") echo "./os-type doesn't produce an answer - please check it" >&2; exit 1;;
esac
cat << %
This machine appears to be a "$arch" running "$os".
If that is correct just run make.
If those are incorrect please edit ./arch and ./os-type
%
exit 0
