/* Copyright (c) 1979 Regents of the University of California */

/* static	char sccsid[] = "@(#)h01errs.h 4.1 10/10/80"; */

#define EARGV		 1
#define EASRT		 2
#define EASSIGN		 3
#define EBADFNUM	 4
#define EBADINUM	 5
#define EBADOP		 6
#define EBUILTIN	 7
#define ECASE		 8
#define ECHR		 9
#define ECLOSE		10
#define ECREATE		11
#define EFIXADD		13
#define EFIXDIV		14
#define EFIXMUL		15
#define EFIXNEG		16
#define EFIXSUB		17
#define EFLTADD		18
#define EFLTDIV		19
#define EFLTMUL		20
#define EFLTSUB		21
#define EFMTSIZE	22
#define EGOTO		23
#define EHALT		24
#define EINTR		25
#define ELLIMIT		26
#define ELN		27
#define EMODDIV		28
#define ENAMESIZE	29
#define ENAMRNG		30
#define ENILPTR		31
#define ENUMNTFD	32
#define EOPEN		33
#define EOUTOFMEM	34
#define EPACK		35
#define EPASTEOF	36
#define ERANGE		37
#define EREADIT		38
#define EREFINAF	39
#define EREMOVE		40
#define ESEEK		41
#define ESQRT		42
#define ESTKNEMP	43
#define ESTKOVFLO	44
#define ESTLIM		45
#define ESUBSCR		46
#define ESYSTEM		47
#define ETRASHHEAP	48
#define EUNPACK		49
#define EWRITE		50
#define EWRITEIT	51
#define ECTLWR		12
#define ECTUPR		52
#define ECTSNG		53
#define ENARGS		54
