#define EARGV		 1
#define EASRT		 2
#define EBADFNUM	 3
#define EBADINUM	 4
#define ECASE		 5
#define ECHR		 6
#define ECLOSE		 7
#define ECREATE		 8
#define ECTLWR		 9
#define ECTSNG		10
#define ECTUPR		11
#define EFMTSIZE	12
#define EGOTO		13
#define EHALT		14
#define ELLIMIT		15
#define ELN		16
#define ENAMESIZE	17
#define ENAMRNG		18
#define ENILPTR		20
#define ENOFILE		21
#define ENUMNTFD	22
#define EOPEN		23
#define EOUTOFMEM	24
#define EPACK		25
#define EPASTEOF	26
#define ERANGE		27
#define EREADIT		28
#define EREFINAF	29
#define EREMOVE		30
#define ESEEK		31
#define ESQRT		32
#define ESTLIM		33
#define ESUBSC		34
#define EUNPACK		35
#define EWRITE		36
#define EWRITEIT	37
