.\" Copyright (c) 1980 Regents of the University of California.
.\" All rights reserved.  The Berkeley software License Agreement
.\" specifies the terms and conditions for redistribution.
.\"
.\"	@(#)l3tol.3	4.1 (Berkeley) 5/15/85
.\"
.TH L3TOL 3 
.AT 3
.SH NAME
l3tol, ltol3 \- convert between 3-byte integers and long integers
.SH SYNOPSIS
.nf
.B l3tol(lp, cp, n)
.B long *lp;
.B char *cp;
.PP
.B ltol3(cp, lp, n)
.B char *cp;
.B long *lp;
.fi
.SH DESCRIPTION
.I L3tol
converts a list of
.I n
three-byte integers packed into a character string
pointed to by 
.I cp
into a list of long integers pointed to by
.IR lp .
.PP
.I Ltol3
performs the reverse conversion from long integers
.RI ( lp )
to three-byte integers
.RI ( cp ).
.PP
These functions are useful for file-system maintenance
where the i-numbers are three bytes long.
.SH SEE ALSO
filsys(5)
