.\" Copyright (c) 1990 The Regents of the University of California.
.\" All rights reserved.
.\"
.\" %sccs.include.redist.man%
.\"
.\"	@(#)swab.3	6.3 (Berkeley) %G%
.\"
.TH SWAB 3  ""
.AT 3
.nf
.SH NAME
swab \- swap bytes
.SH SYNOPSIS
.nf
.ft B
#include <string.h>

void
swab(const char *src, char *dst, size_t len);
.ft R
.fi
.SH DESCRIPTION
The function
.I swab
copies
.I len
bytes from the location referenced by
.I src
to the location referenced by
.IR dst ,
swapping adjacent bytes.
.PP
.I Len
should be even.
.SH SEE ALSO
bzero(3), memset(3)
