.\" Copyright (c) 1983 Regents of the University of California.
.\" All rights reserved.  The Berkeley software License Agreement
.\" specifies the terms and conditions for redistribution.
.\"
.\"	@(#)insque.3	5.1 (Berkeley) %G%
.\"
.TH INSQUE 3 "18 July 1983"
.UC 5
.SH NAME
insque, remque \- insert/remove element from a queue
.SH SYNOPSIS
.nf
.DT
.ft B
struct qelem {
	struct	qelem *q_forw;
	struct	qelem *q_back;
	char	q_data[];
};
.PP
.ft B
insque(elem, pred)
struct qelem *elem, *pred;
.PP
.ft B
remque(elem)
struct qelem *elem;
.ft R
.SH DESCRIPTION
.I Insque
and 
.I remque
manipulate queues built from doubly linked lists.  Each
element in the queue must in the form of ``struct qelem''.
.I Insque
inserts 
.I elem
in a queue imediately after 
.IR pred ;
.I remque
removes an entry
.I elem 
from a queue.
.SH "SEE ALSO
``VAX Architecture Handbook'', pp. 228-235.
