.\" Copyright (c) 1989 The Regents of the University of California.
.\" All rights reserved.
.\"
.\" %sccs.include.redist.man%
.\"
.\"	@(#)lsearch.3	5.3 (Berkeley) %G%
.\"
.TH LSEARCH 3 ""
.UC 7
.SH NAME
lsearch, lfind, \- linear searching routines
.SH SYNOPSIS
.ft B
.nf
char *
lsearch(const void *key, const void *base,
size_t *nelp, size_t width, 
int (*compar) (void *, void *));
.sp
char *
lfind(const void *key, const void *base,
size_t *nelp, size_t width,
int (*compar) (void *, void *));
.ft R
.SH DESCRIPTION
.ft B
This interface was obsolete before it was written.
It is available from the compatibility library, libcompat.
.ft R
.PP
The functions
.IR lsearch ,
and
.IR lfind
provide basic linear searching functionality.
.PP
.I Base
is the pointer to the beginning of an array.
.I Nelp
is the current number of elements in the array, where each element
is
.I width
bytes long.
.I Compar
is a comparison routine which is used to compare two elements.
It is called with two arguments that point to the 
.I key
object and to an array member, in that order, and must return an integer
less than, equal to, or greater than zero if the 
.I key
object is considered, respectively, to be less than, equal to, or greater
than the array member.
.PP
.I Lsearch
and
.I lfind
return a pointer into the array referenced by
.I base
where
.I key
is located.
If
.I key
does not exist,
.I lfind
will return a NULL pointer and
.I lsearch
will add it to the array.
When an element is added to the array by
.I lsearch
the location referenced by the argument
.I nelp
is incremented by one.
.SH "SEE ALSO"
bsearch(3), hsearch(3), tsearch(3)
