#!/bin/sh
# $Header: makedist,v 4.3 85/05/01 11:42:35 lwall Exp $
#
# $Log:	makedist,v $
# Revision 4.3  85/05/01  11:42:35  lwall
# Baseline for release with 4.3bsd.
# 

rm -f kit*.list
manifake
kitlists
manimake
makekit kit*.list
