#! /bin/sh -
#
# Look for default (and termcap-only?) capabilities.
# Defaults should be removed to save space.
#
#	@(#)tck	5.1	(Berkeley)	10/17/87

showtc $* | \
sed	-n				\
	-e 's/ bc=^H$/DEFAULT &/p'	\
	-e 's/ bc=\\h$/DEFAULT &/p'	\
	-e 's/ bc=\\10$/DEFAULT &/p'	\
	-e 's/ bc=\\010$/DEFAULT &/p'	\
	-e 's/ bl=^G$/DEFAULT &/p'	\
	-e 's/ bl=\\7$/DEFAULT &/p'	\
	-e 's/ bl=\\07$/DEFAULT &/p'	\
	-e 's/ bl=\\007$/DEFAULT &/p'	\
	-e 's/ cr=^M$/DEFAULT &/p'	\
	-e 's/ cr=\\r$/DEFAULT &/p'	\
	-e 's/ cr=\\15$/DEFAULT &/p'	\
	-e 's/ cr=\\015$/DEFAULT &/p'	\
	-e 's/ ff=^L$/DEFAULT &/p'	\
	-e 's/ ff=^L$/DEFAULT &/p'	\
	-e 's/ ff=\\14$/DEFAULT &/p'	\
	-e 's/ ff=\\014$/DEFAULT &/p'	\
	-e 's/ nl=^J$/DEFAULT &/p'	\
	-e 's/ nl=\\n$/DEFAULT &/p'	\
	-e 's/ nl=\\12$/DEFAULT &/p'	\
	-e 's/ nl=\\012$/DEFAULT &/p'	\
	-e 's/ ta=^I$/DEFAULT &/p'	\
	-e 's/ ta=\\t$/DEFAULT &/p'	\
	-e 's/ ta=\\11$/DEFAULT &/p'	\
	-e 's/ ta=\\011$/DEFAULT &/p'	\
					\
	-e 's/ bc$/TERMCAP ONLY &/p'	\
	-e 's/ bs$/TERMCAP ONLY &/p'	\
	-e 's/ dB$/TERMCAP ONLY &/p'	\
	-e 's/ dC$/TERMCAP ONLY &/p'	\
	-e 's/ dF$/TERMCAP ONLY &/p'	\
	-e 's/ dN$/TERMCAP ONLY &/p'	\
	-e 's/ dT$/TERMCAP ONLY &/p'	\
	-e 's/ dV$/TERMCAP ONLY &/p'	\
	-e 's/ EP$/TERMCAP ONLY &/p'	\
	-e 's/ HD$/TERMCAP ONLY &/p'	\
	-e 's/ kn$/TERMCAP ONLY &/p'	\
	-e 's/ ko$/TERMCAP ONLY &/p'	\
	-e 's/ LC$/TERMCAP ONLY &/p'	\
	-e 's/ ma$/TERMCAP ONLY &/p'	\
	-e 's/ ml$/TERMCAP ONLY &/p'	\
	-e 's/ mu$/TERMCAP ONLY &/p'	\
	-e 's/ nc$/TERMCAP ONLY &/p'	\
	-e 's/ NL$/TERMCAP ONLY &/p'	\
	-e 's/ nl$/TERMCAP ONLY &/p'	\
	-e 's/ ns$/TERMCAP ONLY &/p'	\
	-e 's/ OP$/TERMCAP ONLY &/p'	\
	-e 's/ pt$/TERMCAP ONLY &/p'	\
	-e 's/ UC$/TERMCAP ONLY &/p'	\
	-e 's/ xr$/TERMCAP ONLY &/p'	\
	-e 's/ xx$/TERMCAP ONLY &/p'	\
