!
! BOOTSTRAP BY BOOT() SYSCALL
! USED PASSED PARAMETERS
!
HALT
UNJAM
INIT
LOAD BOOT
		! LEAVE R11 ALONE FROM SYSTEM, CHOOSING HOW TO REBOOT
		! LEAVE R10 (DEVICE CHOICE) TO SYSTEM (SAME AS BEFORE)
START 2
