!
! POWER FAIL AND OTHER DISASTER RESTART
!
! NOTE: THIS SCRIPT KNOWS WHICH IS THE PRIMARY DISK BOOTSTRAP!
!
E/Q R0
E/Q R0
HALT
E PSL
E R0/NE:F
E SP
E/V @ /NE:40
UNJAM
INIT
LOAD BOOT
D R11 0			! AUTO-RESTART PARAMETERS - 0=GO MULTI
D R10 0			! DEVICE CHOICE: (HP=0,UP=2,RK=3)
START 2
