.\" Copyright (c) 1980 Regents of the University of California.
.\" All rights reserved.  The Berkeley software License Agreement
.\" specifies the terms and conditions for redistribution.
.\"
.\"	@(#)pti.1	6.1 (Berkeley) %G%
.\"
.TH PTI 1 "%G%"
.UC
.SH NAME
pti \- phototypesetter interpreter
.SH SYNOPSIS
.B pti
[ file ... ]
.SH DESCRIPTION
.I Pti
shows the commands in a stream from the standard output of
.IR troff (1)
using
.I troff's
.B \-t
option,
interpreting them as they would act on the typesetter.
Horizontal motions shows as counts in internal units and
are marked with `<' and `>' indicating left and right motion.
Vertical space is called
.I lead
and is also indicated.
.SH SEE ALSO
troff(1)
.SH BUGS
Too cryptic for normal users, who should use ``troff \-a ...''.
