/* Copyright (c) 1979 Regents of the University of California */
/* adjustable path names, may differ on each machine */
# define NETCMD		"/usr/net/bin/net"
# define NETCMD1	"/usr/net/bin/net"
# define RESFILE	"/usr/net/rcv/rfaaXXXXX"
# define TEMPFILE 	"/usr/net/rcv/tfaaXXXXX"
# define SENDDIR 	"/usr/net/send?"
# define DFNAME 	"/usr/net/send?/dfaaXXXXX"
# define LOGFILE 	"/usr/net/plogfileX"
# define PUBLOGFILE 	"/usr/net/logfile"
# define DUMPFILE 	"/usr/net/netstatX"
# define NAMEFILE	"/usr/net/usernames"
# define BINSH		"/bin/sh"
# define NETRMPATH	"/usr/net/sendY/cfxx0000x"
# define NETRMNAME	"/usr/net/sendY/cfaa0000x"
# define NETDAEMON	"/usr/net/bin/netdaemon"
# define NETQSTAT	"/usr/net/bin/netqstats"

/* adjustable path names, must be the same on all machines */
# define CATCMD 	"/bin/cat"
# define MMAILCMD	"/usr/net/bin/mmail"
# define MWRITECMD	"/usr/net/bin/mwrite"
# define NETCPCMD	"/usr/net/bin/netcp"
# define SENDMAILCMD	"/usr/net/bin/sendmail"
# define PRMAIL		"/usr/net/bin/prmail"
