.so tmac.ilib
.TH LMAN 8 "The University of Arizona \- 8/16/84"
.SH NAME
lman \- format manual page in library style
.SH DESCRIPTION
The manual pages for the Icon Library can be produced with the
head and foot format of the Icon Library manual by using the
macros in \*Mv5g/man/tmac.an\fR, as in
.DS
cd v5g/man
troff tmac.an man1/rsg.1
.DE
.SH NOTE
The text for the manual pages includes files in \*Mv5g/man\fR and
must be formatted in this directory.
