.so tmac.ilib
.TH UMAN 8 "The University of Arizona \- 8/12/84"
.SH NAME
uman \- format manual page in UNIX manual style
.SH DESCRIPTION
The manual pages for the Icon Library can be produced with the
head and foot format of the UNIX manual by using the standard
UNIX manual macros, as in
.DS
cd v5g/man
troff \-man man1/rsg.1
.DE
.SH NOTE
The text for the manual pages includes files in \*Mv5g/man\fR and
must be formatted in this directory.
