#define COMMENT		3
#define LAYER		4
#define WIRE		5
#define BOX		6
#define POLYGON		7
#define ROUNDFLASH	8
#define FLASH		8
#define SYMBOL		9
#define CALL		10
#define EDGE		11
#define ARRAY		12
#define NAME		13
#define TEXT		14
#define POINTNAME	15
#define SWIRE		16
#define SPOLYGON	17
#define SCALL		18
#define SFLASH		19
#define VECTOR		20
#define STEXT		21

#define NONEXIST	0
#define UNUSED		1
#define USED		2
#define UNDEFINED	3
#define ACTIVE		4
#define DELETED		5
#define UNEXAMINED	6

