
.TH VDUMP PUBLIC 2/1/80
.UC
.SH NAME
vdump \- Versatec/Varian plotter
.SH SYNOPSIS
.B vdump tempfile
[
.I banner
[
.I message 
]] [
.B \-W
]
.SH DESCRIPTION
.I Vdump
takes the file 'tempfile' and sends the file directly
to the Varian plotter and then removes 'tempfile'.
The
.B \-W
option sends the file to the Versatec.
If the argument banner is present, it is printed above
the plot.
If the argument
message is present, then when the plot is finnished message is
printed on your screen.
This program is useful when you have a dense plot.
.SH FILES
/usr/public/vdump
.SH ALSO SEE
cifplot (public)
.br
smallcif (public)
