.TH ARPA-MAILER 8 12/31/79
.SH NAME
arpa-mailer \- deliver mail to the
.SM ARPANET
.SH SYNOPSIS
/usr/lib/mailers/arpa
.I from-address
.I to-host
.I to-user
.SH DESCRIPTION
.I Arpa-mailer
queues the letter found on its standard input
for delivery to the host and user specified.
The actual delivery will be performed by the
.SM ARPANET
mailer daemon.
.PP
If the letter does not appear to have a full
.SM ARPANET
header,
.I arpa-mailer
will insert ``Date:'' and ``From:''
fields in the proper format.
The ``From:'' person
is determined by the from-address argument,
with colons translated to periods
and ``@Berkeley'' appended.
The from-address argument
is also used by the
mailer daemon
to return the mail to you
if there is a problem at the receiving host.
.SH FILES
.RI /dev/net/ to-host
.br
/usr/spool/netmail/*
.SH SEE\ ALSO
delivermail(8), mailer(ARPA)
