.TH DELIVERMAIL 8
.SH NAME
delivermail \- deliver mail to arbitrary people
.SH SYNOPSIS
.B /etc/delivermail
[
.BR \- [ fr ]
.I address
] [
.B \-a
] [
.BR \-e [ empqw ]
] [
.B \-n
] [
.B \-m
] [
.B \-s
] [
.B \-i
] [
.B \-h
.I N
] address ...
.SH DESCRIPTION
.I Delivermail
delivers a letter to one or more people,
routing the letter over whatever networks
are necessary.
.I Delivermail
will do inter-net forwarding as necessary
to deliver the mail to the correct place.
.PP
.I Delivermail
is not intended as a user interface routine;
it is expected that other programs will provide user-friendly
front ends,
and
.I delivermail
will be used only to deliver pre-formatted messages.
.PP
.I Delivermail
reads its standard input
up to a control-D
or a single dot
and sends a copy of the letter found there
to all of the addresses listed.
If the
.B \-i
flag is given,
single dots are ignored.
It determines the network to use
based on the syntax of the addresses.
Addresses containing the character `@'
or the word ``at''
are sent to the
.SM ARPANET;
addresses containing `!'
are sent to the
.SM UUCP
net,
and addresses containing `:' or `.'
are sent to the Berkeley network.
Other addresses are assumed to be local.
.PP
Local addresses are looked up in the file
.I /usr/lib/mailaliases
and aliased appropriately.
Aliasing can be prevented by preceeding the address
with a backslash or using the
.B \-n
flag.
Normally the sender is not included in any alias
expansions, e.g.,
if `john' sends to `group',
and `group' includes `john' in the expansion,
then the letter will not be delivered to `john'.
The
.B \-m
flag disables this suppression.
.PP
.I Delivermail
computes the person sending the mail
by looking at your login name.
The ``from'' person
can be explicitly specified by using the
.B \-f
flag;
or, if the
.B \-a
flag is given,
delivermail looks in the body of the message
for a ``From:'' or ``Sender:''
field in
.SM ARPANET
format.
The
.B \-f
and
.B \-a
flags can be used
only by the special users
.I root
and
.I network,
or if the person you are trying to become
is the same as the person you are.
The
.B \-r
flag is entirely equivalent to the
.B \-f
flag; it is provided for ease of interface only.
.PP
The
.BI \-e x
flag controls the disposition of error output,
as follows:
.TP 3n
.B e
Print errors on the standard output,
and echo a copy of the message when done.
It is assumed that a network server will
return the message back to the user.
.TP
.B m
Mail errors back to the user.
.TP
.B p
Print errors on the standard output.
.TP
.B q
Throw errors away;
only exit status is returned.
.TP
.B w
Write errors back to the user's terminal,
but only if the user is still logged in
and write permission is enabled;
otherwise errors are mailed back.
.LP
If the error is not mailed back,
and if the mail originated on the machine where the error occurred,
the letter is appended to the file
.I dead.letter
in the sender's home directory.
.PP
If the first character of the user name
is a vertical bar,
the rest of the user name is used as the name of a program
to pipe the mail to.
It may be necessary to quote the name of the user
to keep
.I delivermail
from supressing the blanks from between arguments.
.PP
The message is normally editted to eliminate ``From''
lines that might confuse other mailers.
In particular,
``From'' lines in the header are deleted,
and ``From'' lines in the body are prepended by `>'.
The
.B \-s
flag saves ``From'' lines in the header.
.PP
The
.B \-h
flag gives a ``hop-count'', i.e.,
a measure of how many times this message
has been processed by
.I delivermail
(presumably on different machines).
Each time
.I delivermail
processes a message,
it increases the hop-count by one;
if it exceeds 30
.I delivermail
assumes that an alias loop has occured
and it aborts the message.
The hop-count defaults to zero.
.PP
.I Delivermail
returns an exit status
describing what it did.
The codes are defined in
.IR mailexits.h :
.ta 3n +\w'EX_UNAVAILABLE'u+3n
.de XX
.ti \n(.iu
..
.in +\w'EX_UNAVAILABLE'u+6n
.XX
0	EX_OK	Succesful completion on all addresses.
.XX
2	EX_NOUSER	User name not recognized.
.XX
3	EX_UNAVAILABLE	Catchall meaning necessary resources
were not available.
.XX
4	EX_SYNTAX	Syntax error in address.
.XX
5	EX_SOFTWARE	Internal software error,
including bad arguments.
.XX
6	EX_OSERR	Temporary operating system error,
such as ``cannot fork''.
.XX
7	EX_NOHOST	Host name not recognized.
.DT
.PP
.SH FILES
.in +10
.ti -10
/usr/lib/mailaliases \- to alias names
.ti -10
/bin/mail \- to deliver local mail
.ti -10
/usr/net/bin/sendmail \- to deliver Berkeley mail
.ti -10
/usr/lib/mailers/arpa \- to deliver
.SM ARPANET
mail
.ti -10
/usr/lib/mailers/uucp \- to deliver
.SM UUCP
mail
.ti -10
/tmp/mail* \- temp file
.ti -10
/tmp/xscript* \- saved transcript
.ti -10
/dev/log \- to log status (optional)
.in -10
.SH SEE\ ALSO
mail(1), Mail(UCB), arpa-mailer(8), uucp-mailer(8),
mailaliases(5), userinfo(5)
.SH BUGS
.I Delivermail
sends one copy of the letter
to each user;
it should send one copy
of the letter to each host
and distribute to multiple users there
whenever possible.
.PP
.I Delivermail
assumes the addresses can be represented as one word.
This is incorrect according to the
.SM ARPANET
mail protocol RFC 733 (NIC 41952),
but is consistant with the real world.
