.so tmac.ilib
.TH SHUFFLE 2 "The University of Arizona \- 7/29/84"
.SH NAME
shuffle \- shuffle string or list
.SH DESCRIPTION
The procedure \*Mshuffle(x)\fR shuffles a string or list. In the case
that \*Mx\fR is a string, a corresponding string with the characters
randomly rearranged is produced. In the case that \*Mx\fR is a list,
the values in the list are randomly rearranged.
.SH DIAGNOSTIC
Run-time time error 102 occurs if \*Mx\fR is not a list, a string, or
a value that can be converted to a string.
.SH SEE ALSO
.Ib
p. 187.
.SH AUTHORS
Ward Cunningham and Ralph E. Griswold
