.so tmac.ilib
.TH STRUCTS 2 "The University of Arizona \- 4/26/83"
.SH NAME
structs \- structure operations
.SH DESCRIPTION
These procedures for manipulating structures are taken from \fIThe Icon
Programming Language\fR.
.SH SYNOPSIS
.nf
.ta 1.5i
\*Mdepth(a)\fR	compute maximum depth of tree \*Ma\fR
\*Meq(x,\*by)\fR	compare list structures \*Mx\fR and \*My\fR
\*Mldag(s)\fR	construct a dag from the string \*Ms\fR
\*Mlgraph(s)\fR	construct a graph from the string \*Msgraph\fR
\*Mltree(s)\fR	construct a tree from the string \*Ms\fR
\*Mstree(a)\fR	construct a string from the list \*Ma\fR
\*Mtcopy(a)\fR	copy tree \*Ma\fR
\*Mteq(a1,\*ba2)\fR	compare trees \*Ma1\fR and \*Ma2\fR
\*Mvisit(a)\fR	visit, in preorder, the nodes of \*Ma\fR
.SH NOTE
The procedure \*Mldag\fR has a second argument that is used on internal
recursive calls; a second argument must not be supplied by the user.
.SH SEE ALSO
.Ib
pp. 170-180, 295.
.SH AUTHOR
Ralph E. Griswold
