.TH LIBNS 3 4/8/79 3
.SH NAME
libNS \- modified standard i/o library allowing concurrent read/write to a stream
.SH SYNOPSIS
.B #include <nstdio.h>
.br
\fBcc ... \-lNS\fR
.SH DESCRIPTION
This is a modified standard i/o library which allows you to open files ``rw''
or ``ra'', and to then both read and write the resultant streams.
.SH SEE ALSO
fopen(3), getc(3)
.SH AUTHOR
Modifications by Keith Sklower
.SH BUGS
