/* iso3166.c - bitmap of ISO 3166 codes */

#ifndef	lint
/*
static char *rcsid = "$Header: /f/osi/dsap/common/RCS/iso3166.h,v 7.2 91/02/22 09:19:27 mrose Interim $";
 */
#endif

/* 
 * $Header: /f/osi/dsap/common/RCS/iso3166.h,v 7.2 91/02/22 09:19:27 mrose Interim $
 *
 *
 * $Log:	iso3166.h,v $
 * Revision 7.2  91/02/22  09:19:27  mrose
 * Interim 6.8
 * 
 * Revision 7.1  90/12/11  10:53:54  mrose
 * lock-and-load
 * 
 * Revision 7.0  90/12/10  14:26:03  mrose
 * *** empty log message ***
 * 
 */

/*
 *				  NOTICE
 *
 *    Acquisition, use, and distribution of this module and related
 *    materials are subject to the restrictions of a license agreement.
 *    Consult the Preface in the User's Manual for the full terms of
 *    this agreement.
 *
 */


/* LINTLIBRARY */


/* The idea for this comes from EWOS/EGDIR/90/156

   The table below was automatically generated by "dsaconfig -c".  If the list
   of 3166 codes change, re-run dsaconfig and update this file!
 */


/* this macro assumes that bitno is already defined, and that chars are already
   in upper-case. */

#define	is3166(cp) \
    (bitno = (((((cp)[0]) - 'A') & 0xff) * 26) + ((((cp)[1]) - 'A') & 0xff), \
	bits_3166[bitno >> 3] & (1 << (bitno % 8)))


static unsigned char bits_3166[85] = {
    0x78,
    0x69,
    0x5f,
    0xe8,
    0xcf,
    0xf9,
    0x5d,
    0xde,
    0x67,
    0x1b,
    0x86,
    0x15,
    0x80,
    0xc4,
    0x00,
    0x0c,
    0x00,
    0x5c,
    0x09,
    0xb0,
    0x9a,
    0xbb,
    0x15,
    0x00,
    0x0d,
    0x06,
    0x18,
    0x68,
    0x0f,
    0x00,
    0x40,
    0x03,
    0x00,
    0x19,
    0x2b,
    0xd4,
    0x41,
    0x81,
    0x45,
    0xc5,
    0xe8,
    0xff,
    0xd7,
    0x25,
    0x6b,
    0x08,
    0x00,
    0x01,
    0x40,
    0x3c,
    0x8f,
    0x52,
    0x01,
    0x00,
    0x00,
    0x40,
    0x00,
    0x01,
    0xf1,
    0xad,
    0xa7,
    0x33,
    0x3b,
    0xb9,
    0x9a,
    0x41,
    0x10,
    0x04,
    0x55,
    0x85,
    0x40,
    0x00,
    0x02,
    0x40,
    0x00,
    0x00,
    0x00,
    0x00,
    0x18,
    0x00,
    0x10,
    0x04,
    0x40,
    0x08,
    0x01,
};
