; This file, when loaded, creates the mh keymap. Explicitly loaded from the
; root.

    (progn loop
	(save-excursion
	    (temp-use-buffer "+inbox")
	    (define-keymap "&mh-keymap")
	    (define-keymap "&mh-x-keymap")
	    (use-local-map "&mh-keymap")
	    (setq loop 0)
	    (while (<= loop 127)
		(local-bind-to-key "&mh-summary" loop)
		(setq loop (+ loop 1))
	    )
	    (setq loop '0')
	    (while (<= loop '9')
		(local-bind-to-key "digit" loop)
		(setq loop (+ loop 1))
	    )
	    (local-bind-to-key "&mh-help" "?")
	    (local-bind-to-key "&mh-Mark-file-deleted" "d")
	    (local-bind-to-key "&mh-Mark-file-deleted" "D")
	    (local-bind-to-key "&mh-Mark-file-deleted" "")
	    (local-bind-to-key "&mh-move" "^")
	    (local-bind-to-key "&mh-re-move" "!")
	    (local-bind-to-key "&mh-previous-line" "\")
	    (local-bind-to-key "&mh-previous-line" "\")
	    (local-bind-to-key "&mh-previous-line" "p")
	    (local-bind-to-key "&mh-previous-line" "P")
	    (local-bind-to-key "previous-line" "\^P")
	    (local-bind-to-key "next-line" "\^N")
	    (local-bind-to-key "&mh-next-line" "n")
	    (local-bind-to-key "&mh-next-line" "N")
	    (local-bind-to-key "&mh-next-line" "\")
	    (local-bind-to-key "redraw-display" "\")
	    (local-bind-to-key "search-forward" "\")
	    (local-bind-to-key "search-reverse" "\")
	    (local-bind-to-key "argument-prefix" "\^U")
	    (local-bind-to-key "previous-window" "\^Xp")
	    (local-bind-to-key "previous-window" "\^XP")
	    (local-bind-to-key "next-window" "\^Xn")
	    (local-bind-to-key "next-window" "\^XN")
	    (local-bind-to-key "delete-window" "\^Xd")
	    (local-bind-to-key "delete-window" "\^XD")
	    (local-bind-to-key "delete-other-windows" "\^X1")
	    (local-bind-to-key "visit-file" "\^X\^V")
	    (local-bind-to-key "next-page" "\^V")
	    (local-bind-to-key "redraw-display" "\")
	    (local-bind-to-key "previous-page" "\ev")
	    (local-bind-to-key "previous-page" "\eV")
	    (local-bind-to-key "scroll-one-line-up" "")
	    (local-bind-to-key "scroll-one-line-down" "\e")
	    (local-bind-to-key "beginning-of-file" "\e<")
	    (local-bind-to-key "end-of-file" "\e>")
	    (local-bind-to-key "return-to-monitor" "\")
	    (local-bind-to-key "&mh-unmark" "u")
	    (local-bind-to-key "&mh-unmark" "U")
	    (local-bind-to-key "exit-emacs" "\\")
	    (local-bind-to-key "&mh-show" "t")
	    (local-bind-to-key "&mh-show" "T")
	    (local-bind-to-key "&mh-edit" "e")
	    (local-bind-to-key "&mh-edit" "E")
	    (local-bind-to-key "&mh-repl" "R")
	    (local-bind-to-key "&mh-repl" "r")
	    (local-bind-to-key "&mh-send" "m")
	    (local-bind-to-key "&mh-send" "M")
	    (local-bind-to-key "&mh-forw" "f")
	    (local-bind-to-key "&mh-forw" "F")
	    (local-bind-to-key "&mh-remove" "\")
	    (local-bind-to-key "&mh-new-folder" "\\")
	    (local-bind-to-key "&mh-new-folder" "g")
	    (local-bind-to-key "&mh-new-folder" "G")
	    (local-bind-to-key "&mh-bboard" "b")
	    (local-bind-to-key "&mh-bboard" "B")
	    (local-bind-to-key "&mh-inc" "i")
	    (local-bind-to-key "&mh-inc" "I")
	    (local-bind-to-key "&mh-extras" "x")
	    (local-bind-to-key "&mh-extras" "X")

	    (temp-use-buffer "mh-xcommands")
	    (use-local-map "&mh-x-keymap")
	    (setq loop 0)
	    (while (<= loop 255)
		   (local-bind-to-key "&mh-beep" loop)
		   (setq loop (+ loop 1))
	    )
	    (local-bind-to-key "exit-emacs" "q")
	    (local-bind-to-key "next-page" "")
	    (local-bind-to-key "previous-page" "\ev")
	    (local-bind-to-key "previous-page" "\eV")
	    (local-bind-to-key "beginning-of-file" "\e<")
	    (local-bind-to-key "end-of-file" "\e>")
	    (local-bind-to-key "exit-emacs" "Q")
	    (local-bind-to-key "exit-emacs" "")
	)
    )
