.so tmac.ilib
.TH QUEENS 6 "The University of Arizona \- 7/29/84"
.SH NAME
queens \- solutions to n-queens problem
.SH SYNOPSIS
\f3queens\fP [\fIn\fR]
.SH DESCRIPTION
\fIQueens\fR displays the solutions to the nonattacking queens problem.
The number of queens is given by \fIn\fR; the default is 6.
.SH AUTHOR
Stephen B. Wampler
