.\" Copyright (c) 1980 Regents of the University of California.
.\" All rights reserved.  The Berkeley software License Agreement
.\" specifies the terms and conditions for redistribution.
.\"
.\"	@(#)hangman.6	6.1 (Berkeley) %G%
.\"
.TH HANGMAN 6 ""
.UC 4
.SH NAME
hangman \- the game of hangman
.SH SYNOPSIS
.B /usr/games/hangman
.SH DESCRIPTION
In
.I hangman,
the computer picks a word from the on-line word list
and you must try to guess it.
The computer keeps track of which letters have been guessed
and how many wrong guesses you have made on the screen in a graphic fashion.
.SH FILES
/usr/dict/words     On-line word list
.SH AUTHOR
Ken Arnold
