.\" Copyright (c) 1980 Regents of the University of California.
.\" All rights reserved.  The Berkeley software License Agreement
.\" specifies the terms and conditions for redistribution.
.\"
.\"	@(#)mail0.nr	4.1 (Berkeley) %G%
.\"
.if n \
.nr fs .5v
.he 'Mail Reference Manual'\n(mo/\n(dy/\n(yr'%'
.tp
.sp 1.5i
.sz 12
.rb
.(l C
MAIL REFERENCE MANUAL
.)l
.sz 10
.sp 2
.i
.(l C
Kurt Shoens
.)l
.r
.(l C
Version 1.3


\*(td
.)l
.pn 2
