.\" Copyright (c) 1980 Regents of the University of California.
.\" All rights reserved.  The Berkeley software License Agreement
.\" specifies the terms and conditions for redistribution.
.\"
.\"	@(#)intro.4	6.5 (Berkeley) 6/23/90
.\"
.TH INTRO 4 "June 23, 1990"
.UC 4
.SH NAME
intro \- introduction to special files and hardware support
.SH DESCRIPTION
This section describes the special files, related driver functions,
and networking support
available in the system.
In this part of the manual, the SYNOPSIS section of
each configurable device gives a sample specification
for use in constructing a system description for the
.IR config (8)
program.
The DIAGNOSTICS section lists messages which may appear on the console
and/or in the system error log
.I /var/log/messages
due to errors in device operation;
see
.IR syslogd (8)
for more information.
.SH "VAX DEVICE SUPPORT"
This section describes the hardware supported on the DEC VAX-11.
Software support for these devices comes in two forms.  A hardware
device may be supported with a character or block
.IR "device driver" ,
or it may be used within the networking subsystem and have a
.IR "network interface driver" .
Block and character devices are accessed through files in the file
system of a special type; c.f.
.IR mknod (8).
Network interfaces are indirectly accessed through the interprocess
communication facilities provided by the system; see
.IR socket (2).
.PP
A hardware device is identified to the system at configuration time
and the appropriate device or network interface driver is then compiled
into the system.  When the resultant system is booted, the
autoconfiguration facilities in the system probe for the device
on either the UNIBUS (or Q-bus) or MASSBUS and, if found, enable the software
support for it.  If a UNIBUS device does not respond at autoconfiguration
time it is not accessible at any time afterwards.  To
enable a UNIBUS device which did not autoconfigure, the system will have to
be rebooted.  If a
MASSBUS device comes ``on-line'' after the autoconfiguration sequence
it will be dynamically autoconfigured into the running system.
.PP
The autoconfiguration system is described in
.IR autoconf (4).
A list of the supported devices is given below.
.SH SEE ALSO
intro(4), netintro(4), autoconf(4), config(8).
.PP
Building 4.3BSD UNIX Systems with \fIConfig\fP (SMM:2)
.SH "LIST OF DEVICES"
The devices listed below are supported in this incarnation of
the system.  Pseudo-devices are not listed.
Devices are indicated by their functional interface.
If second vendor products provide functionally identical interfaces
they should be usable with the supplied software.
(\fBBeware, however, that we promise the software works
ONLY with the hardware indicated on the appropriate manual page.\fP)
Occasionally, new devices of a similar type may be added
simply by creating appropriate table entries in the driver.
.sp
.ta 1.0i
.nf
acc	ACC LH/DH IMP communications interface
ad	Data translation A/D interface
css	DEC IMP-11A communications interface
crl	VAX 8600, 8650 console RL02 disk
ct	C/A/T or APS phototypesetter
ddn	ACC ACP625 DDN Standard Mode X.25 IMP interface
de	DEC DEUNA 10Mb/s Ethernet controller
dh	DH-11 emulators, terminal multiplexor
dhu	DHU-11 terminal multiplexor
dmc	DEC DMC-11/DMR-11 point-to-point communications device
dmf	DEC DMF-32 terminal multiplexor and parallel printer interface
dmz	DEC DMZ-32 terminal multiplexor
dn	DEC DN-11 autodialer interface
dz	DZ-11 terminal multiplexor
ec	3Com 10Mb/s Ethernet controller
en	Xerox 3Mb/s Ethernet controller (obsolete)
ex	Excelan 10Mb/s Ethernet controller
fl	VAX-11/780 console floppy interface
hdh	ACC IF-11/HDH IMP interface
hk	RK6-11/RK06 and RK07 moving head disk
hp	MASSBUS disk interface (with RP06, RM03, RM05, etc.)
ht	TM03 MASSBUS tape drive interface (with TE-16, TU-45, TU-77)
hy	DR-11B or GI-13 interface to an NSC Hyperchannel
ik	Ikonas frame buffer graphics device interface
il	Interlan 1010, 1010A 10Mb/s Ethernet controller
ix	Interlan NP-100 10Mb/s Ethernet controller
kg	KL-11/DL-11W line clock
lp	LP-11 parallel line printer interface
mt	TM78 MASSBUS tape drive interface
np	Interlan NP-100 10Mb/s Ethernet controller (intelligent mode)
pcl	DEC PCL-11 communications interface
ps	Evans and Sutherland Picture System 2 graphics interface
qe	DEC DEQNA Q-bus 10 Mb/s Ethernet interface
rx	DEC RX02 floppy interface
tm	TM-11/TE-10 tape drive interface
tmscp	TMSCP-compatible tape controllers (e.g., TU81, TK50)
ts	TS-11 tape drive interface
tu	VAX-11/730 TU58 console cassette interface
uda	DEC UDA-50 disk controller
un	DR-11W interface to Ungermann-Bass
up	Emulex SC-21V, SC-31 UNIBUS disk controller
ut	UNIBUS TU-45 tape drive interface
uu	TU58 dual cassette drive interface (DL11)
va	Benson-Varian printer/plotter interface
vp	Versatec printer/plotter interface
vv	Proteon proNET 10Mb/s and 80Mb/s ring network interface
