.\" Copyright (c) 1983 Regents of the University of California.
.\" All rights reserved.  The Berkeley software License Agreement
.\" specifies the terms and conditions for redistribution.
.\"
.\"	@(#)mailaddr.7	5.1 (Berkeley) %G%
.\"
.\"	@(#)mailaddr.7	4.1		7/28/83
.TH MAILADDR 7
.UC 5
.SH NAME
mailaddr \- mail addressing description
.SH DESCRIPTION
Mail addresses are based on the ARPANET protocol
listed at the end of this manual page.
These addresses are in the general format
.PP
		user@domain
.PP
where a domain is a hierarchical dot separated list of subdomains.
For example,
the address
.PP
		eric@monet.Berkeley.ARPA
.PP
is normally interpreted from right to left:
the message should go to the ARPA name tables
(which do not correspond exactly to the physical ARPANET),
then to the Berkeley gateway,
after which it should go to the local host monet.
When the message reaches monet it is delivered to the user ``eric''.
.PP
Unlike some other forms of addressing,
this does not imply any routing.
Thus,
although this address is specified as an ARPA address,
it might travel by an alternate route
if that was more convenient or efficient.
For example,
at Berkeley the associated message
would probably go directly to monet over the Ethernet
rather than going via the Berkeley ARPANET gateway.
.PP
.I Abbreviation.
Under certain circumstances
it may not be necessary to type the entire domain name.
In general anything following the first dot
may be omitted
if it is the same as the domain from which you are sending the message.
For example,
a user on
``calder.Berkeley.ARPA''
could send to
``eric@monet''
without adding the
``.Berkeley.ARPA''
since it is the same on both sending and receiving hosts.
.PP
Certain other abbreviations may be permitted
as special cases.
For example,
at Berkeley ARPANET hosts can be referenced
without adding the
``.ARPA''
as long as their names do not conflict
with a local host name.
.PP
.I Compatibility.
Certain old address formats
are converted to the new format
to provide compatibility with the previous mail system.
In particular,
.PP
		host:user
.PP
is converted to
.PP
		user@host
.PP
to be consistent with the
.IR rcp (1C)
command.
.PP
Also, the syntax:
.PP
		host!user
.PP
is converted to:
.PP
		user@host.UUCP
.PP
This is normally converted back to the
``host!user''
form
before being sent on for compatibility with older UUCP hosts.
.PP
The current implementation is not able to route messages
automatically through the UUCP network.
Until that time you must explicitly tell the mail system
which hosts to send your message through
to get to your final destination.
.PP
.I Case Distinctions.
Domain names (i.e., anything after the ``@'' sign)
may be given in any mixture of upper and lower case
with the exception of UUCP hostnames.
Most hosts accept any mixture of case in user names,
with the notable exception of MULTICS sites.
.PP
.I Differences with ARPA Protocols.
Although the UNIX addressing scheme
is based on the ARPA mail addressing protocols,
there are some significant differences.
.PP
At the time of this writing
the only
``top level''
domain defined by ARPA is the
``.ARPA''
domain itself.
This is further restricted to having only one level of host specifier.
That is,
the only addresses that ARPA accepts at this time must be in the format
``user@host.ARPA''
(where ``host'' is one word).
In particular,
addresses such as:
.PP
		eric@monet.Berkeley.ARPA
.PP
are not currently legal
under the ARPA protocols.
For this reason,
these addresses are converted to a different format on output
to the ARPANET,
typically:
.PP
		eric%monet@Berkeley.ARPA
.PP
.I Route-addrs.
Under some circumstances
it may be necessary to route a message
through several hosts
to get it to the final destination.
Normally this routing is done automatically,
but sometimes it is desirable to route the message manually.
An address that shows these relays are termed
``route-addrs.''
These use the syntax:
.PP
		<@hosta,@hostb:user@hostc>
.PP
This specifies that the message should be sent to hosta,
from there to hostb,
and finally to hostc.
This path is forced
even if there is a more efficient path
to hostc.
.PP
Route-addrs
occur frequently on return addresses,
since these are generally augmented by the software
at each host.
It is generally possible to ignore all but the
``user@host''
part of the address to determine the actual sender.
.PP
.I Postmaster.
Every site is required to have a user or user alias
designated
``postmaster''
to which problems with the mail system may be addressed.
.PP
.I CSNET.
Messages to CSNET sites can be sent to
``user.host@UDel-Relay''.
.SH BERKELEY
The following comments apply only to the Berkeley environment.
.PP
.I Host Names.
Many of the old familiar host names
are being phased out.
In particular,
single character names as used in Berknet
are incompatible with the larger world
of which Berkeley is now a member.
For this reason
the following names
are being obsoleted.
You should notify any correspondents
of your new address
as soon as possible.
.PP
.ta 1i 1.2i 2.5i
	OLD	NEW
	j	ingvax	ucbingres
	p		ucbcad
	r	arpavax	ucbarpa
	v	csvax	ucbernie
	n		ucbkim
	y		ucbcory
.PP
The old addresses will be rejected as unknown hosts
sometime in the near future.
.PP
.I What's My Address?
If you are on a local machine,
say monet,
your address is
.PP
		yourname@monet.Berkeley.ARPA
.PP
However, since most of the world does not have the new software
in place yet,
you will have to give correspondents slightly different addresses.
From the ARPANET,
your address would be:
.PP
		yourname%monet@Berkeley.ARPA
.PP
From UUCP, your address would be:
.PP
		ucbvax!yourname%monet
.PP
.I Computer Center.
The Berkeley Computer Center
is in a subdomain of Berkeley.
Messages to the computer center
should be addressed to:
.PP
		user%host.CC@Berkeley.ARPA
.PP
The alternate syntax:
.PP
		user@host.CC
.PP
may be used if the message is sent from inside Berkeley.
.PP
For the time being
Computer Center hosts
are known within the Berkeley domain,
i.e.,
the
``.CC''
is optional.
However,
it is likely that this situation will change
with time as both the Computer Science department
and the Computer Center grow.
.PP
.I Bitnet.
Hosts on bitnet may be accessed using:
.PP
		user@host.BITNET
.PP
.SH SEE ALSO
mail(1), sendmail(8);
Crocker, D. H.,
.ul
Standard for the Format of Arpa Internet Text Messages,
RFC822.
