#define ECHR 1
#define EDIVCHK 2
#define EFDIVCHK 3
#define EHALT 4
#define ENILPTR 5
#define EPASTEOF 6
#define ESQRT 7
#define ESTKNEMP 8
#define ESUBSCR 9
#define EREFINAF 10
#define EWRITE 11
#define ECREATE 12
#define ELN 13
#define EBADOP 14
#define EBADINUM 15
#define EGOTO 16
#define ECASE 17
#define ESEEK 18
#define EALLOC 19
#define EOUTOFMEM 20
#define ECTTOT 21
#define ETOODIGITS 22
#define EMODCHK 23
#define EBADFNUM 24
#define EREMOVE 25
#define ECLOSE 26
#define EOPEN 27
#define EARGV 28
#define EPACK 29
#define EUNPACK 30
#define ERANGE 31
#define EASRT 32
#define EREADIT 33
#define EWRITEIT 34
#define EBIGGIE 35
#define ESTLIM 36
#define ESTKOVFLO 37
#define EINTR 38
