.TH ATOF 3 
.SH NAME
atof, atoi, atol \- convert ASCII to numbers
.SH SYNOPSIS
.B double atof(nptr)
.br
.B char *nptr;
.PP
.B atoi(nptr)
.br
.B char *nptr;
.PP
.B long atol(nptr)
.br
.B char *nptr;
.SH DESCRIPTION
These functions convert a string pointed to by
.I nptr
to floating, integer, and long integer
representation respectively.
The first unrecognized character ends the string.
.PP
.I Atof
recoginizes an optional string of tabs and spaces,
then an optional sign, then
a string of digits optionally containing a decimal
point, then an optional `e' or `E' followed
by an optionally signed integer.
.PP
.I Atoi
and
.I atol
recognize an optional string of tabs and spaces,
then an optional sign, then a string of
digits.
.SH SEE ALSO
scanf(3)
.SH BUGS
There are no provisions for overflow.
