.\" Copyright (c) 1980 Regents of the University of California.
.\" All rights reserved.  The Berkeley software License Agreement
.\" specifies the terms and conditions for redistribution.
.\"
.\"	@(#)cd.1	6.1 (Berkeley) 4/29/85
.\"
.TH CD 1 "April 29, 1985"
.UC 4
.SH NAME
cd \- change working directory
.SH SYNOPSIS
.B cd
directory
.SH DESCRIPTION
.I Directory
becomes the new working directory.
The process must have execute (search)
permission in
.IR directory .
.PP
Because a new process is created to execute each command,
.I cd
would be ineffective if it were written as a
normal command.  It is therefore recognized and executed
by the shells.
In
.IR csh (1)
you may specify a list of directories in which
.I directory
is to be sought as a subdirectory if it is not
a subdirectory of the current directory;
see the description of the
.I cdpath
variable in
.IR csh (1).
.SH "SEE ALSO"
csh(1), sh(1), pwd(1), chdir(2)
