.\" Copyright (c) 1980 Regents of the University of California.
.\" All rights reserved.  The Berkeley software License Agreement
.\" specifies the terms and conditions for redistribution.
.\"
.\"	@(#)expand.1	6.2 (Berkeley) 5/9/86
.\"
.TH EXPAND 1 "May 9, 1986"
.UC 4
.SH NAME
expand, unexpand \- expand tabs to spaces, and vice versa
.SH SYNOPSIS
.B expand
[
\-tabstop
] [
\-tab1,tab2,...,tabn
] [
file ...
]
.br
.B unexpand
[
.B \-a
] [
file ...
]
.SH DESCRIPTION
.I Expand
processes the named files or the standard input writing
the standard output with tabs changed into blanks.
Backspace characters are preserved into the output and decrement
the column count for tab calculations.
.I Expand
is useful for pre-processing character files
(before sorting, looking at specific columns, etc.) that
contain tabs.
.PP
If a single
.I tabstop
argument is given, then tabs are set
.I tabstop
spaces apart instead of the default 8.
If multiple tabstops are given then the tabs are set at those
specific columns.
.PP
.I Unexpand
puts tabs back into the data from the standard input or the named
files and writes the result on the standard output.
By default, only leading blanks and tabs
are reconverted to maximal strings of tabs.  If the
.B \-a
option is given, then tabs are inserted whenever they would compress the
resultant file by replacing two or more characters.
