.\" Copyright (c) 1983 Regents of the University of California.
.\" All rights reserved.  The Berkeley software License Agreement
.\" specifies the terms and conditions for redistribution.
.\"
.\"	@(#)fsplit.1	6.1 (Berkeley) 4/29/85
.\"
.TH FSPLIT 1 "April 29, 1985"
.UC 5
.SH NAME
fsplit \- split a multi-routine Fortran file into individual files
.SH SYNOPSIS
.B fsplit
[ 
.B -e 
efile] ... [ file ]
.SH DESCRIPTION
.B Fsplit
takes as input either a file or standard input containing Fortran source code.
It attempts to split the input into separate routine files of the
form
.I name.f,
where
.I name
is the name of the program unit (e.g. function, subroutine, block data or
program).  The name for unnamed block data subprograms has the form
.I blkdtaNNN.f
where NNN is three digits and a file of this name does not already exist.
For unnamed main programs the name has the form
.I mainNNN.f.
If there is an error in classifying a program unit, or if
.I name.f
already exists,
the program unit will be put in a file of the form 
.I zzzNNN.f
where 
.I zzzNNN.f 
does not already exist.
.PP
Normally each subprogram unit is split into a separate file.  When the
.I -e
option is used, only the specified subprogram units are split into separate
files.  E.g.:
.nf
	fsplit -e readit -e doit prog.f
.fi
will split readit and doit into separate files.
.SH DIAGNOSTICS
If names specified via the 
.I -e
option are not found, a diagnostic is written to 
.I standard 
.I error.
.SH AUTHOR
Asa Romberger and Jerry Berkman
.SH BUGS
.I Fsplit
assumes the subprogram name is on the first noncomment line of the subprogram
unit.  Nonstandard source formats may confuse 
.I fsplit.
.PP
It is hard to use 
.I -e
for unnamed main programs and block data subprograms since you must 
predict the created file name.
