.\" Copyright (c) 1983 Regents of the University of California.
.\" All rights reserved.  The Berkeley software License Agreement
.\" specifies the terms and conditions for redistribution.
.\"
.\"	@(#)gcore.1	6.1 (Berkeley) 4/29/85
.\"
.TH GCORE 1 "April 29, 1985"
.UC 5
.SH NAME
gcore \- get core images of running processes
.SH SYNOPSIS
.B gcore
process-id ...
.SH DESCRIPTION
.I Gcore
creates a core image of each specified process,
suitable for use with
.IR adb (1)
or
.IR dbx (1).
.SH FILES
core.<process-id>	core images
.SH BUGS
Paging activity that occurs while
.I gcore
is running may cause the program
to become confused.
For best results,
the desired processes should be stopped.
