.\" Copyright (c) 1983 Regents of the University of California.
.\" All rights reserved.  The Berkeley software License Agreement
.\" specifies the terms and conditions for redistribution.
.\"
.\"	@(#)groups.1	6.1 (Berkeley) 4/29/85
.\"
.TH GROUPS 1 "April 29, 1985"
.UC 5
.SH NAME
groups \- show group memberships
.SH SYNOPSIS
.B
groups [user]
.SH DESCRIPTION
The
.I groups
command shows the groups to which you or the optionally specified
user belong.
Each user belongs to a group specified in the password file
.I /etc/passwd
and possibly to other groups as specified in the file
.IR /etc/group .
If you do not own a file but belong to the group which it is owned
by then you are granted group access to the file.
.PP
When a new file is created it is given
the group of the containing directory.
.SH "SEE ALSO"
setgroups(2)
.SH FILES
/etc/passwd, /etc/group
.SH BUGS
More groups should be allowed.
