.\" Copyright (c) 1985 Regents of the University of California.
.\" All rights reserved.  The Berkeley software License Agreement
.\" specifies the terms and conditions for redistribution.
.\"
.\"	@(#)whois.1	6.2 (Berkeley) 6/6/85
.\"
.TH WHOIS 1 "June 6, 1985"
.UC 6
.SH NAME
whois \- DARPA Internet user name directory service
.SH SYNOPSIS
.B whois
name
.SH DESCRIPTION
.TP
whois help
Produces a helpful message similar to the following:
.PP
Please enter a name or a handle (``ident"), such as ``Smith"
or ``SRI-NIC".
Starting with a period forces a name-only search;
starting with exclamation point forces handle-only.
Examples:
.nf
	Smith			[looks for name or handle SMITH	]
	!SRI-NIC			[looks for handle SRI-NIC only	]
	.Smith, John		[looks for name JOHN SMITH only	]
.fi
Adding ``..." to the argument will match anything from that point,
e.g. ``ZU..." will match ZUL, ZUM, etc.
.PP
To have the ENTIRE membership list of a group or organization,
if you are asking about a group or org, shown with the record, use
an asterisk character `*' directly preceding the given argument.
[CAUTION: If there are a lot of members this will take a long time!]
You may of course use exclamation point and asterisk, or a period
and asterisk together.
.SH SEE ALSO
RFC 812:  Nicname/Whois
