.\" Copyright (c) 1991 Regents of the University of California.
.\" All rights reserved.
.\"
.\" %sccs.include.redist.roff%
.\"
.\"     @(#)sum.1	6.2 (Berkeley) %G%
.\"
.Dd 
.Dt SUM 1
.Os
.Sh NAME
.Nm sum
.Nd calculate file checksums and block counts
.Sh SYNOPSIS
.Nm sum
.Ar file
.Sh DESCRIPTION
The
.Nm sum
utility calculates and writes to standard output a
checksum (16 bit CRC) for each input file,
and also writes to the standard output the number of blocks
in each file.
.Pp
The following operand is available:
.Bl -tag -width file
.It Ar file
The pathname of the
.Ar file
to checksum.
If no file operands are specified, the
standard input is used.
.El
.Sh SEE ALSO
.Xr wc 1
.Sh DIAGNOSTICS
The
.Nm sum
utility exits zero on success,
and >0 if an error occurs.
.Pp
End-of-file may return a read-error.
.Sh HISTORY
A
.Nm
command appeared in
.At v7 .
