.so tmac.ilib
.TH LAM 1 "The University of Arizona \- 6/28/83"
.SH NAME
lam \- laminate files
.SH SYNOPSIS
\f3lam\fR  file [ file | \- string ] ...
.SH DESCRIPTION
.I Lam
laminates the named files onto the standard output.
The resulting output is the line-by-line concatenation
of corresponding lines from each file named.
If the files are different lengths,
empty lines are substituted for missing lines in the shorter files.
.PP
Each
.I string
argument is placed in the output line
at the point that it appears in the argument list.
For example, lines from \fIfile1\fR and \fIfile2\fR can be laminated
with a colon between each line from \fIfile1\fR and the corresponding
line from \fIfile2\fR by the command
.DS
lam file1 \-: file2
.DE
.PP
Filenames and strings may appear in any order in the argument list.
If
`\-',
is given for a filename
the standard input is read at that point.
If a file is named more than once,
each of its lines will be duplicated on the output line,
except that if standard input is named more than once,
its lines will be read alternately.
For example, each pair of lines from standard input can be
joined onto one line with a space between them by the command
.DS
lam \- "\-\0" \-
.DE
.LP
while the command
.DS
lam file1 "\-\0" file1
.DE
.LP
replicates each line from \fIfile1\fR.
.SH SEE ALSO
delam(1), delamc(1)
.LP
.St
.SH AUTHOR
Thomas R. Hicks
