.so tmac.ilib
.TH PARENS 1 "The University of Arizona \- 8/15/84"
.SH NAME
parens \- produce strings of balanced parentheses
.SH SYNOPSIS
\f3parens\fP [\-\f3b \fIn\fR] [\-\f3n \fIn\fR] [\-\f3l \fIs\fR] [\-\f3r \fIs\fR] [\-\f3v\fR]
.SH DESCRIPTION
\fIParens\fR produces parenthesis-balanced strings in which the
parentheses are randomly distributed.
.PP
The following options may appear in any order:
.IP \-\f3b\0\fIn\fR .75i
Bound the length of the strings to \fIn\fR left and right parentheses each. The default is 10.
.IP \-\f3n\0\fIn\fR
Produce \fIn\fR strings. The default is 10.
.IP \-\f3l\0\fIs\fR
Use \fIs\fR for the left parenthesis. The default is \*M(\fR .
.IP \-\f3r\0\fIs\fR
Use \fIs\fR for the right parenthesis. The default is \*M)\fR .
.IP \-\f3v\fR
Randomly vary the length of the strings between 0 and the bound.
In the absence of this option, all strings are the exactly as long
as the specified bound.
.SH SEE ALSO
Arnold, D. B. and M. R. Sleep. ``Uniform Random Generation of
Balanced Parenthesis Strings'', \fIACM Transactions on Programming
Languages and Systems\fR, Vol. 2. No. 1 (1980), pp. 122-128.
.SH AUTHOR
Ralph E. Griswold
