void main DCLPROTO((int argc, char **argv, char **envp));
void loop DCLPROTO((void));
void setflags DCLPROTO((void));
void parseargs DCLPROTO((char **argv));
void setmoreflags DCLPROTO((void));
void setupvals DCLPROTO((void));
void compctlsetup DCLPROTO((void));
void initialize DCLPROTO((void));
void addreswords DCLPROTO((void));
void runscripts DCLPROTO((void));
void ainit DCLPROTO((void));
