.\" Copyright (c) 1980 Regents of the University of California.
.\" All rights reserved.  The Berkeley software License Agreement
.\" specifies the terms and conditions for redistribution.
.\"
.\"	@(#)tra.1	4.1 (Berkeley) 4/29/85
.\"
.TH TRA 1 "4/1/81"
.UC
.pl 1
The ``tra'' command is obsolete.  Use the ``f'' (file) keyletter to
the ``tail'' command instead.  Thus ``tra errs'' is similar to
``tail -f errs'', and you can now say, e.g. ``tail -10f errs'' to
start the watch with the current last 10 lines.
