/*
 * Copyright (c) 1980 Regents of the University of California.
 * All rights reserved.  The Berkeley software License Agreement
 * specifies the terms and conditions for redistribution.
 *
 *	@(#)tokdefs.h	5.1 (Berkeley) %G%
 */

#define SEOS 1
#define SCOMMENT 2
#define SLABEL 3
#define SUNKNOWN 4
#define SHOLLERITH 5
#define SSTRING 6
#define SICON 7
#define SRCON 8
#define SDCON 9
#define SBITCON 10
#define SOCTCON 11
#define SHEXCON 12
#define STRUE 13
#define SFALSE 14
#define SNAME 15
#define SNAMEEQ 16
#define SFIELD 17
#define SSCALE 18
#define SINCLUDE 19
#define SLET 20
#define SASSIGN 21
#define SAUTOMATIC 22
#define SBACKSPACE 23
#define SBLOCK 24
#define SCALL 25
#define SCHARACTER 26
#define SCLOSE 27
#define SCOMMON 28
#define SCOMPLEX 29
#define SCONTINUE 30
#define SDATA 31
#define SDCOMPLEX 32
#define SDIMENSION 33
#define SDO 34
#define SDOUBLE 35
#define SELSE 36
#define SELSEIF 37
#define SEND 38
#define SENDFILE 39
#define SENDIF 40
#define SENTRY 41
#define SEQUIV 42
#define SEXTERNAL 43
#define SFORMAT 44
#define SFUNCTION 45
#define SGOTO 46
#define SASGOTO 47
#define SCOMPGOTO 48
#define SARITHIF 49
#define SLOGIF 50
#define SIMPLICIT 51
#define SINQUIRE 52
#define SINTEGER 53
#define SINTRINSIC 54
#define SLOGICAL 55
#define SNAMELIST 56
#define SOPEN 57
#define SPARAM 58
#define SPAUSE 59
#define SPRINT 60
#define SPROGRAM 61
#define SPUNCH 62
#define SREAD 63
#define SREAL 64
#define SRETURN 65
#define SREWIND 66
#define SSAVE 67
#define SSTATIC 68
#define SSTOP 69
#define SSUBROUTINE 70
#define STHEN 71
#define STO 72
#define SUNDEFINED 73
#define SWRITE 74
#define SLPAR 75
#define SRPAR 76
#define SEQUALS 77
#define SCOLON 78
#define SCOMMA 79
#define SCURRENCY 80
#define SPLUS 81
#define SMINUS 82
#define SSTAR 83
#define SSLASH 84
#define SPOWER 85
#define SCONCAT 86
#define SAND 87
#define SOR 88
#define SNEQV 89
#define SEQV 90
#define SNOT 91
#define SEQ 92
#define SLT 93
#define SGT 94
#define SLE 95
#define SGE 96
#define SNE 97
