.TH ALIASES 5 12/31/79
.SH NAME
aliases \- aliases file for delivermail
.SH SYNOPSIS
/usr/lib/aliases
.SH DESCRIPTION
This file describes user id aliases
that will be used
by
.I /etc/delivermail.
It is formatted as a series of lines
of the form
.in +0.5i
name:addr1,addr2,...addrn
.in
The
.I name
is the name to alias,
and the
.I addri
are the addresses to send the message to.
Lines beginning with white space
are continuation lines.
Lines beginning with `\|#\|'
are comments.
.PP
Aliasing occurs only on local names.
Loops can not occur,
since no message will be sent to any person
more than once.
.SH SEE\ ALSO
delivermail(8)
.SH BUGS
