.\" Copyright (c) 1988 The Regents of the University of California.
.\" All rights reserved.
.\"
.\" Redistribution and use in source and binary forms are permitted
.\" provided that the above copyright notice and this paragraph are
.\" duplicated in all such forms and that any documentation,
.\" advertising materials, and other materials related to such
.\" distribution and use acknowledge that the software was developed
.\" by the University of California, Berkeley.  The name of the
.\" University may not be used to endorse or promote products derived
.\" from this software without specific prior written permission.
.\" THIS SOFTWARE IS PROVIDED ``AS IS'' AND WITHOUT ANY EXPRESS OR
.\" IMPLIED WARRANTIES, INCLUDING, WITHOUT LIMITATION, THE IMPLIED
.\" WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE.
.\"
.\"	@(#)passwd.1	6.5 (Berkeley) %G%
.\"
.TH PASSWD 1 ""
.UC 4
.SH NAME
passwd \- change password file information
.SH SYNOPSIS
.B passwd
[ user ]
.SH DESCRIPTION
.I Passwd
changes the user's password.  First, the user is prompted for their old
password, and then, if that is correct, for the new password.  The new
password must be entered twice to forestall any typing errors.  The
super-user is not prompted for the old password.
.PP
Once the password has been verified,
.I passwd
uses
.IR mkpasswd (8)
to update the user database.  This is run in the background, and,
at very large sites could take several minutes.  Until this update
is completed, the password file is unavailable for other updates
and the new password will not be available to programs.
.SH FILES
.DT
/etc/master.passwd		the user database
.RE
.SH "SEE ALSO"
chpass(1), login(1), passwd(5), mkpasswd(8), vipw(8)
.br
Robert Morris and Ken Thompson,
.I UNIX password security
