.\" Copyright (c) 1983 Regents of the University of California.
.\" All rights reserved.  The Berkeley software License Agreement
.\" specifies the terms and conditions for redistribution.
.\"
.\"	@(#)imp.4p	6.2 (Berkeley) 5/16/86
.\"
.TH IMP 4P "May 16, 1986"
.UC 5
.SH NAME
imp \- IMP raw socket interface
.SH SYNOPSIS
.B #include <sys/socket.h>
.br
.B #include <netinet/in.h>
.br
.B #include <netimp/if_imp.h>
.PP
.B s = socket(AF_IMPLINK, SOCK_RAW, proto);
.SH DESCRIPTION
The raw imp socket provides direct access to the
.IR imp (4)
network interface.  Users send packets through
the interface using the 
.IR send (2)
calls, and receive packets with the
.IR recv (2),
calls.  All outgoing packets must have an 1822 96-bit
leader on the front.  Likewise, packets received
by the user will have this leader on the front.  The
1822 leader and the legal values for the various fields
are defined in the include file
.RI < netimp/if_imp.h >.
The raw imp interface automatically installs the length
and destination address in the 1822 leader of all
outgoing packets; these need not be filled in by the user.
.PP
If the protocol selected,
.IR proto ,
is zero,
the socket will receive
all IMP messages except RFNM and incompletes
which are not input data for a kernel protocol.
If
.I proto
is non-zero,
only messages for the specified link type will be received.
.SH DIAGNOSTICS
An operation on a socket may fail with one of the following
errors:
.TP 15
[EISCONN]
when trying to establish a connection on a socket which
already has one, or when trying to send a datagram with the destination
address specified and the socket is already connected;
.TP 15
[ENOTCONN]
when trying to send a datagram, but
no destination address is specified, and the socket hasn't been
connected;
.TP 15
[ENOBUFS]
when the system runs out of memory for
an internal data structure;
.TP 15
[ENOBUFS]
eight messages to the destination host are outstanding,
and another eight are already queued for output;
.TP 15
[EADDRNOTAVAIL]
when an attempt is made to create a 
socket with a network address for which no network interface
exists.
.SH SEE ALSO
intro(4N), inet(4F), imp(4)
