#	@(#)Makefile	5.1 (Berkeley) 5/31/90

PROG=	talkd
CFLAGS+=-I${.CURDIR}/../common_source
NOMAN=	noman
SRCS=	announce.c print.c process.c table.c talkd.c

.include "../../Makefile.inc"
.include <bsd.prog.mk>
