.\"	@(#)getpw.3c	6.2 (Berkeley) 5/27/86
.\"
.TH GETPW 3C  "May 27, 1986"
.AT 3
.SH NAME
getpw \- get name from uid
.SH SYNOPSIS
.nf
.B getpw(uid, buf)
.B char *buf;
.fi
.SH DESCRIPTION
.ft B
Getpw is made obsolete by getpwuid(3).
.ft R
.PP
.I Getpw
searches the password file for
the (numerical)
.IR uid ", and fills in " "buf"
with the corresponding line;
it returns non-zero if
.IR uid ""
could not
be found.
The line is null-terminated.
.SH FILES
/etc/passwd
.SH "SEE ALSO"
getpwent(3),
passwd(5)
.SH DIAGNOSTICS
Non-zero
return on error.
