.\" Copyright (c) 1980 Regents of the University of California.
.\" All rights reserved.  The Berkeley software License Agreement
.\" specifies the terms and conditions for redistribution.
.\"
.\"	@(#)pause.3c	6.1 (Berkeley) 5/9/85
.\"
.TH PAUSE 3C "May 9, 1985"
.UC 4
.SH NAME
pause \- stop until signal
.SH SYNOPSIS
.B pause()
.SH DESCRIPTION
.I Pause
never returns normally.
It is used to give up control while waiting for
a signal from
.IR kill (2)
or an interval timer, see
.IR setitimer (2).
Upon termination of a signal handler started during a
.I pause,
the
.I pause
call will return.
.SH "RETURN VALUE
Always returns \-1.
.SH ERRORS
.I Pause
always returns:
.TP 15
[EINTR]
The call was interrupted.
.SH "SEE ALSO
kill(2), select(2), sigpause(2)
