#	@(#)Makefile	4.5 (Berkeley) %G%

LIB=	ln
SRCS=	allprint.c main.c reject.c yyless.c yywrap.c
LINKS=	${DESTDIR}/usr/lib/libln.a ${DESTDIR}/usr/lib/libl.a \
	${DESTDIR}/usr/lib/libln_p.a ${DESTDIR}/usr/lib/libl_p.a

.include <bsd.lib.mk>
