.TH LASTCOMM 1 10/27/79
.UC
.SH NAME
lastcomm \- show last commands executed in reverse order
.SH SYNOPSIS
.B lastcomm
[ command name ] ... [user name] ...
.SH DESCRIPTION
.PP
.I Lastcomm
gives information on previously executed commands.
.I Lastcomm
with no arguments prints information about all the commands recorded
during the current accounting file's lifetime.
If called with arguments, only those accounting entries whose command
name or user name matches one of the arguments are printed.
So, for example,
.br
	lastcomm a.out
.br
would produce a listing of all the
executions of commands named a.out, and
.br
	lastcomm root
.br
would produce a listing of all the commands executed by user root.
.LP

.PP
For each process entry, the following are printed.
.br
	The name of the user who ran the process.
.br
	The command name under which the process was called.
.br
	The amount of cpu time used by the process (in seconds).
.br
	The time the process exited.
.br
.LP

.SH "AUTHOR"
Len Edmondson

.SH "SEE ALSO"
last (1)
.br
