.\"
.\" Copyright (c) 1992 The Regents of the University of California
.\" Copyright (c) 1990, 1992 Jan-Simon Pendry
.\" All rights reserved.
.\"
.\" This code is derived from software donated to Berkeley by
.\" Jan-Simon Pendry.
.\"
.\" %sccs.include.redist.roff%
.\"
.\"	@(#)mount_kernfs.8	8.1 (Berkeley) %G%
.\"
.\"
.Dd 
.Dt MOUNT_KERNFS 8
.Os BSD 4.4
.Sh NAME
.Nm mount_kernfs
.Nd mount the /kern file system
.Sh SYNOPSIS
.Nm mount_kernfs
.Op Fl F Ar fsoptions
.Pa /kern
.Pa mount_point
.Sh DESCRIPTION
The
.Nm mount_kern
command attaches an instance of the kernel parameter
namespace to the global filesystem namespace.
The conventional mount point is
.Pa /kern .
This command is normally executed by
.Xr mount 8
at boot time.
.Pp
The filesystem includes several regular files which can be read,
some of which can also be written.
The contents of the files is in a machine-independent format,
either a string, or an integer in decimal ASCII.
Where numbers are returned, a trailing newline character is also added.
.Sh FILES
.Bl -tag -width copyright -compact
.It Pa boottime
the time at which the system was last booted (decimal ASCII).
.It Pa copyright
kernel copyright message.
.It Pa hostname
the hostname, with a trailing newline.
The hostname can be changed by writing to this file.
A trailing newline will be stripped from the hostname being written.
.It Pa hz
the frequency of the system clock (decimal ASCII).
.It Pa loadavg
the 1, 5 and 15 minute load average in kernel fixed-point format.
The final integer is the fix-point scaling factor.
All numbers are in decimal ASCII.
.It Pa pagesize
the machine pagesize (decimal ASCII).
.It Pa physmem
the number of pages of physical memory in the machine (decimal ASCII).
.It Pa root
the system root directory.
In a chroot'ed environment,
.Nm
can be used to create a new
.Pa /kern
mount point.
.Pa /kern/root
will then refer to the system global root, not the current process root.
.It Pa rootdev
the root device.
.It Pa rrootdev
the raw root device.
.It Pa time
the second and microsecond value of the system clock.
Both numbers are in decimal ASCII.
.It Pa version
the kernel version string.
The head line for
.Pa /etc/motd
can be generated by running:
.Dq Ic "sed 1q /kern/version"
.El
.Sh SEE ALSO
.Xr mount 2 ,
.Xr unmount 2 ,
.Xr fstab 5
.Sh CAVEATS
This filesystem may not be NFS-exported.
.Sh HISTORY
The
.Nm
filesystem
is
.Ud
