MAKEFILE      = Makefile

SRCS	      = libhash.a \
		libpdb.a \
		libslist.a \
		libspms.a \
		libtree.a \
		llib-lhash.ln \
		llib-lpdb.ln \
		llib-lslist.ln \
		llib-lspms.ln \
		llib-ltree.ln

SUFFIX	      = .a:s .ln:s

all:;

clean:;		@rm -f $(SRCS)

co:;

depend:;

index:;

install:;

lint:;

print:;

program:;

tags:;

update:;
###
