.\" Copyright (c) 1986 Regents of the University of California.
.\" All rights reserved.  The Berkeley software License Agreement
.\" specifies the terms and conditions for redistribution.
.\"
.\"	@(#)L-devices.5	6.1 (Berkeley) 4/24/86
.\"
.TH L-DEVICES 5 "April 24, 1986"
.UC 6
.SH NAME
L-devices \- UUCP device description file 
.SH DESCRIPTION
The L-devices file is consulted by the UUCP daemon
.IR uucico (8C)
under the direction of
.IR L.sys (5)
for information on the devices that it may use.
Each line describes exactly one device.
.PP
A line in
.I L-devices
has the form:
.PP
Caller  Device  Call_Unit  Class  Dialer  [Expect  Send]....
.PP
Each item can be separated by any number of blanks or tabs. Lines beginning
with a `#' character are comments; long lines can be continued by appending
a `\e' character to the end of the line.
.PP
.I Caller
denotes the type of connection, and must be one of the following:
.TP 8
.B ACU
Automatic call unit, e.g., autodialing modems such as the Hayes
Smartmodem 1200 or Novation ``Smart Cat''.
.TP 8
.B DIR
Direct connect; hardwired line (usually RS-232) to a remote system.
.TP 8
.B DK
AT&T Datakit.
.TP 8
.B MICOM
Micom Terminal switch.
.TP 8
.B PAD
X.25 PAD connection.
.TP 8
.B PCP
GTE Telenet PC Pursuit.
.TP 8
.B SYTEK
Sytek high-speed dedicated modem port connection.
.TP 8
.B TCP
Berkeley TCP/IP or 3Com UNET connection. These are mutually exclusive.
Note that listing TCP connections in
.I L-devices
is superfluous;
.I uucico
does not even bother to look here since it has all the information it
needs in
.IR L.sys (5).
.PP
.I Device
is a device file in /dev/ that is opened to use the device. The device
file must be owned by UUCP, with access modes of 0600 or better. (See
.IR chmod (2)).
.PP
.I Call_Unit
is an optional second device file name.
True automatic call units use a separate device file for data and for dialing;
the
.I Device
field specifies the data port, while the
.I Call_unit
field specifies the dialing port.
If the
.I Call_unit
field is unused, it must not be left empty.
Insert a dummy entry as a placeholder, such as ``0'' or ``unused.''
.PP
.I Class
is an integer number that
specifies the line baud (for dialers and direct lines) or the port number (for
network connections).
.PP
The
.I Class
may be preceded by a non-numeric prefix.
This is to differentiate among devices that have identical
.I Caller
and baud, but are distinctly different.
For example, ``1200'' could refer to all Bell 212-compatible modems,
``V1200'' to Racal-Vadic modems, and ``C1200'' to CCITT modems,
all at 1200 baud.
Similarly, ``W1200'' could denote long distance lines, while ``L1200''
could refer to local phone lines.
.PP
.I Dialer
applies only to ACU devices. This is the "brand" or type of the ACU or modem.
.TP 8
.B DF02
DEC DF02 or DF03 modems.
.TP 8
.B DF112
Dec DF112 modems. Use a
.I Dialer
field of
.B DF112T
to use tone dialing, or
.B DF112P
for pulse dialing.
.TP 8
.B att
AT&T 2224 2400 baud modem.
.TP 8
.B cds224
Concord Data Systems 224 2400 baud modem.
.TP 8
.B dn11
DEC DN11 Unibus dialer.
.TP 8
.B hayes
Hayes Smartmodem 1200 and compatible autodialing modems.
Use a
.I Dialer
field of
.B hayestone
to use tone dialing, or
.B hayespulse
for pulse dialing.
It is also permissible to include the letters `T' and `P' in the phone
number (in
.IR L.sys )
to change to tone or pulse midway through dialing.
(Note that a leading `T' or `P' will be interpreted as a dialcode!)
.TP 8
.B hayes2400
Hayes Smartmodem 2400 and compatible modems.
Use a
.I Dialer
field of
.B hayes2400tone
to use tone dialing, or
.B hayes2400pulse
for pulse dialing.
.TP 8
.B novation
Novation ``Smart Cat'' autodialing modem.
.TP 8
.B penril
Penril Corp ``Hayes compatible'' modems (they really aren't or
they would use the
.B hayes
entry.)
.TP 8
.B rvmacs
Racal-Vadic 820 dialer with 831 adapter in a MACS configuration.
.TP 8
.B va212
Racal-Vadic 212 autodialing modem.
.TP 8
.B va811s
Racal-Vadic 811s dialer with 831 adapter.
.TP 8
.B va820
Racal-Vadic 820 dialer with 831 adapter.
.TP 8
.B vadic
Racal-Vadic 3450 and 3451 series autodialing modems.
.TP 8
.B ventel
Ventel 212+ autodialing modem.
.TP 8
.B vmacs
Racal-Vadic 811 dialer with 831 adapter in a MACS configuration.
.PP
.I Expect/Send
is an optional
.I Expect/Send
script for getting through a smart port selector,
or for issuing special commands to the modem.
The syntax is identical to that of the Expect/Send script of
.IR L.sys .
The difference is that the
.I L-devices
script is used
.I before
the connection is made, while the
.I L.sys
script is used
.IR after .
.SH FILES
/usr/lib/uucp/L-devices
.br
/usr/lib/uucp/UUAIDS/L-devices	L-devices example
.SH SEE ALSO
uucp(1C), uux(1C), L.sys(5), uucico(8C)
