.TH GETDTABLESIZE 2 "12 February 1983"
.UC 4
.SH NAME
getdtablesize \- get descriptor table size
.SH SYNOPSIS
.nf
.ft B
nds = getdtablesize()
int nds;
.fi
.SH DESCRIPTION
Each process has a fixed size descriptor table
which is guaranteed to have at least 20 slots.  The entries in
the descriptor table are numbered with small integers starting at 0.
The call
.I getdtablesize
returns the size of this table.
.SH "SEE ALSO"
close(2), dup(2), open(2)
