.TH UMASK 2
.SH NAME
umask \- set file creation mode mask
.SH SYNOPSIS
.ft B
oumask = umask(numask)
.br
int oumask, numask;
.ft R
.SH DESCRIPTION
.I Umask
sets the process's file mode creation mask to \fIcmask\fP
and returns the previous value of the mask.  The low-order
9 bits of \fIcmask\fP are used whenever a file is created,
clearing corresponding bits in the file mode
(see
.IR chmod (2)).
This clearing allows each user to restrict the default access
to his files.
.PP
The value is initially 022 (write access for owner only).
The mask is inherited by child processes.
.SH "RETURN VALUE
The previous value of the file mode mask is returned by the call.
.SH SEE ALSO
chmod(2), mknod(2), open(2)
