.so tmac.ilib
.TH BOLD 2 "The University of Arizona \- 6/28/83"
.SH NAME
bold \- boldface and underscored text
.SH DESCRIPTION
These procedures produce text with interspersed characters suitable for
printing to produce the effect of boldface (by overstriking) and
underscoring (using backspaces).
.SH SYNOPSIS
.nf
.ta 1.5i
\*Mbold(s)\fR	bold version of \*Ms
\*Muscore(s)\fR	underscored version of \*Ms
.SH AUTHOR
Ralph E. Griswold
