.so tmac.ilib
.TH SEGMENT 2 "The University of Arizona \- 9/11/84"
.SH NAME
segment \- segment string
.SH DESCRIPTION
The procedure \*Msegment(s,\*bc)\fR generates
consecutive substrings of \*Ms\fR consisting of characters that
respectively do/do not occur in \*Mc\fR.
For example,
.DS
segment("This is a sentence.",\*b&lcase ++ &ucase)
.DE
generates
.DS
"This"
" "
"is"
" "
"a"
" "
"sentence"
"."
.DE
.SH AUTHOR
William H. Mitchell
