.\" Copyright (c) 1980, 1990 The Regents of the University of California.
.\" All rights reserved.
.\"
.\" %sccs.include.redist.roff%
.\"
.\"	@(#)login.1	6.11 (Berkeley) %G%
.\"
.Dd 
.Dt LOGIN 1
.Os BSD 4
.Sh NAME
.Nm login
.Nd log on to a system
.Sh SYNOPSIS
.Nm login
.Op Fl p
.Op Ar user
.Nm login
.Op Fl p
.Op Fl h Ar hostname
.Op Fl f
.Op Ar user
.Sh DESCRIPTION
The
.Nm login
command
logs the given user
.Ar user
onto a
.Tn UNIX
system.
It has three different uses;
logging a user on to a system,
re-logging a user in as another
user (without logging out),
and logging non-human users (programs)
onto other systems.
In the first two instances, the
.Nm login
program protects the user's password
from prying eyes by disabling the
echoing of typed characters from terminals.
.Pp
Options available:
.Bl -tag -width xxxxhostname
.It Fl f
The
.Fl f
option is used with
a username on the command line, at initial login,
to indicate that proper authentication has already been done
and that no password need be requested.
This option may be used by the superuser
or by the user specified on the command line.
.It Fl h Ar hostname
The
.Fl h
option is used by
.Xr telnetd  8
(at initial login)
and other servers to list the host from which
the connection was received.
.It Fl p
Causes the remainder of the environment to be preserved,
otherwise any previous environment is discarded.
.El
.Pp
In the first usage of
.Nm login
it is invoked by the
.Xr getty 8
program which is responsible for initializing communications between
a users terminal and
.Tn UNIX .
.Nm Login
starts up
by prompting for a user name; when it recives a valid user name and password
the user is logged in and may proceed to work on the system.
.Pp
The second usage of
.Nm login
allows a user to log in as another user
without having logout.
In this case
.Nm login
is invoked from
.Xr sh 1
or
.Xr csh 1
as shown above in the first synopsis.
.Pp
The third usage is by system programs and servers like
.Xr telnetd
and may only be initiated by the super-user.
.Pp
Immediately after logging a user in,
.Nm login
writes the date and time the user last logged in,
the message of the day and notifies the user
if he/she has new mail.
If the file
.Dq Pa .hushlogin
exists in the user's home directory,
both the message of the day and mail notification are
suppressed; this
is usually used to simplify the logins for non-human users, such as
.Xr uucp 1 .
.Nm login
then records an entry in the
.Xr wtmp 5
and
.Xr utmp 5
files and provides the user
with the command shell found in the user's
.Xr passwd 5
entry.
.Pp
Login also modifies the
environment (see
.Xr environ 7 )
with information specifying home directory, command interpreter, terminal
type (if available) and user name.
.Pp
If the file
.Pa /etc/nologin
exists,
.Nm login
prints its contents on the user's terminal and exits. This is
used by
.Xr shutdown  8
to prevent users from logging in when the system is about to go down.
.Pp
The standard shells,
.Xr csh 1
and
.Xr sh 1
notice when login is invoked on a command line and execute
it immediately with out calling
.Xr fork 2 .
.Sh FILES
.Bl -tag -width /var/log/wtmp -compact
.It Pa /var/run/utmp
current logins
.It Pa /var/log/wtmp
login account records
.It Pa /var/mail/*
undelivered mail
.It Pa /etc/motd
message-of-the-day
.It Pa /etc/passwd.*
password files
.It Pa /etc/nologin
disallows logins
.It Pa \&.hushlogin
makes login quieter
.El
.Sh SEE ALSO
.Xr mail 1 ,
.Xr passwd 1 ,
.Xr rlogin 1 ,
.Xr getpass 3 ,
.Xr passwd 5 ,
.Xr utmp 5 ,
.Xr environ 7 ,
.Xr init 8 ,
.Xr getty 8 ,
.Xr shutdown 8 ,
.Sh HISTORY
A
.Nm login
appeared in
.At v6 .
.Sh DIAGNOSTICS
Self explanatory.
