.\" Copyright (c) 1980 Regents of the University of California.
.\" All rights reserved.  The Berkeley software License Agreement
.\" specifies the terms and conditions for redistribution.
.\"
.\"	@(#)dn.4	6.1 (Berkeley) 5/15/85
.\"
.TH DN 4 "May 15, 1985"
.UC 4
.SH NAME
dn \- DN-11 autocall unit interface
.SH SYNOPSIS
.B "device dn0 at uba? csr 0160020 vector dnintr"
.SH DESCRIPTION
The
.I dn
device provides an interface through a DEC DN-11 (or equivalent
such as the Able Quadracall) to an auto-call unit (ACU).
To place an outgoing call one forks a sub-process which
opens the appropriate call unit file,
.I /dev/cua?
and writes the phone number on it.  The parent process
then opens the corresponding modem line
.IR /dev/cul? .
When the connection has been
established, the open on the modem line,
.I /dev/cul?
will return and the process will be connected.
A timer is normally used to timeout the opening of 
the modem line.
.PP
The codes for the phone numbers are:
.PP
.nf
.ta \w'0-9    'u
0-9	dial 0-9
*	dial * (`:' is a synonym)
#	dial # (`;' is a synonym)
\-	delay 20 milliseconds
<	end-of-number (`e' is a synonym)
=	delay for a second dial tone (`w' is a synonym)
f	force a hangup of any existing connection
.fi
.PP
The entire telephone number must be presented in a single
.I write
system call.
.PP
By convention, even numbered call units are for 300 baud
modem lines, while odd numbered units are for 1200 baud lines.
For example,
.I /dev/cua0
is associated with a 300 baud modem line,
.IR /dev/cul0 ,
while
.I /dev/cua1
is associated with a 1200 baud modem line,
.IR /dev/cul1 .
For devices such as the Quadracall which simulate multiple DN-11
units, the minor device indicates which outgoing modem to use.
.SH FILES
.DT
/dev/cua?	call units
.br
/dev/cul?	associated modem lines
.SH "SEE ALSO"
tip(1C)
.SH DIAGNOSTICS
Two error numbers are of interest at open time.
.TP 10
[EBUSY]
The dialer is in use.
.TP 
[ENXIO]
The device doesn't exist, or there's no power to it.
