.UC
.TH VALLOC 3
.SH NAME
valloc \- aligned memory allocator
.SH SYNOPSIS
.nf
.B char *valloc(size)
.B unsigned size;
.fi
.SH DESCRIPTION
.I Valloc
allocates
.I size
bytes aligned on a boundary adequate for
.IR vread (2)).
It is implemented by calling
.IR malloc (3)
with a slightly larger request, saving the true beginning of the block
allocated, and returning a properly aligned pointer.
.SH DIAGNOSTICS
.I Valloc
returns a null pointer (0) if there is no available memory
or if the arena has been detectably corrupted by storing outside the bounds
of a block.
.SH BUGS
.I Vfree
isn't implemented.
