.TH XREFRESH 1 "October 25" "X Version 10"
.SH NAME
xrefresh - refresh all windows on the screen.
.SH SYNOPSIS
.B "xrefresh"
[ \fIhost\fP:\fIdisplay\fP ]
.SH DESCRIPTION
.PP
.I Xrefresh
is a trivial X program to cause your screen to be completely repainted.
.I Xrefresh
just throws a window over the whole screen and unmaps it, causing refresh
events to be sent to all applications.
.SH ARGUMENT SUMMARY
.B "\fIhost\fP:\fIdisplay\fP"
This  argument  allow  you  to  specify the host and display number on
which to display the window dump.  For example ``xrefresh orpheus:1''
would specify that the dump will appear on display `1' on the machine
`orpheus'.  By default,
.I xrefresh
uses the host and display number stored in the environment variable
DISPLAY, and therefore this argument is not normally specified.
.SH ENVIRONMENT
.PP
.TP 8
DISPLAY - To get default host and display number.
.SH SEE ALSO
X(1), uwm(1), X(8)
.SH AUTHOR
.PP
Copyright 1985, Massachusetts Institute of Technology.
.PP
Jim Gettys, Digital Equipment Corp., MIT Project Athena


