.\"	@(#)quiz.6	6.1 (Berkeley) %G%
.\"
.TH QUIZ 6  ""
.AT 3
.SH NAME
quiz \- test your knowledge
.SH SYNOPSIS
.B /usr/games/quiz
[
.B \-i
file ]
[
.B \-t
] [ category1 category2 ]
.SH DESCRIPTION
.I Quiz
gives associative knowledge tests on various subjects.
It asks items chosen from
.I category1
and expects answers from
.IR category2 .
If no categories are specified,
.I quiz
gives instructions and lists the available categories.
.PP
.I Quiz
tells a correct answer whenever you type a bare newline.
At the end of input, upon interrupt, or when questions run out,
.I quiz
reports a score and terminates.
.PP
The
.B \-t
flag specifies `tutorial' mode, where missed questions are repeated
later, and material is gradually introduced as you learn.
.PP
The
.B \-i
flag causes the named file to be substituted for the default index file.
The lines of these files have the  syntax:
.RS
.nf
.ta \w'alternate 'u
line	= category newline \(bv category `:' line
category	= alternate \(bv category `|' alternate
alternate	= empty \(bv alternate primary
primary	= character \(bv `[' category `]' \(bv option
option	= `{' category `}'
.fi
.RE
.PP
The first category on each line of an index file names an information file.
The remaining categories specify the order and contents of
the data in each line of the information file.
Information files have the same syntax.
Backslash `\\' is used as with
.IR sh (1)
to quote syntactically significant characters or to insert transparent
newlines into a line.
When either a question or its answer is empty,
.I quiz
will refrain from asking it.
.SH FILES
/usr/games/quiz.k/*
.SH BUGS
The construct `a\||\|ab' doesn't work in an information file.
Use `a{b}'.
