.TH TIME 1 
.SH NAME
time \- time a command
.SH SYNOPSIS
.B time
command
.SH DESCRIPTION
The
given command is executed; after it is complete,
.I time
prints the elapsed time during the command, the time
spent in the system, and the time spent in execution
of the command.
Times are reported in seconds.
.PP
On a PDP-11, the execution time can depend on what kind of memory
the program happens to land in;
the user time in MOS is often half what it is in core.
.PP
The times are printed on the diagnostic output stream.
.SH BUGS
Elapsed time is accurate to the second,
while the CPU times are measured
to the 60th second.
Thus the sum of the CPU times can be up to a second larger
than the elapsed time.
