.\" Copyright (c) 1985 Regents of the University of California.
.\" All rights reserved.  The Berkeley software License Agreement
.\" specifies the terms and conditions for redistribution.
.\"
.\"	@(#)atq.1	6.2 (Berkeley) 5/10/86
.\"
.TH ATQ 1 "May 10, 1986"
.UC 6
.SH NAME
atq \- print the queue of jobs waiting to be run
.SH SYNOPSIS
.B atq
[ -c ] [ -n ] [ name ... ]
.SH DESCRIPTION
.I Atq 
prints the queue of jobs that are waiting to be run
at a later date. These jobs were created with the
.IR at (1)
command.
With no flags, the queue is sorted in the order that
the jobs will be executed.
.PP
If the 
.B \-c 
flag is used, the queue is sorted by the time that the 
.I at 
command was given. 
.PP
The 
.B \-n 
flag prints only the total number of files that are currently
in the queue. 
.PP
If a name(s) is provided, only those files belonging to that user(s) are 
displayed.
.SH FILES
/usr/spool/at		spool area
.SH "SEE ALSO"
at(1),
atrm(1),
cron(8)
