.TH CHSH 1 "21 October 1980"
.UC 4
.SH NAME
chsh \- change default login shell
.SH SYNOPSIS
.B chsh
name
[
shell
]
.SH DESCRIPTION
.I Chsh
is a command similar to
.IR  passwd (1)
except that it is used to change the login shell field of the password
file rather than the password entry.
If no
.I shell
is specified
then the shell reverts to the default login shell
.I /bin/sh.
Otherwise only
.IR /bin/csh,
.IR /bin/oldcsh,
or
.I /usr/new/csh
can be specified as the shell unless you are the super-user.
.PP
An example use of this command would be
.PP
.DT
	chsh bill /bin/csh
.SH "SEE ALSO"
csh(1), passwd(1), passwd(5)
