.TH GROUPS 1 "17 March 1982"
.UC 4
.SH NAME
groups \- show group memberships
.SH SYNOPSIS
.B groups
.SH DESCRIPTION
The
.I groups
command shows the groups to which you belong.
Each user belongs to a group specified in the password file
.I /etc/passwd
and possibly to other groups as specified in the file
.I /etc/group.
If you do not own a file but belong to the group which it is owned
by then you are granted group access to the file.
.PP
When a new file is created it is given
the group of the containing directory.
.SH "SEE ALSO"
setgrp(2)
.SH FILES
/etc/passwd, /etc/group
.SH BUGS
More groups should be allowed.
