.TH RMAIL 1 "2 April 1983"
.UC 4
.SH NAME
rmail \- handle remote mail received via uucp
.SH SYNOPSIS
.B rmail
user ...
.SH DESCRIPTION
.I Rmail
interprets incoming mail received via
.IR uucp (1C),
collapsing ``From'' lines in the form generated
by 
.IR binmail (1)
into a single line of the form ``return-path!sender'',
and passing the processed mail on to
.IR sendmail (8).
.PP
.I Rmail
is explicitly designed for use with 
.I uucp
and
.IR sendmail .
.SH "SEE ALSO"
binmail(1),
uucp(1C),
sendmail(8)
.SH BUGS
.I Rmail
should not reside in /bin.
