/*
 * System call switch table.
 *
 * DO NOT EDIT-- this file is automatically generated.
 * created from	@(#)syscalls.master	8.1 (Berkeley) 6/11/93
 */

#include <sys/param.h>
#include <sys/systm.h>

int	nosys();

int	rexit();
int	fork();
int	read();
int	write();
int	open();
int	close();
int	wait4();
int	ocreat();
int	link();
int	unlink();
int	chdir();
int	mknod();
int	chmod();
int	chown();
int	obreak();
int	olseek();
int	getpid();
int	mount();
int	setuid();
int	getuid();
int	ptrace();
int	saccess();
int	sync();
int	kill();
int	ostat();
int	olstat();
int	dup();
int	pipe();
int	profil();
int	getgid();
int	sysacct();
int	ioctl();
int	reboot();
int	symlink();
int	readlink();
int	execve();
int	umask();
int	chroot();
int	ofstat();
int	ogetpagesize();
int	vfork();
int	sbrk();
int	sstk();
int	ovadvise();
int	munmap();
int	mprotect();
int	madvise();
int	mincore();
int	getgroups();
int	setgroups();
int	getpgrp();
int	setpgid();
int	setitimer();
int	owait();
int	swapon();
int	getitimer();
int	ogethostname();
int	osethostname();
int	getdtablesize();
int	dup2();
int	fcntl();
int	select();
int	fsync();
int	setpriority();
int	socket();
int	connect();
int	oaccept();
int	getpriority();
int	osend();
int	orecv();
int	sigreturn();
int	bind();
int	setsockopt();
int	listen();
int	osigvec();
int	osigblock();
int	osigsetmask();
int	sigsuspend();
int	osigstack();
int	orecvmsg();
int	osendmsg();
#ifdef TRACE
int	vtrace();
#else
#endif
int	gettimeofday();
int	getrusage();
int	getsockopt();
int	readv();
int	writev();
int	settimeofday();
int	fchown();
int	fchmod();
int	orecvfrom();
int	osetreuid();
int	osetregid();
int	rename();
int	otruncate();
int	oftruncate();
int	flock();
int	sendto();
int	shutdown();
int	socketpair();
int	mkdir();
int	rmdir();
int	utimes();
int	adjtime();
int	ogetpeername();
int	ogethostid();
int	osethostid();
int	ogetrlimit();
int	osetrlimit();
int	okillpg();
int	quotactl();
int	oquota();
int	ogetsockname();
int	news_setenvp();
int	news_sysnews();
#ifdef NFS
int	nfssvc();
#else
#endif
int	ogetdirentries();
int	statfs();
int	fstatfs();
#ifdef NFS
int	getfh();
#else
#endif
int	sun_getdomainname();
int	sun_setdomainname();
#ifdef SYSVSHM
int	shmsys();
#else
#endif
int	sun_getdents();

#ifdef XXX_UNUSED
#define compat(n, name) n, __CONCAT(o,name)

int	onews_time();
#ifdef TRACE
#else
#endif
#ifdef NFS
#else
#endif
#ifdef NFS
#else
#endif
#ifdef SYSVSHM
#else
#endif

#else /* XXX_UNUSED */
#define compat(n, name) 0, nosys
#endif /* XXX_UNUSED */

struct sysent newssys[] = {
	0, nosys,			/* 0 = nosys indir */
	1, rexit,			/* 1 = exit */
	0, fork,			/* 2 = fork */
	3, read,			/* 3 = read */
	3, write,			/* 4 = write */
	3, open,			/* 5 = open */
	1, close,			/* 6 = close */
	4, wait4,			/* 7 = wait4 */
	2, ocreat,			/* 8 = ocreat */
	2, link,			/* 9 = link */
	1, unlink,			/* 10 = unlink */
	0, nosys,			/* 11 = obsolete execv */
	1, chdir,			/* 12 = chdir */
	compat(1,news_time),		/* 13 = old news_time */
	3, mknod,			/* 14 = mknod */
	2, chmod,			/* 15 = chmod */
	3, chown,			/* 16 = chown */
	1, obreak,			/* 17 = break */
	0, nosys,			/* 18 = obsolete stat */
	3, olseek,			/* 19 = olseek */
	0, getpid,			/* 20 = getpid */
	4, mount,			/* 21 = mount */
	0, nosys,			/* 22 = obsolete umount */
	1, setuid,			/* 23 = setuid */
	0, getuid,			/* 24 = getuid */
	0, nosys,			/* 25 = obsolete stime */
	4, ptrace,			/* 26 = ptrace */
	0, nosys,			/* 27 = obsolete alarm */
	0, nosys,			/* 28 = obsolete fstat */
	0, nosys,			/* 29 = obsolete pause */
	0, nosys,			/* 30 = obsolete utime */
	0, nosys,			/* 31 = nosys */
	0, nosys,			/* 32 = nosys */
	2, saccess,			/* 33 = access */
	0, nosys,			/* 34 = obsolete access */
	0, nosys,			/* 35 = obsolete ftime */
	0, sync,			/* 36 = sync */
	2, kill,			/* 37 = kill */
	2, ostat,			/* 38 = ostat */
	0, nosys,			/* 39 = obsolete setpgrp */
	2, olstat,			/* 40 = olstat */
	2, dup,			/* 41 = dup */
	0, pipe,			/* 42 = pipe */
	0, nosys,			/* 43 = obsolete times */
	4, profil,			/* 44 = profil */
	0, nosys,			/* 45 = nosys */
	0, nosys,			/* 46 = obsolete setgid */
	0, getgid,			/* 47 = getgid */
	0, nosys,			/* 48 = obsolete ssig sig */
	0, nosys,			/* 49 = nosys */
	0, nosys,			/* 50 = nosys */
	1, sysacct,			/* 51 = acct */
	0, nosys,			/* 52 = nosys */
	0, nosys,			/* 53 = nosys */
	3, ioctl,			/* 54 = ioctl */
	1, reboot,			/* 55 = reboot */
	0, nosys,			/* 56 = nosys */
	2, symlink,			/* 57 = symlink */
	3, readlink,			/* 58 = readlink */
	3, execve,			/* 59 = execve */
	1, umask,			/* 60 = umask */
	1, chroot,			/* 61 = chroot */
	2, ofstat,			/* 62 = ofstat */
	0, nosys,			/* 63 = nosys */
	0, ogetpagesize,			/* 64 = ogetpagesize */
	0, nosys,			/* 65 = news_mremap */
	0, vfork,			/* 66 = vfork */
	0, nosys,			/* 67 = obsolete vread */
	0, nosys,			/* 68 = obsolete vwrite */
	1, sbrk,			/* 69 = sbrk */
	1, sstk,			/* 70 = sstk */
	0, nosys,			/* 71 = news_mmap */
	1, ovadvise,			/* 72 = vadvise */
	2, munmap,			/* 73 = munmap */
	3, mprotect,			/* 74 = mprotect */
	3, madvise,			/* 75 = madvise */
	0, nosys,			/* 76 = obsolete vhangup */
	0, nosys,			/* 77 = obsolete vlimit */
	3, mincore,			/* 78 = mincore */
	2, getgroups,			/* 79 = getgroups */
	2, setgroups,			/* 80 = setgroups */
	0, getpgrp,			/* 81 = getpgrp */
	2, setpgid,			/* 82 = setpgid */
	3, setitimer,			/* 83 = setitimer */
	3, owait,			/* 84 = owait */
	1, swapon,			/* 85 = swapon */
	2, getitimer,			/* 86 = getitimer */
	2, ogethostname,			/* 87 = ogethostname */
	2, osethostname,			/* 88 = osethostname */
	0, getdtablesize,			/* 89 = getdtablesize */
	2, dup2,			/* 90 = dup2 */
	0, nosys,			/* 91 = getdopt */
	3, fcntl,			/* 92 = fcntl */
	5, select,			/* 93 = select */
	0, nosys,			/* 94 = setdopt */
	1, fsync,			/* 95 = fsync */
	3, setpriority,			/* 96 = setpriority */
	3, socket,			/* 97 = socket */
	3, connect,			/* 98 = connect */
	3, oaccept,			/* 99 = oaccept */
	2, getpriority,			/* 100 = getpriority */
	4, osend,			/* 101 = osend */
	4, orecv,			/* 102 = orecv */
	1, sigreturn,			/* 103 = sigreturn */
	3, bind,			/* 104 = bind */
	5, setsockopt,			/* 105 = setsockopt */
	2, listen,			/* 106 = listen */
	0, nosys,			/* 107 = obsolete vtimes */
	3, osigvec,			/* 108 = osigvec */
	1, osigblock,			/* 109 = osigblock */
	1, osigsetmask,			/* 110 = osigsetmask */
	1, sigsuspend,			/* 111 = sigsuspend */
	2, osigstack,			/* 112 = osigstack */
	3, orecvmsg,			/* 113 = orecvmsg */
	3, osendmsg,			/* 114 = osendmsg */
#ifdef TRACE
	2, vtrace,			/* 115 = vtrace */
#else
	0, nosys,			/* 115 = obsolete vtrace */
#endif
	2, gettimeofday,			/* 116 = gettimeofday */
	2, getrusage,			/* 117 = getrusage */
	5, getsockopt,			/* 118 = getsockopt */
	0, nosys,			/* 119 = nosys */
	3, readv,			/* 120 = readv */
	3, writev,			/* 121 = writev */
	2, settimeofday,			/* 122 = settimeofday */
	3, fchown,			/* 123 = fchown */
	2, fchmod,			/* 124 = fchmod */
	6, orecvfrom,			/* 125 = orecvfrom */
	2, osetreuid,			/* 126 = osetreuid */
	2, osetregid,			/* 127 = osetregid */
	2, rename,			/* 128 = rename */
	2, otruncate,			/* 129 = otruncate */
	2, oftruncate,			/* 130 = oftruncate */
	2, flock,			/* 131 = flock */
	0, nosys,			/* 132 = nosys */
	6, sendto,			/* 133 = sendto */
	2, shutdown,			/* 134 = shutdown */
	5, socketpair,			/* 135 = socketpair */
	2, mkdir,			/* 136 = mkdir */
	1, rmdir,			/* 137 = rmdir */
	2, utimes,			/* 138 = utimes */
	0, nosys,			/* 139 = obsolete 4.2 sigreturn */
	2, adjtime,			/* 140 = adjtime */
	3, ogetpeername,			/* 141 = ogetpeername */
	0, ogethostid,			/* 142 = ogethostid */
	1, osethostid,			/* 143 = osethostid */
	2, ogetrlimit,			/* 144 = ogetrlimit */
	2, osetrlimit,			/* 145 = osetrlimit */
	2, okillpg,			/* 146 = okillpg */
	0, nosys,			/* 147 = nosys */
	4, quotactl,			/* 148 = quotactl */
	4, oquota,			/* 149 = oquota */
	3, ogetsockname,			/* 150 = ogetsockname */
	1, news_setenvp,			/* 151 = news_setenvp */
	5, news_sysnews,			/* 152 = news_sysnews */
	0, nosys,			/* 153 = nosys */
	0, nosys,			/* 154 = nosys */
#ifdef NFS
	2, nfssvc,			/* 155 = nfssvc */
#else
	0, nosys,			/* 155 = nosys */
#endif
	4, ogetdirentries,			/* 156 = ogetdirentries */
	2, statfs,			/* 157 = statfs */
	2, fstatfs,			/* 158 = fstatfs */
	0, nosys,			/* 159 = news_unmount */
	0, nosys,			/* 160 = news_async_daemon */
#ifdef NFS
	2, getfh,			/* 161 = getfh */
#else
	0, nosys,			/* 161 = nosys */
#endif
	2, sun_getdomainname,			/* 162 = sun_getdomainname */
	2, sun_setdomainname,			/* 163 = sun_setdomainname */
	0, nosys,			/* 164 = nosys */
	0, nosys,			/* 165 = nosys */
	0, nosys,			/* 166 = nosys */
	0, nosys,			/* 167 = nosys */
	0, nosys,			/* 168 = nosys */
	0, nosys,			/* 169 = nosys */
	0, nosys,			/* 170 = nosys */
#ifdef SYSVSHM
	4, shmsys,			/* 171 = shmsys */
#else
	0, nosys,			/* 171 = nosys */
#endif
	0, nosys,			/* 172 = nosys */
	0, nosys,			/* 173 = nosys */
	3, sun_getdents,			/* 174 = sun_getdents */
	0, nosys,			/* 175 = nosys */
	0, nosys,			/* 176 = nosys */
	0, nosys,			/* 177 = nosys */
	0, nosys,			/* 178 = nosys */
	0, nosys,			/* 179 = nosys */
};

int	nnewssys = sizeof(newssys) / sizeof(newssys[0]);
