.\" Copyright (c) 1983 Regents of the University of California.
.\" All rights reserved.  The Berkeley software License Agreement
.\" specifies the terms and conditions for redistribution.
.\"
.\"	@(#)uusnap.8	6.3 (Berkeley) 10/24/88
.\"
.TH UUSNAP 8 "October 24, 1988"
.UC 5
.SH NAME
uusnap \- show snapshot of the UUCP system
.SH SYNOPSIS
.B uusnap
.SH DESCRIPTION
.I Uusnap
displays in tabular format a synopsis of the current UUCP
situation.  The format of each line is as follows:
.PP
.ti +10
site   N Cmds   N Data   N Xqts   Message
.PP
Where "site" is the name of the site with work, "N" is a count of
each of the three possible types of work (command, data, or remote execute),
and "Message" is the current status message for that
site as found in the STST file.
.PP
Included in "Message" may be the time left before UUCP can re-try the
call, and the count of the number of times that UUCP has tried
(unsuccessfully) to reach the site.
.SH SEE ALSO
uucp(1), uux(1), uuq(1), uucico(8)
.br
.I "UUCP Implementation Guide"
