.\" Copyright (c) 1983 Regents of the University of California.
.\" All rights reserved.  The Berkeley software License Agreement
.\" specifies the terms and conditions for redistribution.
.\"
.\"	@(#)ruptime.1c	6.1 (Berkeley) 4/29/85
.\"
.TH RUPTIME 1C "April 29, 1985"
.UC 5
.SH NAME
ruptime \- show host status of local machines
.SH SYNOPSIS
.B ruptime
[
.B \-a
] [
.B \-r
] [
.B \-l
] [
.B \-t
] [
.B \-u
]
.SH DESCRIPTION
.I Ruptime
gives a status line like
.I uptime
for each machine on the local network;
these are formed from packets broadcast by each host
on the network once a minute.
.PP
Machines for which no
status report has been received for 11 minutes are shown as being down.
.PP
Users idle an hour or more are not counted unless the
.B \-a
flag is given.
.PP
Normally, the listing is sorted by host name.
The
.B \-l ,
.B \-t ,
and
.B \-u
flags specify sorting by
load average,
uptime,
and number of users, respectively.
The
.B \-r
flag reverses the sort order.
.SH FILES
.DT
/usr/spool/rwho/whod.*	data files
.SH SEE ALSO
rwho(1C)
