.\" Copyright (c) 1980 Regents of the University of California.
.\" All rights reserved.  The Berkeley software License Agreement
.\" specifies the terms and conditions for redistribution.
.\"
.\"	@(#)uusend.1c	6.2 (Berkeley) 4/24/86
.\"
.TH UUSEND 1C "April 24, 1986"
.UC 4
.SH NAME
uusend \- send a file to a remote host
.SH SYNOPSIS
.B uusend
[
.B \-m
mode
]
sourcefile
sys1!sys2!..!remotefile
.SH DESCRIPTION
.I Uusend
sends a file to a given location on a remote system.
The system need not be directly connected to the local
system, but a chain of
.IR uucp (1)
links needs to connect the two systems.
.PP
If the
.B \-m
option is specified, the mode of the file on the remote
end will be taken from the octal number given.
Otherwise, the mode of the input file will be used.
.PP
The sourcefile
can be ``\-'',
meaning to use the standard input.
Both of these options are primarily intended for internal use of
.IR uusend .
.PP
The remotefile can include the ~userid syntax.
.SH DIAGNOSTICS
If anything goes wrong any further away than the first system down
the line, you will never hear about it.
.SH SEE\ ALSO
uux(1), uucp(1), uuencode(1)
.SH BUGS
This command should not exist, since
.I uucp
should handle it.
.PP
All systems along the line must have the
.I uusend
command available and allow remote execution of it.
.PP
Some uucp systems have a bug where binary files cannot be the
input to a
.I uux
command.  If this bug exists in any system along the line,
the file will show up severly munged.
