.\" Copyright (c) 1990 The Regents of the University of California.
.\" All rights reserved.
.\"
.\" This code is derived from software contributed to Berkeley by
.\" Chris Torek.
.\"
.\" %sccs.include.redist.man%
.\"
.\"	@(#)strcat.3	5.1 (Berkeley) %G%
.\"
.TH STRCAT 3 ""
.UC 4
.SH NAME
strcat \- concatenate strings
.SH SYNOPSIS
.nf
.ft B
#include <string.h>

char *
strcat(char *s, const char *append);
.ft R
.fi
.SH DESCRIPTION
.B Strcat
appends a copy of the null-terminated string
.I append
to the end of the null-terminated string
.IR s ,
then adds a terminating '\e0'.
.I S
must have sufficient space to hold the result.
.B Strcat
returns the pointer
.IR s .
.SH SEE ALSO
strncat(3)
.SH STANDARDS
.B Strcat
conforms to ANSI X3.159-1989 (``ANSI C'').
