C
C ADVENTURERS
C
	COMMON /ADVS/ ALNT,AROOM(4),ASCORE(4),AVEHIC(4),
&		AOBJ(4),AACTIO(4),ASTREN(4),AFLAG(4)
	INTEGER EQA(4,7)
	EQUIVALENCE (AROOM, EQA)
C
	COMMON /AFLAGS/ ASTAG
C
	COMMON /AINDEX/ PLAYER,AROBOT,AMASTR
