#!/bin/sh -
#
#	@(#)security	5.4 (Berkeley) %G%
#
PATH=/sbin:/bin:/usr/bin

host=`hostname -s`
echo "Subject: $host security check output"

LOG=/var/log
TMP=/tmp/_secure.$$

echo "Checking setuid files and devices:"
find / \( ! -fstype local \) -a -prune -o \
	\( -perm -u+s -o -perm -g+s -o ! -type f -a ! -type d \) \
	-a -ls 2>&1 > $TMP

if cmp $LOG/setuid.today $TMP >/dev/null; then :; else
	echo "$host setuid/device diffs:"
	diff $LOG/setuid.today $TMP
	mv $LOG/setuid.today $LOG/setuid.yesterday
	mv $TMP $LOG/setuid.today
fi
rm -f $TMP

echo ""
echo ""
echo "Checking for uids of 0:"
awk 'BEGIN {FS=":"} $3=="0" {print $1,$3}' /etc/master.passwd
