.\" Copyright (c) 1983 The Regents of the University of California.
.\" All rights reserved.
.\"
.\" Redistribution and use in source and binary forms are permitted
.\" provided that the above copyright notice and this paragraph are
.\" duplicated in all such forms and that any documentation,
.\" advertising materials, and other materials related to such
.\" distribution and use acknowledge that the software was developed
.\" by the University of California, Berkeley.  The name of the
.\" University may not be used to endorse or promote products derived
.\" from this software without specific prior written permission.
.\" THIS SOFTWARE IS PROVIDED ``AS IS'' AND WITHOUT ANY EXPRESS OR
.\" IMPLIED WARRANTIES, INCLUDING, WITHOUT LIMITATION, THE IMPLIED
.\" WARRANTIES OF MERCHANTIBILITY AND FITNESS FOR A PARTICULAR PURPOSE.
.\"
.\"	@(#)ruptime.1	6.2 (Berkeley) 9/20/88
.\"
.TH RUPTIME 1 "September 20, 1988"
.UC 5
.SH NAME
ruptime \- show host status of local machines
.SH SYNOPSIS
.B ruptime
[
.B \-a
] [
.B \-r
] [
.B \-l
] [
.B \-t
] [
.B \-u
]
.SH DESCRIPTION
.I Ruptime
gives a status line like
.I uptime
for each machine on the local network;
these are formed from packets broadcast by each host
on the network once a minute.
.PP
Machines for which no
status report has been received for 11 minutes are shown as being down.
.PP
Users idle an hour or more are not counted unless the
.B \-a
flag is given.
.PP
Normally, the listing is sorted by host name.
The
.B \-l ,
.B \-t ,
and
.B \-u
flags specify sorting by
load average,
uptime,
and number of users, respectively.
The
.B \-r
flag reverses the sort order.
.SH FILES
.DT
/usr/spool/rwho/whod.*	data files
.SH SEE ALSO
rwho(1)
