#	@(#)Makefile	5.1 (Berkeley) %G%

PROG=	pac
CFLAGS+=-I${.CURDIR}/../common_source
MAN8=	pac.0
SRCS=	pac.c printcap.c
.PATH:	${.CURDIR}/../common_source

.include "../../Makefile.inc"
.include <bsd.prog.mk>
