.\" Copyright (c) 1980 Regents of the University of California.
.\" All rights reserved.  The Berkeley software License Agreement
.\" specifies the terms and conditions for redistribution.
.\"
.\"	@(#)mount.8	6.3 (Berkeley) %G%
.\"
.TH MOUNT 8 ""
.UC 4
.SH NAME
mount, umount \- mount and dismount file systems
.SH SYNOPSIS
.nf
.B mount [-afrw]
.B mount [-frw] special | node
.B mount [-frw] special node
.PP
.B umount [-a]
.B umount special | node
.fi
.SH DESCRIPTION
.I Mount
announces to the system that a removable file system is present on the
block device \fIspecial\fP.  The file \fInode\fP must exist already and
it must be a directory.  It becomes the name of the newly mounted root.
The optional arguments \fI-r\fP and \fI-w\fP indicate that the file
system is to be mounted read-only or read-write, respectively.  If
either \fIspecial\fP or \fIfile\fP are not provided, the appropriate
information is taken from the \fIfstab\fP file.  The \fI-f\fP option
causes everything to be done except for the actual system call; if it's
not obvious, this ``fakes'' mounting the file system.
.PP
.I Umount
announces to the system that the removable file system \fInode\fP
or whatever removable file system was previously mounted on device
\fIspecial\fP should be removed.
.PP
If the \fI-a\fP option is present for either
.I mount
or
.I umount,
all of the file systems described in
.I fstab
are mounted or unmounted.
.PP
These commands
maintain a list of currently mounted file systems in
.I /etc/mtab.
If invoked without an argument,
.I mount
prints the list.
.PP
Physically write-protected and magnetic tape file
systems must be mounted read-only
or errors will occur when access times are updated,
whether or not any explicit write is attempted.
.SH FILES
/etc/mtab		mount table
.br
/etc/fstab	file system table
.SH "SEE ALSO"
mount(2), fstab(5), mtab(5)
.SH BUGS
Mounting garbaged file systems will crash the system.
.PP
Mounting a root directory on a non-directory
makes some apparently good pathnames invalid.
