/*	%M%	%I%	%E%	*/

#define ADWRAP		kdbADWRAP
#define BADCOM		kdbBADCOM
#define BADDAT		kdbBADDAT
#define BADEQ		kdbBADEQ
#define BADKET		kdbBADKET
#define BADLOC		kdbBADLOC
#define BADMOD		kdbBADMOD
#define BADRAD		kdbBADRAD
#define BADSYM		kdbBADSYM
#define BADSYN		kdbBADSYN
#define BADTXT		kdbBADTXT
#define BADVAR		kdbBADVAR
#define EXBKPT		kdbEXBKPT
#define NOADR		kdbNOADR
#define NOBKPT		kdbNOBKPT
#define NOCFN		kdbNOCFN
#define NOEOR		kdbNOEOR
#define NOMATCH		kdbNOMATCH
#define SZBKPT		kdbSZBKPT
#define adrflg		kdbadrflg
#define adrval		kdbadrval
#define bchkget		kdbbchkget
#define bkpthead	kdbbkpthead
#define bpstate		kdbbpstate
#define callpc		kdbcallpc
#define charpos		kdbcharpos
#define chkerr		kdbchkerr
#define chkget		kdbchkget
#define chkloc		kdbchkloc
#define cntflg		kdbcntflg
#define cntval		kdbcntval
#define command		kdbcommand
#define convdig		kdbconvdig
#define convert		kdbconvert
#define cursym		kdbcursym
#define delbp		kdbdelbp
#define digitptr	kdbdigitptr
#define ditto		kdbditto
#define dot		kdbdot
#define dotinc		kdbdotinc
#define	echo		kdbecho
#define endline		kdbendline
#define eof		kdbeof
#define eol		kdbeol
#define eqformat	kdbeqformat
#define eqsym		kdbeqsym
#define errflg		kdberrflg
#define error		kdberror
#define esymtab		kdbesymtab
#define execbkpt	kdbexecbkpt
#define execbkptf	kdbexecbkptf
#define executing	kdbexecuting
#define exform		kdbexform
#define expr		kdbexpr
#define expv		kdbexpv
#define findsym		kdbfindsym
#define flushbuf	kdbflushbuf
#define get		kdbget
#define getformat	kdbgetformat
#define getnum		kdbgetnum
#define getreg		kdbgetreg
#define infile		kdbinfile
#define inkdot		kdbinkdot
#define isymbol		kdbisymbol
#define item		kdbitem
#define	jmpbuf		kdbjmpbuf
#define lastc		kdblastc
#define lastcom		kdblastcom
#define lastframe	kdblastframe
#define line		kdbline
#define localsym	kdblocalsym
#define localval	kdblocalval
#define locmsk		kdblocmsk
#define locval		kdblocval
#define lookup		kdblookup
#define loopcnt		kdbloopcnt
#define lp		kdblp
#define maxoff		kdbmaxoff
#define maxpos		kdbmaxpos
#define maxstor		kdbmaxstor
#define mkfault		kdbmkfault
#define nextchar	kdbnextchar
#define nextpcs		kdbnextpcs
#define pcb		kdbpcb
#define peekc		kdbpeekc
#define printbuf	kdbprintbuf
#define printc		kdbprintc
#define printesc	kdbprintesc
#define printf		kdbprintf
#define	printins	kdbprintins
#define printnum	kdbprintnum
#define printpc		kdbprintpc
#define printptr	kdbprintptr
#define printregs	kdbprintregs
#define printtrace	kdbprinttrace
#define	printtrap	kdbprinttrap
#define psymoff		kdbpsymoff
#define put		kdbput
#define quotchar	kdbquotchar
#define radix		kdbradix
#define rdc		kdbrdc
#define readchar	kdbreadchar
#define readsym		kdbreadsym
#define reglist		kdbreglist
#define round		kdbround
#define runpcs		kdbrunpcs
#define savframe	kdbsavframe
#define savlastf	kdbsavlastf
#define savpc		kdbsavpc
#define scanbkpt	kdbscanbkpt
#define scanform	kdbscanform
#define setbp		kdbsetbp
#define setsym		kdbsetsym
#define stformat	kdbstformat
#define	streq		kdbstreq
#define subpcs		kdbsubpcs
#define symchar		kdbsymchar
#define symtab		kdbsymtab
#define term		kdbterm
#define userpc		kdbuserpc
#define valpr		kdbvalpr
#define var		kdbvar
#define varchk		kdbvarchk
