#
# Copyright (c) 1980 Regents of the University of California.
# All rights reserved.  The Berkeley software License Agreement
# specifies the terms and conditions for redistribution.
#
#	@(#)Makefile	5.2 (Berkeley) %G%
#
all:
	@echo "ddlcomp and ddlrun come in binary form only"

install:
	install -c -o bin -g bin -m 755 ddlrun ${DESTDIR}/usr/games/lib/ddlrun

clean:
depend:
