.\" Copyright (c) 1988, 1990 The Regents of the University of California.
.\" All rights reserved.
.\"
.\" %sccs.include.redist.roff%
.\"
.\"	@(#)diction.1	4.7 (Berkeley) %G%
.\"
.Dd 
.Dt DICTION 1
.Os
.Sh NAME
.Nm diction , explain
.Nd print wordy sentences; thesaurus for diction
.Sh SYNOPSIS
.Nm diction
.Op Fl f Ar pfile
.Op Fl ml
.Op Fl mm
.Op Fl n
.Ar file ...
.Nm explain
.Sh DESCRIPTION
.Nm Diction
finds all sentences in a document that contain phrases
from a data base of bad or wordy diction.
Each phrase is bracketed with
.Sq [\|] .
Because
.Nm diction
runs
.Xr deroff 1
before looking at the text, formatting
header files should be included as part of the input.
.Bl -tag -width "xF pfile"
.It Fl f Ar pfile.
Use
.Ar pfile
as a pattern file in addition to the default file.
.It Fl ml
causes
.Xr deroff 1
to skip lists, should be used if the document contains many lists of
non-sentences.
.It Fl mm
The default macro package,
.Fl ms ,
may be overridden with the flag
.Fl mm .
.It Fl n
Suppress usage of default file.
.El
.Pp
.Nm Explain
is an interactive thesaurus for the phrases found by diction.
.Sh SEE ALSO
.Xr deroff 1
.Sh BUGS
Use of non-standard formatting macros may cause
incorrect sentence breaks.
In particular,
.Nm diction
doesn't grok
.Fl me .
.Sh HISTORY
The
.Nm diction
command appeared in 
.Bx 4 .
