/*
 * ioconf.c 
 * Generated by config program
 */

#include "machine/pte.h"
#include "sys/param.h"
#include "sys/buf.h"

#define V(s)	V##s
#define C (caddr_t)

/*
 * ISA devices
 */

#include "i386/isa/isa_device.h"
#include "i386/isa/isa.h"
#include "i386/isa/icu.h"

extern struct isa_driver wddriver; extern V(wd0)();
extern struct isa_driver fddriver; extern V(fd0)();
extern struct isa_driver asdriver; extern V(as0)();
extern struct isa_driver pcdriver; extern V(pc0)();
extern struct isa_driver npxdriver; extern V(npx0)();
extern struct isa_driver comdriver; extern V(com1)();
extern struct isa_driver comdriver; extern V(com2)();
extern struct isa_driver wedriver; extern V(we0)();
extern struct isa_driver nedriver; extern V(ne0)();
extern struct isa_driver ecdriver; extern V(ec0)();
extern struct isa_driver isdriver; extern V(is0)();
extern struct isa_driver wtdriver; extern V(wt0)();

struct isa_device isa_devtab_bio[] = {
/* driver 	iobase	irq   drq     maddr    msiz    intr   unit */
{ &wddriver,    IO_WD1, IRQ14, -1,  C 0x00000,     0, V(wd0),   0 },
{ &fddriver,    IO_FD1,  IRQ6,  2,  C 0x00000,     0, V(fd0),   0 },
{ &asdriver,     0x330, IRQ11,  5,  C 0x00000,     0, V(as0),   0 },
{ &wtdriver,     0x300,  IRQ5,  1,  C 0x00000,     0, V(wt0),   0 },
0
};
struct isa_device isa_devtab_tty[] = {
/* driver 	iobase	irq   drq     maddr    msiz    intr   unit */
{ &pcdriver,    IO_KBD,  IRQ1, -1,  C 0x00000,     0, V(pc0),   0 },
{ &comdriver,   IO_COM1,  IRQ4, -1,  C 0x00000,     0, V(com1),   1 },
{ &comdriver,   IO_COM2,  IRQ3, -1,  C 0x00000,     0, V(com2),   2 },
0
};

struct isa_device isa_devtab_net[] = {
/* driver 	iobase	irq   drq     maddr    msiz    intr   unit */
{ &wedriver,     0x280,  IRQ2, -1,  C 0xD0000,  8192, V(we0),   0 },
{ &nedriver,     0x300,  IRQ2, -1,  C 0x00000,     0, V(ne0),   0 },
{ &ecdriver,     0x250,  IRQ2, -1,  C 0xD8000,  8192, V(ec0),   0 },
{ &isdriver,     0x280, IRQ10,  7,  C 0x00000,     0, V(is0),   0 },
0
};

struct isa_device isa_devtab_null[] = {
/* driver 	iobase	irq   drq     maddr    msiz    intr   unit */
{ &npxdriver,    IO_NPX, IRQ13, -1,  C 0x00000,     0, V(npx0),   0 },
0
};

