.\" Copyright (c) 1993
.\"	The Regents of the University of California.  All rights reserved.
.\"
.\" %sccs.include.redist.roff%
.\"
.\"	@(#)whereis.1	8.2 (Berkeley) %G%
.\"
.Dd 
.Dt WHEREIS 1
.Os BSD 3
.Sh NAME
.Nm whereis
.Nd locate programs
.Sh SYNOPSIS
.Nm whereis
.Op Ar program ...
.Sh DESCRIPTION
The
.Nm whereis
utility checks the standard binary directories for the specified programs,
printing out the paths of any it finds.
.Pp
The path searched is the string returned by the
.Xr sysctl 8
utility for the
.Dq user.cs_path
string.
.Sh SEE ALSO
.Xr sysctl 8 ,
.Sh COMPATIBILITY
The historic flags and arguments for the
.Nm whereis
utility are no longer available in this version.
.Sh HISTORY
The
.Nm whereis
command appeared in 3.0BSD.
