# define	IntTAG          	0
# define	RealTAG         	1
# define	StringTAG       	2
# define	ListTAG         	3
# define	ThreadTAG       	4
# define	GlobTAG         	5
# define	PorFTAG         	6
# define	BConstTAG       	7
# define	BTypeTAG        	8
# define	BVarTAG         	9
# define	BFuncTAG        	10
# define	BProcTAG        	11
# define	LabelDTAG       	12
# define	ConstDTAG       	13
# define	TypedTAG        	14
# define	TypeDTAG        	15
# define	EnumTTAG        	16
# define	ScalDTAG        	17
# define	RangeTTAG       	18
# define	SetTTAG         	19
# define	FileTTAG        	20
# define	PtrTTAG         	21
# define	PackTTAG        	22
# define	ArrayTTAG       	23
# define	RecTTAG         	24
# define	FldlstTAG       	25
# define	FieldDTAG       	26
# define	VarntTAG        	27
# define	VCaseTAG        	28
# define	VarDTAG         	29
# define	ParamDTAG       	30
# define	ValPTAG         	31
# define	VarPTAG         	32
# define	AssignTAG       	33
# define	PCallTAG        	34
# define	IfTAG           	35
# define	WhileTAG        	36
# define	RepeatTAG       	37
# define	ForUTAG         	38
# define	ForDTAG         	39
# define	CaseSTAG        	40
# define	CasedTAG        	41
# define	GotoTAG         	42
# define	LabelTAG        	43
# define	WithTAG         	44
# define	AssertTAG       	45
# define	BinOpTAG        	46
# define	AndTAG          	47
# define	OrTAG           	48
# define	EqTAG           	49
# define	NeTAG           	50
# define	LtTAG           	51
# define	GtTAG           	52
# define	LeTAG           	53
# define	GeTAG           	54
# define	InTAG           	55
# define	AddTAG          	56
# define	SubTAG          	57
# define	MultTAG         	58
# define	DivdTAG         	59
# define	DivTAG          	60
# define	ModTAG          	61
# define	UnOpTAG         	62
# define	PlusTAG         	63
# define	MinusTAG        	64
# define	NotTAG          	65
# define	FCallTAG        	66
# define	SetTAG          	67
# define	RangeTAG        	68
# define	VarTAG          	69
# define	PtrTAG          	70
# define	SubscTAG        	71
# define	SelTAG          	72
# define	NilTAG          	73
# define	WidthTAG        	74
# define	OctTAG          	75
# define	HexTAG          	76
