.TH FASTBOOT 8 "4 March 1983"
.UC 4
.SH NAME
fastboot, fasthalt \- reboot/halt the system without checking the disks
.SH SYNOPSIS
.B /etc/fastboot
[
.I boot-options
]
.br
.B /etc/fasthalt
[
.I halt-options
]
.SH DESCRIPTION
.I Fastboot
and
.I fasthalt
are shell scripts which reboot and halt the system without
checking the file systems.  This is done by creating a
file 
.IR /fastboot ,
then invoking the 
.I reboot
program.  The system startup script,
.IR /etc/rc ,
looks for this file and, if present, skips the normal
invocation of
.IR fsck (8).
.SH "SEE ALSO"
halt(8),
reboot(8),
rc(8)
