.TH SAVECORE 8 4/28/81
.UC 4
.SH NAME
savecore \- save a core dump of the operating system
.SH SYNOPSIS
.B savecore
.I dirname
.SH DESCRIPTION
.PP
.I Savecore
is meant to be called at the end of the /etc/rc file.  Its function
is to save the core dump of the system (assuming one was made) and to
write a reboot message in the shutdown log.
.PP
Savecore checks the core dump to be certain it corresponds with the
current running unix.  If it does it saves the core image in the file
.IR dirname /vmcore.n
and it's brother, the namelist,
.IR dirname /vmunix.n
The trailing ".n" in the pathnames is replaced by a number which grows
every time
.I savecore
is run in that directory.
.PP
Before savecore writes out a core image, it reads a number from the file
.IR dirname /minfree.
If there are fewer free blocks on the filesystem
which contains
.I dirname
than the number obtained from the minfree file, the core dump is not done.
If the minfree file does not exist, savecore always writes out the core
file (assuming that a core dump was taken).
.PP
.I Savecore
also writes a reboot message in the shut down log.  If the system crashed
as a result of a panic,
.I savecore
records the panic string in the shut down log too.
.SH FILES
.DT
/usr/adm/shutdownlog	Shut down log
.br
/vmunix			Current UNIX
.SH BUGS
