.\" Copyright (c) 1983 The Regents of the University of California.
.\" All rights reserved.
.\"
.\" %sccs.include.redist.man%
.\"
.\"	@(#)vv.4	6.4 (Berkeley) %G%
.\"
.TH VV 4 ""
.UC 5
.SH NAME
vv \- Proteon proNET 10 Megabit ring
.SH SYNOPSIS
.B "device vv0 at uba0 csr 0161000 vector vvrint vvxint"
.SH DESCRIPTION
The
.I vv
interface provides access to a 10 Mb/s Proteon proNET ring network.
.PP
The network address of the interface must be specified with an
an SIOCSIFADDR ioctl before data can be transmitted or received.
It is only permissible to change the network address while the
interface is marked "down".
.PP
The host's hardware address is discovered by putting the interface in
digital loopback mode (not joining the ring) and sending a broadcast
packet from which the hardware address is extracted.
.PP
Transmit timeouts are detected through use of a watchdog routine.
Lost input interrupts are checked for when packets are sent out.
.PP
If the installation is running CTL boards which use the old broadcast
address of 0 instead of the new address of 0xff, the define OLD_BROADCAST
should be specified in the driver.
.PP
The driver can use ``trailer'' encapsulation to minimize copying
data on input and output.
This may be disabled, on a per-interface basis,
by setting the IFF_NOTRAILERS flag with an SIOCSIFFLAGS ioctl.
.SH DIAGNOSTICS
.PP
\fBvv%d: host %d\fP.  The software announces the host
address discovered during autoconfiguration.
.PP
\fBvv%d: can't initialize\fP. The software was unable to
discover the address of this interface, so it deemed
"dead" will not be enabled.
.PP
\fBvv%d: error vvocsr=%b\fP.  The hardware indicated an error on
the previous transmission.
.PP
\fBvv%d: output timeout\fP.  The token timer has fired and the
token will be recreated.
.PP
\fBvv%d: error vvicsr=%b\fP.  The hardware indicated an error
in reading a packet off the ring.
.PP
\fBen%d: can't handle af%d\fP.  The interface was handed
a message with addresses formatted in an unsuitable address
family; the packet was dropped.
.PP
\fBvv%d: vs_olen=%d\fP.  The ring output routine has been
handed a message with a preposterous length.  This results in
an immediate 
.IR "panic: vs_olen" .
.SH SEE ALSO
netintro(4), inet(4)
.SH BUGS
The encapsulation of trailer packets in the 4.2BSD version of this driver
was incorrect (the packet type was in VAX byte order).
As a result, the trailer encapsulation in this version is not compatible
with the 4.2BSD VAX version.
