.so tmac.ilib
.TH TABLC 1 "The University of Arizona \- 8/11/84"
.SH NAME
tablc \- tabulate characters
.SH SYNOPSIS
\f3tablc\fP [\f3\-a\fR] [\f3\-n\fR] [\f3\-u\fR]
.SH DESCRIPTION
\fITablc\fR tabulates the characters in standard input and writes a summary
to standard output in which each character and the number of times it
occurs is listed. Characters are written using Icon's escape conventions.
.PP
The following options may appear in any order:
.IP \f3\-a\fP 0.75i
Write the summary in alphabetical order of the characters. This is the
default.
.IP \f3\-n\fP
Write the summary in numerical order of the counts.
.IP \f3\-u\fP
Write only the characters that occur just once.
.SH AUTHOR
Ralph E. Griswold
