.so tmac.ilib
.TH TRIM 1 "The University of Arizona \- 6/28/83"
.SH NAME
trim \- trim lines
.SH SYNOPSIS
\f3trim\fP [\fIn\fR] [\-\f3f\fR]
.SH DESCRIPTION
\fITrim\fR copies lines from standard input to standard output, truncating
the lines at \fIn\fR characters and removing any trailing blanks. The
default value for \fIn\fR is 80.
.PP
The \f3\-f\fR option causes all lines to be \fIn\fR characters long;
otherwise shorter lines are left as is.
.SH AUTHOR
Ralph E. Griswold
