/*
 * Initialization of table that maps error states to messages.
 */

     1, "end of file expected",
     2, "global, record, or procedure declaration expected",
     9, "link list expected",
    11, "missing semicolon",
    14, "global, record, or procedure declaration expected",
    19, "missing record name",
    22, "invalid global declaration",
    23, "missing procedure name",
    24, "missing procedure name", /* ? */
    25, "missing link file name",
    26, "missing field list in record declaration",
    28, "missing end",
    29, "missing semicolon or operator",
    44, "invalid operand for unary operator",
    45, "invalid operand for unary operator",
    46, "invalid operand for unary operator",
    47, "invalid operand for unary operator",
    48, "invalid operand for unary operator",
    49, "invalid operand for unary operator",
    59, "invalid create expression",
    66, "invalid keyword construction",
    93, "invalid if control expression",
    94, "invalid case control expression",
    95, "invalid while control expression",
    96, "invalid until control expression",
    97, "invalid every control expression",
    98, "invalid repeat expression",
   101, "missing parameter list in procedure declaration",
   105, "invalid local declaration",
   106, "invalid initial expression",
   112, "invalid operand",
   113, "invalid operand",
   114, "invalid operand in assignment",
   115, "invalid operand in augmented assignment",
   116, "invalid operand in augmented assignment",
   117, "invalid operand in augmented assignment",
   118, "invalid operand in augmented assignment",
   119, "invalid to clause",
   149, "invalid operand in alternation",
   150, "invalid operand",
   165, "invalid operand",
   168, "invalid operand",
   173, "invalid operand",
   178, "invalid operand",
   179, "invalid operand",
   180, "invalid operand",
   183, "invalid reference or subscript", /* ? */
   184, "invalid field name",
   193, "missing right parenthesis", /* ? */
   194, "missing right brace",
   200, "missing right bracket", /* ? */
   201, "missing then",
   202, "missing of",
   207, "missing identifier",
   209, "missing right parenthesis",
   211, "missing end",
   212, "invalid declaration",
   213, "missing semicolon or operator",
   231, "missing right bracket",
   241, "missing right parenthesis", /* ? */
   242, "invalid then clause",
   243, "missing left brace",
   244, "invalid do clause",
   245, "invalid do clause",
   246, "invalid do clause",
   248, "invalid argument list",
   253, "invalid by clause",
   255, "invalid section",
   261, "missing right parenthesis",
   264, "missing right bracket",
   266, "invalid case clause",
   272, "missing right bracket or ampersand",
   273, "missing right brace",
   274, "missing right parenthesis",
   278, "invalid else clause",
   279, "missing right brace or semicolon",
   281, "missing colon",
   282, "missing colon or ampersand",
   288, "invalid case clause",
   289, "invalid default clause",
   290, "invalid case clause",
