.\" Copyright (c) 1990 The Regents of the University of California.
.\" All rights reserved.
.\"
.\" This code is derived from software contributed to Berkeley by
.\" the Systems Programming Group of the University of Utah Computer
.\" Science Department.
.\"
.\" %sccs.include.redist.man%
.\"
.\"	@(#)tc.4	5.1 (Berkeley) %G%
.\"
.TH TC 4 ""
.UC 7
.SH NAME
tc \- HP98544-98550 ``Topcat'' and ``Catseye'' device interface
.SH DESCRIPTION
This driver is for the HP98544, 98545 and 98547 ``Topcat''
and HP98548, 98549, and 98550 ``Catseye'' display cards.
This driver merely checks for the existence of the device
and does minimal set up, as it is expected the applications will initialize
the device to their requirements.
The Topcat and Catseye are nearly identical in common usage and only the
Topcat will be referred to from now on.
.PP
The Topcat display cards are not user configurable.  If one is present on a
system, it will always have a frame buffer address of 0x200000 and a control
register address of 0x560000.  These are the HP series 300 ITE (Internal
Terminal Emulator) defaults.  The device can also be used as a graphics output
device.
.PP
The 
.IR ioctl (2)
calls supported by the BSD system for the Topcat are:
.TP
GRFIOCGINFO
Get Graphics Info
.sp
Get info about device, setting the entries in the
.I grfinfo
structure, as defined in <hpdev/grfioctl.h>.
For the 98544 or 98549,
the number of planes should be 1, as they are monochrome devices.
The number of planes for a 98545 is 4, translating to 15 colors,
excluding black.
The 98547 and 98548 cards have 6 planes, yielding 63 colors and black.
The 98550 has 8 planes, yielding 255 colors and black.
The displayed frame buffer size for the 98549 and 98550 is 2048 x 1024,
for the others it is 1024 x 768.
.TP
GRFIOCON
Graphics On
.sp
Turn graphics on by enabling CRT output.  The screen will come on, displaying
whatever is in the frame buffer, using whatever colormap is in place.
.TP
GRFIOCOFF
Graphics Off
.sp
Turn graphics off by disabling output to the CRT.  The frame buffer contents
are not affected.
.TP
GRFIOCMAP
Map Device to user space
.sp
Map in control registers and framebuffer space. Once the device file is
mapped, the frame buffer structure is accessible.  The frame buffer structure
describing Topcat/Catseye devices is defined in <hpdev/grf_tcreg.h>.
.PP
For further information about the use of ioctl see the man page.
.SH EXAMPLE
A small example of opening, mapping and using the device is given below.
For more examples of the details on the behavior of the device, see the device
dependent source files for the X Window System, in the
.I /usr/src/new/X/libhp
directory.
.DS
{
    struct tcboxfb *tc;
    u_char *Addr, frame_buffer;
    struct grfinfo gi;
    int disp_fd;

      disp_fd = open("/dev/grf0",1);

      if (ioctl (disp_fd, GRFIOCGINFO, &gi) < 0) return -1;

      (void) ioctl (disp_fd, GRFIOCON, 0);

      Addr = (u_char *) 0;
      if (ioctl (disp_fd, GRFIOCMAP, &Addr) < 0) {
           (void) ioctl (disp_fd, GRFIOCOFF, 0);
           return -1;
      }
      tc = (tcboxfb *) Addr;                          /* Control Registers   */
      frame_buffer = (u_char *) Addr + gi.gd_regsize; /* Frame buffer memory */
}
.DE
.SH "SEE ALSO"
ioctl(2), grf(4)
.SH FILES
.ta \w'/dev/crt9837, /dev/crt98550  'u
/dev/grf?	BSD special file
.br
/dev/crt9837, /dev/crt98550  HP-UX \fIstarbase\fP special files
.br
/dev/MAKEDEV.hpux	script for creating HP-UX special files
.SH ERRORS
.TP 15
[ENODEV]
no such device.
.TP 15
[EBUSY]
Another process has the device open.
.TP 15
[EINVAL]
Invalid ioctl specification.
.SH DIAGNOSTICS
None under BSD.
.br
HP-UX /usr/CE.utilities/Crtadjust programs must be used.
