.TH WC 1 
.SH NAME
wc \- word count
.SH SYNOPSIS
.B wc
[
.B \-lwc
]
[ name ... ]
.SH DESCRIPTION
.I Wc
counts lines, words and characters in the named files,
or in the standard input if no name appears.
A word is a maximal string of characters
delimited by spaces, tabs or newlines.
.PP
If the optional argument is present,
just the specified counts (lines, words or characters)
are selected by the letters
.BR l ,
.BR w ,
or
.BR c .
