.\" Copyright (c) 1989, 1990 The Regents of the University of California.
.\" All rights reserved.
.\"
.\" %sccs.include.redist.roff%
.\"
.\"     @(#)unvis.1	5.2 (Berkeley) %G%
.\"
.Dd 
.Dt UNVIS 1
.Os
.Sh NAME
.Nm unvis
.Nd "revert a visual representation of data back to original form"
.Sh SYNOPSIS
.Nm unvis
.Op Ar file ...
.Sh DESCRIPTION
.Nm Unvis
is the inverse function of
.Xr vis 1 .
It reverts
a visual representation of data back to its original form on standard output.
.Sh SEE ALSO
.Xr vis 1 ,
.Xr unvis 3 ,
.Xr vis 3
.Sh HISTORY
The
.Nm
command
.Ud .
