#
# Copyright (c) 1990 Regents of the University of California.
# All rights reserved.
#
# Redistribution and use in source and binary forms are permitted provided
# that: (1) source distributions retain this entire copyright notice and
# comment, and (2) distributions including binaries display the following
# acknowledgement:  ``This product includes software developed by the
# University of California, Berkeley and its contributors'' in the
# documentation or other materials provided with the distribution and in
# all advertising materials mentioning features or use of this software.
# Neither the name of the University nor the names of its contributors may
# be used to endorse or promote products derived from this software without
# specific prior written permission.
# THIS SOFTWARE IS PROVIDED ``AS IS'' AND WITHOUT ANY EXPRESS OR IMPLIED
# WARRANTIES, INCLUDING, WITHOUT LIMITATION, THE IMPLIED WARRANTIES OF
# MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE.
#
#	@(#)Makefile.test	1.1 (Berkeley) 10/21/90
#
# This makefile builds the domestic distribution tree for 4.3BSD
#
DESTDIR=
DIST=	/nbsd

all:

install:
	cmp -l src/libc/crypt.c ${DESTDIR}${DIST}/usr/src/lib/libc/gen/crypt.c
	cmp -l src/libc/libc.a.${MACHINE} ${DESTDIR}${DIST}/usr/lib/libc.a
	cmp -l src/libc/libc_p.a.${MACHINE} ${DESTDIR}${DIST}/usr/lib/libc_p.a
	cmp -l src/libc/crypt.3 ${DESTDIR}${DIST}/usr/src/lib/libc/gen/crypt.3
	cmp -l man/crypt.0.3 ${DESTDIR}${DIST}/usr/share/man/cat3/crypt.0
	cmp -l bin.${MACHINE}/login ${DESTDIR}${DIST}/usr/bin/login
	cmp -l bin.${MACHINE}/su ${DESTDIR}${DIST}/usr/bin/su
	cmp -l bin.${MACHINE}/lock ${DESTDIR}${DIST}/usr/bin/lock
	cmp -l bin.${MACHINE}/telnet ${DESTDIR}${DIST}/usr/bin/telnet
	cmp -l bin.${MACHINE}/uucpd ${DESTDIR}${DIST}/usr/libexec/uucpd
	cmp -l bin.${MACHINE}/ftpd ${DESTDIR}${DIST}/usr/libexec/ftpd
	cmp -l bin.${MACHINE}/rexecd ${DESTDIR}${DIST}/usr/libexec/rexecd
	cmp -l bin.${MACHINE}/makekey ${DESTDIR}${DIST}/usr/libexec/makekey
	#rm -rf ${DESTDIR}${DIST}/usr/src/bin/rcp
	diff -r src/rcp ${DESTDIR}${DIST}/usr/src/bin/rcp
	cmp -l bin.${MACHINE}/rcp ${DESTDIR}${DIST}/bin/rcp
	cmp -l bin.${MACHINE}/passwd ${DESTDIR}${DIST}/usr/bin/passwd
	#rm -rf ${DESTDIR}${DIST}/usr/src/usr.bin/passwd/Makefile*
	cmp -l src/passwd/Makefile ${DESTDIR}${DIST}/usr/src/usr.bin/passwd/Makefile
	#rm -rf ${DESTDIR}${DIST}/usr/src/usr.bin/rlogin
	diff -r src/rlogin ${DESTDIR}${DIST}/usr/src/usr.bin/rlogin
	cmp -l bin.${MACHINE}/rlogin ${DESTDIR}${DIST}/usr/bin/rlogin
	cmp -l man/rlogin.0 ${DESTDIR}${DIST}/usr/share/man/cat1/rlogin.0
	#rm -rf ${DESTDIR}${DIST}/usr/src/usr.bin/rsh
	diff -r src/rsh ${DESTDIR}${DIST}/usr/src/usr.bin/rsh
	cmp -l bin.${MACHINE}/rsh ${DESTDIR}${DIST}/usr/bin/rsh
	cmp -l man/rsh.0 ${DESTDIR}${DIST}/usr/share/man/cat1/rsh.0
	#rm -rf ${DESTDIR}${DIST}/usr/src/libexec/rlogind
	diff -r src/rlogind ${DESTDIR}${DIST}/usr/src/libexec/rlogind
	cmp -l bin.${MACHINE}/rlogind ${DESTDIR}${DIST}/usr/libexec/rlogind
	#rm -rf ${DESTDIR}${DIST}/usr/src/libexec/rshd
	diff -r src/rshd ${DESTDIR}${DIST}/usr/src/libexec/rshd
	cmp -l bin.${MACHINE}/rshd ${DESTDIR}${DIST}/usr/libexec/rshd
	cmp -l src/Makefile.libexec ${DESTDIR}${DIST}/usr/src/libexec/Makefile
	cmp -l bin.${MACHINE}/kpasswdd ${DESTDIR}${DIST}/usr/libexec/kpasswdd
	cmp -l man/kpasswdd.0 ${DESTDIR}${DIST}/usr/share/man/cat8/kpasswdd.0
	cmp -l src/Makefile.old ${DESTDIR}${DIST}/usr/src/old/Makefile
	#rm -rf ${DESTDIR}${DIST}/usr/src/old/crypt
	diff -r src/crypt ${DESTDIR}${DIST}/usr/src/old/crypt
	cmp -l bin.${MACHINE}/crypt ${DESTDIR}${DIST}/usr/old/crypt
	cmp -l man/crypt.0.1 ${DESTDIR}${DIST}/usr/share/man/old/cat1/crypt.0
	cmp -l src/Makefile.usrbin ${DESTDIR}${DIST}/usr/src/usr.bin/Makefile
	#rm -rf ${DESTDIR}${DIST}/usr/src/usr.bin/xsend
	diff -r src/xsend ${DESTDIR}${DIST}/usr/src/usr.bin/xsend
	cmp -l bin.${MACHINE}/xsend ${DESTDIR}${DIST}/usr/bin/xsend
	cmp -l bin.${MACHINE}/xget ${DESTDIR}${DIST}/usr/bin/xget
	cmp -l bin.${MACHINE}/enroll ${DESTDIR}${DIST}/usr/bin/enroll
	cmp -l man/xsend.0 ${DESTDIR}${DIST}/usr/share/man/cat1/xsend.0
	#rm -f ${DESTDIR}${DIST}/usr/share/man/cat1/xget.0
	#ln ${DESTDIR}${DIST}/usr/share/man/cat1/xsend.0 \
		${DESTDIR}${DIST}/usr/share/man/cat1/xget.0
	#rm -f ${DESTDIR}${DIST}/usr/share/man/cat1/enroll.0
	#ln ${DESTDIR}${DIST}/usr/share/man/cat1/xsend.0 \
		${DESTDIR}${DIST}/usr/share/man/cat1/enroll.0
	cmp -l src/ex/Makefile ${DESTDIR}${DIST}/usr/src/usr.bin/ex/Makefile
	cmp -l src/ex/ex.h ${DESTDIR}${DIST}/usr/src/usr.bin/ex/ex.h
	cmp -l src/ex/ex.c ${DESTDIR}${DIST}/usr/src/usr.bin/ex/ex.c
	cmp -l src/ex/ex_io.c ${DESTDIR}${DIST}/usr/src/usr.bin/ex/ex_io.c
	cmp -l src/ex/ex_temp.c ${DESTDIR}${DIST}/usr/src/usr.bin/ex/ex_temp.c
	cmp -l bin.${MACHINE}/ex ${DESTDIR}${DIST}/usr/bin/ex
	cmp -l src/ed/ed.c ${DESTDIR}${DIST}/usr/src/bin/ed/ed.c
	cmp -l src/ed/ed.1 ${DESTDIR}${DIST}/usr/src/bin/ed/ed.1
	cmp -l bin.${MACHINE}/ed ${DESTDIR}${DIST}/bin/ed
	cmp -l man/ed.0 ${DESTDIR}${DIST}/usr/share/man/cat1/ed.0
	cmp -l src/kerberosIV/libdes.a.${MACHINE} ${DESTDIR}${DIST}/usr/lib/libdes.a
	cmp -l src/kerberosIV/libdes_p.a.${MACHINE} ${DESTDIR}${DIST}/usr/lib/libdes_p.a
	diff -r src/kerberosIV/des ${DESTDIR}${DIST}/usr/src/kerberosIV/des

clean:
