.\" Copyright (c) 1985 Regents of the University of California.
.\" All rights reserved.  The Berkeley software License Agreement
.\" specifies the terms and conditions for redistribution.
.\"
.\"	@(#)mkpasswd.8	6.3 (Berkeley) 6/3/86
.\"
.TH MKPASSWD 8 "June 3, 1986"
.UC 6
.SH NAME
mkpasswd \- generate hashed password table
.SH SYNOPSIS
.B /etc/mkpasswd
[
.B \-v
]
passwdfile
.SH DESCRIPTION
.I Mkpasswd
is used to generated the hashed password database used by the
library routines
.B getpwnam()
and
.BR getpwuid() .
If the
.B \-v
option is supplied, each entry will be listed as it is added.
The file
.I passwdfile
is usually /etc/ptmp (invoked by vipw(8)), and in any case
must be in the format of /etc/passwd (see passwd(5)).
.I Mkpasswd
will generate database files named
.I passwdfile.pag
and
.I passwdfile.dir.
.I Mkpasswd
will exit with a non-zero exit code if any errors are detected.
.SH FILES
.ta \w'passwdfile.dir    'u
\fIpasswdfile\fR.pag	- database filenames
.br
\fIpasswdfile\fR.dir
.SH SEE ALSO
getpwent(3), vipw(8), passwd(5)
