#	@(#)Makefile	5.7.1.1 (Berkeley) 5/8/91
#
#	-DEXTENDED 
#		if you want the paste & spaste macros.

PROG=	m4
CFLAGS+=-DEXTENDED
SRCS =  main.c eval.c serv.c look.c misc.c expr.c
NOMAN=	noman

.include <bsd.prog.mk>
