.TH FTAMUSERS 5 "16 Nov 1988"
.\" $Header: /f/osi/ftam2/RCS/ftamusers.5,v 7.1 91/02/22 09:24:15 mrose Interim $
.\"
.\"
.\" $Log:	ftamusers.5,v $
.\" Revision 7.1  91/02/22  09:24:15  mrose
.\" Interim 6.8
.\" 
.\" Revision 7.0  89/11/23  21:54:46  mrose
.\" Release 6.0
.\" 
.SH NAME
ftamusers \- list of users prohibited by ftam
.SH SYNOPSIS
.B \*(EDftamusers
.SH DESCRIPTION
The \fIftamusers\fR file contains a list of users who cannot access
this system using the  \fIftam\fR\0(1c) program.
This file contains one user name per line.
.SH "SEE ALSO"
ftam(1C), ftamd(8C)
