.\" Copyright (c) 1987 The Regents of the University of California.
.\" All rights reserved.
.\"
.\" %sccs.include.redist.roff%
.\"
.\"	@(#)fstat.1	5.9 (Berkeley) %G%
.\"
.TH FSTAT 1 ""
.UC 4
.SH NAME
fstat \- file status
.SH SYNOPSIS
.B fstat
[
.B \-u
user ] [
.B \-p
pid ] [
.B \-fnv ] [
.B filename... 
]
.SH DESCRIPTION
.I Fstat
identifies open files.
A file is considered open by a process if it was explicitly opened,
is the working directory, root directory, active pure text, or kernel
trace file for that process.
If no options are specified,
.I fstat
reports on all open files in the system.
.PP
Options:
.TP 6
.B  \-u
Report all files open by the specified user.
.TP 6
.B  \-p
Report all files open by the specified process.
.TP 6
.B  \-f
If additional filename arguments are present, restrict to files
that are open in the same filesystem as the named file arguments.
For example, to find all files open in the filesystem that the
directory "/usr/src" resides in, type "fstat -f /usr/src".
.TP 6
.B  \-n
Numerical format.  Print the device number (maj,min) of the filesystem
the file resides in rather than the mount point name; for special
files, print the
device number that the special device refers to rather than the filename
in /dev; and print the mode of the file in octal instead of symbolic form.
.TP 6
.B  \-v
Verbose mode.  Print error messages upon failures to locate particular
system data structures rather than silently ignoring them.  Most of
these data structures are dynamically created and deleted and it is
possible for them to disappear while fstat is running.  This
is normal and  unavoidable since the rest of the system is running while
fstat itself is running.
.TP 6
.B filename...
Restrict reports to the specified files.
.PP
The following fields are printed:
.TP 6
.B  USER
The username of the owner of the process (effective uid).
.TP 6
.B CMD
The command name of the process.
.TP 6
.B PID
The process id.
.TP 6
.B FD
The file number in the per-process open file table or one of the following
special names:
.sp
.nf
	text	- pure text inode
	wd 	- current working directory
	root	- root inode
	tr	- kernel trace file
.fi
.sp
If the file number is followed by an asterisk (``*''), the file is
not an inode, but rather a socket, FIFO, or there is an error.
In this case the remainder of the line doesn't
correspond to the remaining headers -- the format of the line
is described later under "Sockets".
.TP 6
.B MOUNT
If the -n flag wasn't specified, this header is present and is the
pathname that the filesystem the file resides in is mounted on.
.TP 6
.B DEV
If the -n flag is specified, this header is present and is the
major/minor number of the device that this file resides in.
.TP 6
.B INUM
The inode number of the file.
.TP 6
.B MODE
The mode of the file.  If the -n flag isn't specified, the mode is printed
using a symbolic format (see strmode(3)); otherwise, the mode is printed
as an octal number.
.TP 6
.B SZ|DV
If the file is not a character or block special, prints the size of
the file in bytes.  Otherwise, if the -n flag is not specified, prints
the name of the special file as located in /dev.  If that cannot be
located, or the -n flag is specified, prints the major/minor device
number that the special device refers to.
.TP 6
.B NAME
If filename arguments are specified and the -f flag is not, then
this field is present and is the name associated with the given file.
Normally the name cannot be determined since there is no mapping
from an open file back to the directory entry that was used to open
that file.  Also, since different directory entries may reference
the same file (via ln(2)), the name printed may not be the actual
name that the process originally used to open that file.
.SH Sockets
The formating of open sockets depends on the protocol domain.
In all cases the first field is the domain name, the second field
is the socket type (stream, dgram, etc), and the third is the socket
flags field (in hex).
The remaining fields are protocol dependent.
For tcp, it is the address of the tcpcb, and for udp, the inpcb (socket pcb).
For unix domain sockets, its the address of the socket pcb and the address
of the connected pcb (if connected).
Otherwise the protocol number and address of the socket itself are printed.
The attempt is to make enough information available to 
permit further analysis without duplicating
.IR netstat (1).
.PP
For example, the addresses mentioned above are the addresses which the
``netstat -A'' command would print for tcp, udp, and unixdomain.
Note that since pipes are implemented using sockets, a pipe appears as a
connected unix domain stream socket.
A unidirectional unix domain socket indicates the direction of flow with
an arrow (``<-'' or ``->''), and a full duplex socket shows a double arrow
(``<->'').
.SH BUGS
Since
.I fstat
takes a snapshot of the system, it is only correct for a very short period
of time.
.SH "SEE ALSO"
netstat(1), ps(1), systat(1), stat(2), pstat(8)
