.TH MAN 1 "18 January 1983"
.UC 4
.SH NAME
man \- find manual information by keywords; print out the manual
.SH SYNOPSIS
.br
.B man
.B \-k
keyword ...
.br
.B man
.B \-f
file ...
.br
.B man
[
.B \-
] [
.B \-t
] [
section
]
title ...
.SH DESCRIPTION
.I Man
is a program which gives information from the programmers manual.
It can be asked for one line descriptions of commands specified by
name, or for all commands whose description contains any of a set of
keywords.  It can also provide on-line access to the sections of the
printed manual.
.PP
When given the option
.B \-k
and a set of keywords,
.I man
prints out a one line synopsis of each manual sections whose
listing in the table of contents contains that keyword.
.PP
When given the option
.B \-f
and a list of file names, \fIman\fR attempts to locate manual
sections related to those files, printing out the table of contents
lines for those sections.
.PP
When neither
.B \-k
nor
.B \-f
is specified,
.I man
formats a specified set of manual pages.
If a section specifier is given
.I man
looks in the that section of the manual for the given
.I titles.
.I Section
is an Arabic section number (3 for instance).  The number may followed by
a single letter classifier (1g for instance)
indicating a graphics program in section 1.  If
.I section
is omitted,
.I man
searches all sections of the manual, giving preference to commands
over subroutines in system libraries, and printing the first section
it finds, if any.
.PP
If the standard output is a teletype, or if the flag
.B \-
is given,
.I man
pipes its output through
.IR cat (1)
with the option
.B \-s
to crush out useless blank lines,
.IR ul (1)
to create proper underlines for different terminals, and through
.IR more (1)
to stop after each page on the screen.
Hit a space to continue,
a control-D to scroll 11 more lines when the output stops.
.PP
The
.B \-t
flag causes
.I man
to arrange for the specified section to be
.I troff'ed
to a suitable raster output device; see
.IR vtroff (1).
.SH FILES
/usr/man/man?/*
.br
/usr/man/cat?/*
.SH SEE\ ALSO
more(1), ul(1), whereis(1), catman(8)
.SH BUGS
The manual is supposed to be reproducible either on the phototypesetter
or on a typewriter.
However, on a typewriter some information is necessarily lost.
