.\" Copyright (c) 1990 Regents of the University of California.
.\" All rights reserved.
.\"
.\" Redistribution and use in source and binary forms are permitted provided
.\" that: (1) source distributions retain this entire copyright notice and
.\" comment, and (2) distributions including binaries display the following
.\" acknowledgement:  ``This product includes software developed by the
.\" University of California, Berkeley and its contributors'' in the
.\" documentation or other materials provided with the distribution and in
.\" all advertising materials mentioning features or use of this software.
.\" Neither the name of the University nor the names of its contributors may
.\" be used to endorse or promote products derived from this software without
.\" specific prior written permission.
.\" THIS SOFTWARE IS PROVIDED ``AS IS'' AND WITHOUT ANY EXPRESS OR IMPLIED
.\" WARRANTIES, INCLUDING, WITHOUT LIMITATION, THE IMPLIED WARRANTIES OF
.\" MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE.
.\"
.\"     @(#)ranlib.1	6.4 (Berkeley) 7/24/90
.\"
.Dd July 24, 1990
.Dt RANLIB 1
.BSD 4.4
.Sh NAME
.Nm ranlib
.Nd preprocess archives for efficient linking
.Sh SYNOPSIS
.Nm ranlib
.Op Fl t
.Ar archive_file ...
.Sh DESCRIPTION
.Nm Ranlib
is a preprocessor for the loading utility
.Xr ld 1 .
.Nm Ranlib
creates a randomized library from the given
.Ar archive_file
with
the file entry named
.Sy \&__.SYMDEF
prepended.
The
.Sy \&__.SYMDEF
file entry is a dictionary the loader can detect and interpret
to resolve external references at link time.
To generate the library, the
.Xr ar 1
utility is used.
.Tw 8n
.Tp Fl t
Ranlib only "touches" the archives and does not modify them.
This is useful after copying an archive
or using the
.Fl t
option of
.Xr make  1
in order to avoid having
.Xr ld  1
complain about
an
.Dq out of date
symbol table.
.Tp
.Sh SEE ALSO
.Xr ar 1 ,
.Xr ld 1 ,
.Xr lorder 1 ,
.Xr make 1 ,
.Xr nm 1
.Sh HISTORY
.Nm Ranlib
appeared in Version 7 AT&T UNIX.
.Sh BUGS
The archiving is a separate process and phase
errors may occur (see the
.Fl t
option above).
