#define ECHR		1
#define ESYSTEM		2
#define EBUILTIN	3
#define EHALT		4
#define ENILPTR		5
#define EPASTEOF	6
#define ESQRT		7
#define ESTKNEMP	8
#define ESUBSCR		9
#define EREFINAF	10
#define EWRITE		11
#define ENAMESIZE	12
#define ELN		13
#define EBADOP		14
#define EBADINUM	15
#define EGOTO		16
#define ECASE		17
#define ESEEK		18
#define ECREATE		19
#define EOUTOFMEM	20
#define ECTTOT		21
#define ESTLIM		22
#define ESTKOVFLO	23
#define EBADFNUM	24
#define EREMOVE		25
#define ECLOSE		26
#define EOPEN		27
#define EARGV		28
#define EPACK		29
#define EUNPACK		30
#define ERANGE		31
#define EASRT		32
#define EREADIT		33
#define EWRITEIT	34
#define EINTR		35
#define EASSIGN		36
#define EFIXADD		37
#define EFLTADD		38
#define EFIXSUB		39
#define EFLTSUB		40
#define EFIXMUL		41
#define EFLTMUL		42
#define EFIXDIV		43
#define EFLTDIV		44
#define EMODDIV		45
#define EFIXNEG		46
#define ELLIMIT		47
#define EFRAMESIZE	48
#define ETRASHHEAP	49
