#define AUTOINDENT      0
#define AUTOPRINT       1
#define AUTOWRITE       2
#define BEAUTIFY        3
#define DIRECTORY       4
#define EDCOMPATIBLE    5
#define ERRORBELLS      6
#define HARDTABS        7
#define IGNORECASE      8
#define LISP            9
#define LIST            10
#define MAGIC           11
#define NUMBER          12
#define OPEN            13
#define OPTIMIZE        14
#define PARAGRAPHS      15
#define PROMPT          16
#define REDRAW          17
#define REMAP           18
#define REPORT          19
#define SCROLL          20
#define SECTIONS        21
#define SHELL           22
#define SHIFTWIDTH      23
#define SHOWMATCH       24
#define SLOWOPEN        25
#define TAGS            26
#define TABSTOP         27
#define TERM            28
#define TERSE           29
#define TIMEOUT         30
#define TTYTYPE         31
#define UNDOMACRO       32
#define WARN            33
#define WINDOW          34
#define WRAPSCAN        35
#define WRAPMARGIN      36
#define WRITEANY        37

#define	NOPTS	38
