#define AUTOINDENT      0
#define AUTOPRINT       1
#define AUTOWRITE       2
#define BEAUTIFY        3
#define DIRECTORY       4
#define EDCOMPATIBLE    5
#define ERRORBELLS      6
#define HARDTABS        7
#define IGNORECASE      8
#define LISP            9
#define LIST            10
#define MAGIC           11
#define MESG            12
#define NUMBER          13
#define OPEN            14
#define OPTIMIZE        15
#define PARAGRAPHS      16
#define PROMPT          17
#define READONLY        18
#define REDRAW          19
#define REMAP           20
#define REPORT          21
#define SCROLL          22
#define SECTIONS        23
#define SHELL           24
#define SHIFTWIDTH      25
#define SHOWMATCH       26
#define SLOWOPEN        27
#define TABSTOP         28
#define TAGLENGTH       29
#define TAGS            30
#define TERM            31
#define TERSE           32
#define TIMEOUT         33
#define TTYTYPE         34
#define WARN            35
#define WINDOW          36
#define WRAPSCAN        37
#define WRAPMARGIN      38
#define WRITEANY        39

#define	NOPTS	40
