.\" Copyright (c) 1983 Regents of the University of California.
.\" All rights reserved.
.\"
.\" Redistribution and use in source and binary forms are permitted
.\" provided that this notice is preserved and that due credit is given
.\" to the University of California at Berkeley. The name of the University
.\" may not be used to endorse or promote products derived from this
.\" software without specific prior written permission. This software
.\" is provided ``as is'' without express or implied warranty.
.\"
.\"	@(#)logger.1	6.2 (Berkeley) %G%
.\"
.TH LOGGER 1 ""
.UC 6
.SH NAME
logger \- make entries in the system log
.SH SYNOPSIS
.B logger
[
.B \-t
tag
] [
.B \-p
pri
] [
.B \-i
] [
.B \-f
file
] [
message ...
]
.SH ARGUMENTS
.TP 12n
.BI \-t \ tag
Mark every line in the log with the specified
.IR tag .
.TP
.BI \-p \ pri
Enter the message with the specified priority.
The priority may be specified numerically
or as a ``facility.level''
pair.
For example, ``\-p local3.info''
logs the message(s) as
.IR info rmational
level in the
.I local3
facility.
The default is ``user.notice.''
.TP
.B \-i
Log the process id of the logger process
with each line.
.TP
.BI \-f \ file
Log the specified file.
.TP
message
The message to log; if not specified, and the \fB-f\fP flag is not
provided, standard input is logged.
.SH DESCRIPTION
.I Logger
provides a program interface to the
.IR syslog (3)
system log module.
.SH EXAMPLES
logger System rebooted
.PP
logger \-p local0.notice \-t HOSTIDM \-f /dev/idmc
.SH SEE ALSO
syslog(3),
syslogd(8)
