.TH SLEEP 1L \" -*- nroff -*-
.SH NAME
sleep \- delay for a specified amount of time
.SH SYNOPSIS
.B sleep
number[smhd]...
.SH DESCRIPTION
This manual page
documents the GNU version of
.BR sleep .
.B sleep
pauses for an amount of time specified by the sum of the values of the
command line arguments.  Each argument is a number followed by an
optional unit; the default is seconds.  The units are:
.IP s
seconds
.IP m
minutes
.IP h
hours
.IP d
days
