.\" Copyright (c) 1983 Regents of the University of California.
.\" All rights reserved.  The Berkeley software License Agreement
.\" specifies the terms and conditions for redistribution.
.\"
.\"	@(#)intro.8	6.3 (Berkeley) 5/29/86
.\"
.TH INTRO 8 "May 29, 1986"
.UC 5
.SH NAME
intro \- introduction to system maintenance and operation commands
.SH DESCRIPTION
This section contains information related to system operation
and maintenance.
It describes commands used to create new file systems,
.IR newfs ,
verify the integrity of the file systems,
.IR fsck ,
control disk usage,
.IR edquota ,
maintain system backups,
.IR dump ,
and recover files when disks die an untimely death,
.IR restore .
The section 
.I format
should be consulted when formatting disk packs.
Network related services are distinguished as 8C.
The section
.I crash
should be consulted in understanding how to interpret system
crash dumps.
