.\"	@(#)passwd.5	5.1 (Berkeley) %G%
.\"
.TH PASSWD 5  "15 January 1983"
.AT 3
.SH NAME
passwd \- password file
.SH DESCRIPTION
.I Passwd
contains for each user the
following information:
.HP 10
name (login name, contains no upper case)
.br
.ns
.HP 10
encrypted password
.br
.ns
.HP 10
numerical user ID
.br
.ns
.HP 10
numerical group ID
.br
.ns
.HP 10
user's real name, office, extension, home phone.
.br
.ns
.HP 10
initial working directory
.br
.ns
.HP 10
program to use as Shell
.PP
The name may contain `&', meaning insert the login name.
This information is set by the
.IR chfn (1)
command and used by the
.IR finger (1)
command.
.PP
This is an ASCII file.  Each field within each user's entry
is separated from the next by a colon.
Each user is separated from the next by a new-line.
If the password field is null, no password is demanded;
if the Shell field is null, then
.I /bin/sh
is used.
.PP
This file resides in directory /etc.
Because of the encrypted
passwords, it can and does have general read
permission and can be used, for example,
to map numerical user ID's to names.
.PP
Appropriate precautions must be taken to lock the file against changes
if it is to be edited with a text editor;
.IR vipw (8)
does the necessary locking.
.SH FILES
/etc/passwd
.SH "SEE ALSO"
getpwent(3), login(1), crypt(3), passwd(1), group(5), chfn(1), finger(1),
vipw(8), adduser(8)
.SH BUGS
A binary indexed file format should be available for fast access.
.PP
User information (name, office, etc.) should be stored elsewhere.
