.\" Copyright (c) 1990 The Regents of the University of California.
.\" All rights reserved.
.\"
.\" This code is derived from software contributed to Berkeley by
.\" the Systems Programming Group of the University of Utah Computer
.\" Science Department.
.\"
.\" %sccs.include.redist.man%
.\"
.\"	@(#)format.8	5.1 (Berkeley) %G%
.\"
.TH FORMAT 8 ""
.SH NAME
format \- how to format disks and tapes
.SH DESCRIPTION
.PP
Currently, there are no ``native'' BSD media formatting utilities.
Formatting of both disks and cartridge tapes must be done either
standalone or under HP-UX using the
.I mediainit
utility distributed by HP.
Note that HP-brand cartridge tapes come pre-formatted, and HP disks
are supposed to.
