.TH HP 4 
.UC
.SH NAME
hp \- RH-11/RP04, RP05, RP06, RM03 moving-head disk
.SH DESCRIPTION
Files with minor device numbers 0 through 7 refer to various portions
of drive 0;
minor devices 8 through 15 refer to drive 1, etc.
.PP
The origin and size of the pseudo-disks on each drive are
as follows:
.PP
RP partitions
.br
	disk	start	length
.br
	0	0	15884
.br
	1	15884	33440
.br
	2	40964	8360
.br
	3	0	0
.br
	4	0	0
.br
	5	0	0
.br
	6	49324	291346
.br
	7	0	0
.PP
RM partitions
.br
	disk	start	length
.br
	0	0	15884
.br
	1	16000	33440
.br
	2	0	0
.br
	3	0	0
.br
	4	0	0
.br
	5	0	0
.br
	6	49600	82080
.br
	7	0	0
.PP
It is unwise for all of these files to be present in one installation,
since there is overlap in addresses and protection becomes
a sticky matter.
Ordinarily devices 0 and 6 (or 0 and 7) will be used.
.PP
The
block
files
access the disk via the system's normal
buffering mechanism
and may be read and written without regard to
physical disk records.
There is also a `raw' interface
which provides for direct transmission between the disk
and the user's read or write buffer.
A single read or write call results in exactly one I/O operation
and therefore raw I/O is considerably more efficient when
many words are transmitted.
The names of the raw files
conventionally
begin with
an extra `r.'
.PP
In raw I/O the buffer must begin on a word boundary,
and counts should be a multiple of 512 bytes
(a disk block).
Likewise
.I seek
calls should specify a multiple of 512 bytes.
.SH FILES
/dev/rp?, /dev/rrp?
.SH SEE ALSO
rp(4)
