.TH LPR 1
.UC 4
.SH NAME
lpr, lprm, lpq, print \- line printer spooler
.SH SYNOPSIS
.B lpr
[
.B \-m
] [ name ... ]
.br
.B lprm
[
id ...
] [
filename ...
] [
owner ...
]
.br
.B lpq
.br
.B print
file ...
.SH DESCRIPTION
.I Lpr 
causes the
named files
to be queued for printing.
If no files are named, the standard input is read.
The option
.B \-m
causes notification via
.IR mail (1)
to be sent when the job completes.
.PP
.I Lprm
removes an entry from the line printer queue.
The id, filename or owner should be that reported by
.I lpq.
All appropriate files will be removed.
The id of each file removed from the queue will be printed.
.PP
.I Lpq
prints the line printer queue.
Each entry in the queue is printed showing the owner of the queue entry,
an identification number,
the size of the entry in characters,
and the file which is to be printed.
The
.I id
is useful for removing a specific entry from the printer queue using
.IR lprm (1).
.PP
.I Print
.I pr's
a copy of each named file on the line printer.
It is a one line shell script:
.PP
.DT
	pr $* | lpr
.SH FILES
.ta 2i
/usr/spool/lpd/*	spool area
.br
/usr/lib/lpd	printer daemon
.br
/usr/lib/lpf	filter to handle banners and underlining
.SH SEE\ ALSO
pr(1)
.SH BUGS
Queued jobs print in directory (seemingly random) order.
