.\" Copyright (c) 1991, 1993
.\"	The Regents of the University of California.  All rights reserved.
.\"
.\" %sccs.include.redist.roff%
.\"
.\"     @(#)intro.1	8.2 (Berkeley) %G%
.\"
.Dd 
.Dt INTRO 1
.Os
.Sh NAME
.Nm intro
.Nd introduction to general commands (tools and utilities)
.Sh DESCRIPTION
Section one of the manual contains most of the commands
which comprise the
.Bx
user environment.
Some of the commands included in section one are
text editors, command shell interpreters,
searching and sorting tools,
file manipulation commands
system status commands,
remote file copy commands, mail commands,
compilers and compiler tools,
formatted output tools,
and line printer commands.
.Pp
All commands set a status value upon exit which may be tested
to see if the command completed normally.
The exit values and their meanings are explained in the individual
manuals.  Traditionally, the value 0 signifies successful
completion of the command.
.Sh SEE ALSO
.Xr man 1
.Xr intro 2
.Xr intro 3
.Xr intro 3
.Xr intro 4
.Xr intro 8
.Pp
Tutorials in the
.%T "UNIX User's Manual Supplementary Documents" .
.Sh HISTORY
A
.Nm intro
manual appeared in
.At v6 .
