.\" Copyright (c) 1990 Regents of the University of California.
.\" All rights reserved.  The Berkeley software License Agreement
.\" specifies the terms and conditions for redistribution.
.\"
.\"     @(#)intro.1	6.2 (Berkeley) %G%
.\"
.TH INTRO 1 "April 29, 1985"
.AT 3
.SH NAME
intro \- introduction to commands
.SH DESCRIPTION
This section describes publicly accessible commands in alphabetic order.
Certain distinctions of purpose are made in the headings:
.TP
(1)
Commands of general utility.
.TP
(1C)
Commands for communication with other systems.
.TP
(1G)
Commands used primarily for graphics and computer-aided design.
.PP
N.B.: Commands related to system maintenance used to appear in
section 1 manual pages and were distinguished by (1M) at the top of the
page.  These manual pages now appear in section 8.
.SH SEE ALSO
Section (6) for computer games.
.PP
.I How to get started,
in the Introduction.
.SH DIAGNOSTICS
Upon termination each command returns two bytes of status,
one supplied by the system giving the cause for
termination, and (in the case of `normal' termination)
one supplied by the program, see
.I wait
and
.IR exit (2).
The former byte is 0 for normal termination, the latter
is customarily 0 for successful execution, nonzero
to indicate troubles such as erroneous parameters, bad or inaccessible data,
or other inability to cope with the task at hand.
It is called variously `exit code', `exit status' or
`return code', and is described only where special conventions are involved.
