#	@(#)Makefile	4.6 (Berkeley) %G%

LIB=	ln
SRCS=	allprint.c main.c reject.c yyless.c yywrap.c
LINKS=	${LIBDIR}/libln.a ${LIBDIR}/libl.a \
	${LIBDIR}/libln_p.a ${LIBDIR}/libl_p.a

.include <bsd.lib.mk>
