# $Id: Makefile.inc,v 1.7 1994/05/28 09:56:36 csgr Exp $

CPLUSPLUSLIB=   yes
CXXFLAGS+=-O

# SHLIB major and minor nos. MUST be specified here.
# Do not remove the following 2 lines.
SHLIB_MAJOR=1
SHLIB_MINOR=1

