.\"	@(#)hypot.3	6.1 (Berkeley) 5/15/85
.\"
.TH HYPOT 3M  "May 15, 1985"
.AT 3
.SH NAME
hypot, cabs \- Euclidean distance
.SH SYNOPSIS
.nf
.B #include <math.h>
.PP
.B double hypot(x, y)
.B double x, y;
.PP
.B double cabs(z)
.B struct { double x, y;} z;
.fi
.SH DESCRIPTION
.I Hypot
and
.I cabs
return
.PP
.IP
sqrt(x*x + y*y),
.LP
taking precautions against unwarranted overflows.
.SH SEE ALSO
exp(3M) for
.I sqrt
