#	@(#)Makefile	5.17 (Berkeley) %G%

# BROKEN: adventure dungeon hunt larn warp phantasia 
# NOT INSTALLED: xneko

SUBDIR=	arithmetic atc backgammon battlestar bcd boggle caesar canfield \
	chess ching cribbage dm factor fish fortune hack hangman mille \
	monop morse number pig pom ppt primes quiz rain robots rogue sail \
	snake trek wargames worm worms wump

.include <bsd.subdir.mk>
