.TH PIX 1 4/8/79
.UC
.SH NAME
pix \- Pascal interpreter and executor
.SH SYNOPSIS
.B pix
[
.B \-blnpstuwz
] [
.B \-i
name ...
]
name.p
[
argument ...
]
.SH DESCRIPTION
.I Pix
is a `load and go' version of Pascal which combines
the functions of the interpreter code translator
.I pi
and the executor
.IR px .
It uses
.I pi
to translate the program in the file
.I name.p
and, if there were no fatal errors during translation,
causes the resulting interpreter code
to be executed by
.I px
with the specified arguments.
A temporary file is used for the object code;
the file
.I obj
is neither created nor destroyed.
.SH FILES
.ta 2i
/usr/bin/pi	Pascal translator
.br
/usr/bin/px	Pascal executor
.br
/tmp/pix?????	temporary
.br
/usr/lib/how_pix	basic explanation
.SH SEE\ ALSO
Berkeley Pascal User's Manual
.br
pi(1), px(1)
.SH DIAGNOSTICS
For a basic explanation do
.PP
.DT
.B	pix
.SH AUTHORS
Susan L. Graham and William N. Joy
