#	@(#)Makefile	5.1 (Berkeley) %G%

PROG=	inv
SRCS=	deliv2.c inv1.c inv2.c inv3.c inv5.c inv6.c
CFLAGS+=-I${.CURDIR}/../refer
NOMAN=	noman
.PATH:	${.CURDIR}/../deliv

.include "../../Makefile.inc"
.include <bsd.prog.mk>
