.so tmac.ilib
.TH DEAL 6 "The University of Arizona \- 5/13/83"
.SH NAME
deal \- deal bridge hands
.SH SYNOPSIS
\f3deal\fP [\f3\-h\fI n\fR] [\f3\-s\fI n\fR]
.SH DESCRIPTION
\fIDeal\fR shuffles, deals, and displays hands in the game of bridge.
.PP
The following options may appear in either order:
.IP "\f3\-h\fI n\fR" .75i
Display \fIn\fR hands. The default is 1.
.IP "\f3\-s\fI n\fR"
Set the seed for random generation to \fIn\fR.
The default seed is 0.
.SH NOTE
The letter \*MT\fR is used to represent the 10.
.SH AUTHOR
Ralph E. Griswold
