#	@(#)Makefile	5.1 (Berkeley) 5/31/90

PROG=	uncompact
SRCS=	uncompact.c tree.c
CFLAGS+=-I${.CURDIR}/../common_source
.PATH:	${.CURDIR}/../common_source
NOMAN=	noman

.include "../../Makefile.inc"
.include <bsd.prog.mk>
