.TH NFSTATS 1 "University of Illinois"
.SH NAME
nfstats \- Print statistics about Notesfiles
.SH SYNOPSIS
.B nfstats
[
.B "-s"
]
topic
[ ... ]
.SH DESCRIPTION
.B "Nfstats"
prints usage statistics for notesfiles.
This program takes a list of notesfiles and lists their statistics on
standard output.
If more than one notesfile is specified, an aggregate set of statistics
is also produced.
.PP
Specify
.B "-s" 
to have only this aggregate report printed and the individual reports
suppressed.
.SH BUGS
Notes sent to two sites are counted as ``networked out'' twice.
.PP
Sequencing past an idle notesfile isn't counted as an entry.
This is a mixed blessing.
Not keeping this statistic greatly improves performance.
.SH FILES
.PD 0
.TP 35
/etc/passwd
for the users name
.TP 35
/etc/group
for the users group
.TP 35
/usr/spool/notes
the default notesfile data base
.PD
.SH SEE ALSO
notes(1),
nfcomment(3),
.br
.ul
The Notesfile Reference Manual
.SH AUTHORS
.nf
Ray Essick (uiucdcs!essick, essick%uiuc@csnet-relay.arpa)
Department of Computer Science
University of Illinois at Urbana-Champaign
Urbana, IL
.sp
Rob Kolstad (kolstad@convex.UUCP)
CONVEX Computer Corporation
Richardson, TX
.fi
