#	$Id: Makefile,v 1.6 1994/01/22 20:43:32 guido Exp $
#	From: @(#)Makefile	5.7 (Berkeley) 4/1/91
#

SUBDIR=	atrun bugfiler bootpd comsat elvispreserve fingerd ftpd getNAME \
	getty mail.local makekey pppd rexecd rlogind rpc.rstatd \
	rpc.rusersd rpc.rwalld rshd talkd telnetd tftpd uucpd

# kpasswdd not ported, it is old kerberosIV

.include <bsd.subdir.mk>
