#	$Id: Makefile,v 1.3 1993/08/27 02:13:13 rgrimes Exp $
#	From: @(#)Makefile	5.7 (Berkeley) 4/1/91
#

SUBDIR=	bugfiler comsat crond elvispreserve fingerd ftpd getNAME getty \
	mail.local makekey pppd rexecd rlogind rpc.rstatd rpc.rusersd \
	rpc.rwalld rshd talkd telnetd tftpd uucpd

# kpasswdd not ported, it is old kerberosIV

.include <bsd.subdir.mk>
