.TH INDIR 2 
.SH NAME
indir \- indirect system call
.SH ASSEMBLER
(indir = 0.)
.br
.B sys indir; call
.PP
The system call at the location
.I call
is executed.
Execution resumes after the
.I indir
call.
.PP
The main purpose of
.I indir
is to allow a program to
store arguments in system calls and execute them
out of line in the data segment.
This preserves the purity of the text segment.
.PP
If
.I indir
is executed indirectly,
it is a no-op.
If the instruction at the indirect
location is not a system call,
.I indir
returns error code EINVAL;
see
.IR intro (2).
