.\" Copyright (c) 1985 The Regents of the University of California.
.\" All rights reserved.
.\"
.\" %sccs.include.redist.roff%
.\"
.\"	@(#)yes.1	6.3 (Berkeley) %G%
.\"
.TH YES 1 ""
.UC 4
.SH NAME
yes \- be repetitively affirmative
.SH SYNOPSIS
.B yes
[
.I expletive
]
.SH DESCRIPTION
.I Yes
outputs
.IR expletive ,
or, by default, ``y'', forever.
