.TH POSY 1 "15 Sep 1987"
.\" $Header: /f/osi/pepy/RCS/posy.1,v 7.1 91/02/22 09:35:12 mrose Interim $
.\"
.\"
.\" $Log:	posy.1,v $
.\" Revision 7.1  91/02/22  09:35:12  mrose
.\" Interim 6.8
.\" 
.\" Revision 7.0  89/11/23  22:11:58  mrose
.\" Release 6.0
.\" 
.SH NAME
posy \- PEPY optional structure\-generator (yacc\-based)
.SH SYNOPSIS
.in +.5i
.ti -.5i
.B posy
\%[\-a]
\%[\-d]
\%[\-f]
\%[\-h\fIoption\fP]
\%[\-o\0newmodule.py]
\%[\-s]
\fImodule.py\fR
.in -.5i
.SH DESCRIPTION
The \fIposy\fR program reads a description of a \fIpresentation\fR module and
augments the module for use with \fIpepy\fR\0(1).
It also produces an \*(lq#include\*(rq file containing equivalent
\fIC\fR language structure definitions for the module.
.PP
The `\-a' switch directs \fIposy\fR to augment the #include file with
commentary text.
.PP
Normally, \fIposy\fR ignores all \fIpepy\fR\-style augmentations except the 
\*(lqverbatim\*(rq actions occuring at the very beginning and end of the
module.
The `\-d' switch directs \fIposy\fR to ignore the verbatim actions as well.
.PP
The `\-f' switch directs \fIposy\fR to generate \fIC\fR routines to deallocate
the structures it defines.
These are appended to the augmented module definition
(as a consequence,
use of the `\-f' switch forces use of the `\-d' switch).
.PP
The `\-h' switch enables additional heuristics when \fIposy\fR generates a
\fIC\fR language structure definition.
Option `0' enables the default heuristics.
Enabling any other option also results in enabling option `0'.
Option `1' enables \*(lqclever\*(rq but non\-unique structure naming.
Option `2' enables the generation of arrays rather than linked-lists
whenever possible.
.PP
The `\-o' switch sets the name of the output file.
If this switch is not specified,
the standard output is used
(\fIposy\fR can not derive the name of the output file from the input file
since both should have extension \*(lq.py\*(rq).
.PP
Normally, \fIposy\fR prints the name of each type as it works.
The `\-s' switch disables this behavior.
.SH FILES
.nf
.ta \w'\fImodule\fR-types.h  'u
\fImodule\fR-types.h	\fIC\fR structure defintions from \fImodule\fR
.re
.fi
.SH "SEE ALSO"
pepy(1),
.br
\fIThe ISO Development Environment: User's Manual\fR
.SH AUTHOR
Marshall T. Rose
