.\" $Revision: 1.4 $
.TH CONVDATE 1
.SH NAME
convdate \- convert time/date strings and numbers
.SH SYNOPSIS
.B convdate
[
.B \-c
]
[
.B \-n
]
[
.B \-s
]
.I arg...
.SH DESCRIPTION
.I Convdate
translate the date/time strings specified as arguments on its
command line, outputing the results one to a line.
.PP
If the ``\-s'' flag is used, then each argument is taken as a
date string to be parsed by
.IR parsedate (3)
and is output as a string formatted by
.IR ctime (3).
This is the default.
.PP
If the ``\-n'' flag is used, then each argument is converted the same way
but is output as a
.IR time_t ;
see
.IR time (2).
.PP
If the ``\-c'' flag is used, then each argument is taken to be a
.I time_t
and is output in
.I ctime
format.
.PP
For example,
.RS
.nf
.RI "% " "convdate 'feb 10 10am'"
Sun Feb 10 10:00:00 1991

.RI "% " "convdate 12pm 5/4/90"
Fri Dec 13 00:00:00 1991
Fri May  4 00:00:00 1990

.RI "% " "convdate -n 'feb 10 10am' '12pm 5/4/90'"
666198000
641880000

.RI "% " "convdate -c 666198000"
Sun Feb 10 10:00:00 1991
.fi
.RE
.SH HISTORY
Written by Rich $alz <rsalz@uunet.uu.net>.
.de R$
This is revision \\$3, dated \\$4.
..
.R$ $Id: convdate.1,v 1.4 1993/01/29 16:42:35 rsalz Exp $
.SH "SEE ALSO"
parsedate(3).
