.\" Copyright (c) 1990 The Regents of the University of California.
.\" All rights reserved.
.\"
.\" %sccs.include.redist.man%
.\"
.\"     @(#)passwd.1	6.8 (Berkeley) %G%
.\"
.Dd 
.Dt PASSWD 1
.Os BSD 4
.Sh NAME
.Nm passwd
.Nd modify a user's password
.Sh SYNOPSIS
.Nm passwd
.Op Fl l
.Op Ar user
.Sh DESCRIPTION
.Nm Passwd
changes the user's Kerberos password.  First, the user is prompted for their
current password.
If the current password is correctly typed, a new password is
requested.
The new password must be entered two times to verify any typing errors.
.Pp
The new password should be at least six characters long and not
purely alphabetic.
Its total length must be less than _PASSWORD_LEN (currently 128 characters).
Numbers, upper case letters and meta characters
are encouraged.
.Pp
Once the password has been verified,
.Nm passwd
communicates the new password information to
the Kerberos authenticating host.
.Tp Fl l
This option causes the password to be updated only in the local
password file, and not with the Kerberos database.
When changing only the local password,
.Xr mkpasswd  8
is used to update the user database.  This is run in the background, and,
at very large sites could take several minutes.  Until this update
is completed, the password file is unavailable for other updates
and the new password will not be available to programs.
.Tp
.Pp
To change another user's Kerberos password, one must first
run
.Xr kinit 1
followed by
.Xr passwd 1 .
The super-user is not required to provide a user's current password
if only the local password is modified.
.Sh FILES
.Dw /etc/master.passwd
.Di L
.Dp Pa /etc/master.passwd
the user database
.Dp
.Sh SEE ALSO
.Xr chpass 1 ,
.Xr kerberos 1 ,
.Xr kinit 1 ,
.Xr login 1 ,
.Xr passwd 5 ,
.Xr kpasswdd 8 ,
.Xr mkpasswd 8 ,
.Xr vipw 8
.br
Robert Morris and Ken Thompson,
.Em UNIX password security
.Sh HISTORY
A
.Nm passwd
command appeared in Version 6 AT&T UNIX.
