#define AUTOINDENT      0
#define AUTOPRINT       1
#define AUTOWRITE       2
#define BEAUTIFY        3
#define DIRECTORY       4
#define EDCOMPATIBLE    5
#define ERRORBELLS      6
#define HARDTABS        7
#define IGNORECASE      8
#define LISP            9
#define LIST            10
#define MAGIC           11
#define MAPINPUT        12
#define NUMBER          13
#define OPEN            14
#define OPTIMIZE        15
#define PARAGRAPHS      16
#define PROMPT          17
#define REDRAW          18
#define REPORT          19
#define SCROLL          20
#define SECTIONS        21
#define SHELL           22
#define SHIFTWIDTH      23
#define SHOWMATCH       24
#define SLOWOPEN        25
#define TABSTOP         26
#define TTYTYPE         27
#define TERM            28
#define TERSE           29
#define WARN            30
#define WINDOW          31
#define WRAPSCAN        32
#define WRAPMARGIN      33
#define WRITEANY        34

#define	NOPTS	35
