.\"	@(#)split.1	6.3 (Berkeley) %G%
.\"
.TH SPLIT 1 ""
.AT 3
.SH NAME
split \- split a file into pieces
.SH SYNOPSIS
\fBsplit\fP [ -\fBn\fP ] [ -\fBb\fP byte_cnt ] [ file [ name ] ]
.SH DESCRIPTION
\fISplit\fP reads \fIfile\fP and writes it in
.IR n -line
pieces or in \fIbyte_cnt\fP byte pieces to a set of output
files.  The default is in 1000 line pieces.  The name of the
first output file is \fIname\fP with "aa" appended, and so
on, lexicographically, to "zz".  If no output name is given,
"x" is the default, in which case \fIsplit\fP will create
files from "xaa" to "zzz".
.PP
If no input file is given, or if \fB-\fP is given in its stead, then
the standard input file is used.
.SH BUGS
If you provide \fIname\fP, \fIsplit\fP can only create 676 separate
files.  The default naming convention allows 2028 separate files.
