.TH CAL 1 
.SH NAME
cal \- print calendar
.SH SYNOPSIS
.B cal
[ month ] year
.SH DESCRIPTION
.I Cal
prints a calendar for the specified year.
If a month is also specified, a calendar
just for that month is printed.
.I Year
can be between 1
and 9999.
The
.I month
is a number between 1 and 12.
The calendar
produced is that for England and her colonies.
.PP
Try September 1752.
.SH BUGS
The year is always considered to start in January even though this
is historically naive.
.br
Beware that `cal 78' refers to the early Christian era,
not the 20th century.
