.TH DATE 1 
.SH NAME
date \- print and set the date
.SH SYNOPSIS
.B date
.RB "[ yymmddhhmm [ " . "ss ] ]"
.SH DESCRIPTION
If no argument is given, the current date and time are printed.
If an argument is given, the current date is set.
.I yy
is the last two digits of the year;
the first
.I mm
is the month number;
.I dd
is the day number in the month;
.I hh
is the hour number (24 hour system);
the second
.I mm
is the minute number;
.BI . ss
is optional and is the seconds.
For example:
.IP
date 10080045
.PP
sets the date to Oct 8, 12:45 AM.
The year, month and day may be omitted, the current
values being the defaults.
The system operates in GMT.
.I Date
takes care of the conversion to and from
local standard and daylight time.
.SH FILES
/usr/adm/wtmp to record time-setting
.SH SEE ALSO
utmp(5)
.SH DIAGNOSTICS
`No permission' if
you aren't the super-user and you try to change the date;
`bad conversion' if the date set is syntactically incorrect.
