.TH LN 1 11/16/79
.UC
.SH NAME
ln, lnall \- make links
.SH SYNOPSIS
.B ln
name1 [ name2 ]
.br
.B lnall
name ... directory
.SH DESCRIPTION
A link is a directory entry referring
to a file; the same file (together with
its size, all its protection
information, etc.)
may have several links to it.
There is no way to distinguish a link to a file
from its original directory entry;
any changes in the
file are effective
independently of the name by which the file is known.
.PP
.I Ln
creates a link to an existing file
.IR name1 .
If
.I name2
is given, the link has that name;
.I name2 may also be a directory in which to place the link;
otherwise it is placed in the current directory.
If only the directory is specified, the link will be made with
its name the same as the last component
of
.IR name1 .
.PP
.I Lnall
makes links to all the named files in the named directory.
The links made will have the same name as the files being linked to.
.PP
It is forbidden to link to a directory
or to link across file systems.
.SH "SEE ALSO"
rm(1)
