.TH STTY 1 11/13/79
.UC
.SH NAME
stty \- set terminal options
.SH SYNOPSIS
.B stty
[ option ... ]
.SH DESCRIPTION
.I Stty
sets certain I/O options on the current output terminal.
With no argument, it reports the current settings of the options.
The option strings are
selected from the following set:
.TP  8n
.B even 
allow even parity
.br
.ns
.TP 
.B \-even 
disallow even parity
.br
.ns
.TP 
.B odd 
allow odd parity
.br
.ns
.TP 
.B \-odd 
disallow odd parity
.br
.ns
.TP 
.B raw 
raw mode input
(no erase, kill, interrupt, quit, EOT; parity bit passed back)
.br
.ns
.TP 
.B \-raw 
negate raw mode
.br
.ns
.TP 
.B cooked 
same as `\-raw'
.br
.ns
.TP
.B cbreak
make each character available to
.IR read (2)
as received; no erase and kill
.br
.ns
.TP
.B \-cbreak
make characters available to 
.I read
only when newline is received
.br
.ns
.TP 
.B \-nl 
allow carriage return for new-line,
and output CR-LF for carriage return or new-line
.br
.ns
.TP 
.B nl 
accept only new-line to end lines
.br
.ns
.TP 
.B echo 
echo back every character typed
.br
.ns
.TP 
.B \-echo 
do not echo characters
.br
.ns
.TP 
.B lcase 
map upper case to lower case
.br
.ns
.TP 
.B \-lcase 
do not map case
.br
.ns
.TP 
.B \-tabs 
replace tabs by spaces when printing
.br
.ns
.TP 
.B tabs 
preserve tabs
.br
.ns
.TP 
.B ek 
reset erase and kill characters back to normal # and @
.br
.ns
.TP 
.BI erase \ c\fR
set erase character to
.I c
(default `#'.)
.br
.ns
.TP 
.BI kill \ c\fR
set kill character to
.I c
(default `@'.)
.br
.ns
.TP 
.BI intr \ c\fR
set interrupt character to
.I c
(default DEL.)
.br
.ns
.TP 
.BI quit \ c\fR
set quit character to
.I c
(default control \e.)
.br
.ns
.TP 
.BI start \ c\fR
set start character to
.I c
(default control Q.)
.br
.ns
.TP 
.BI stop \ c\fR
set stop character to
.I c
(default control S.)
.br
.ns
.TP 
.BI eof \ c\fR
set end of file character to
.I c
(default control D.)
.br
.ns
.TP 
.BI brk \ c\fR
set break character to
.I c
(default undefined.)
This character is an extra wakeup causing character.
.br
.ns
.TP
.B  cr0 cr1 cr2 cr3
.br
select style of delay for carriage return (see
.IR ioctl (2))
.br
.ns
.TP
.B  nl0 nl1 nl2 nl3
.br
select style of delay for linefeed 
.br
.ns
.TP
.B  tab0 tab1 tab2 tab3
.br
select style of delay for tab 
.br
.ns
.TP
.B  ff0 ff1
select style of delay for form feed 
.br
.ns
.TP
.B bs0 bs1
select style of delay for backspace
.br
.ns
.TP 
.B tty33 
set all modes suitable for the
Teletype Corporation Model 33 terminal.
.br
.ns
.TP 
.B tty37 
set all modes suitable for the
Teletype Corporation Model 37 terminal.
.br
.ns
.TP 
.B vt05 
set all modes suitable for Digital Equipment Corp. VT05 terminal
.br
.ns
.TP 
.B tn300 
set all modes suitable for a General Electric TermiNet 300
.br
.ns
.TP 
.B ti700 
set all modes suitable for Texas Instruments 700 series terminal
.br
.ns
.TP 
.B tek 
set all modes suitable for Tektronix 4014 terminal
.br
.ns
.TP 
.B hup 
hang up dataphone on last close.
.br
.ns
.TP 
.B \-hup 
do not hang up dataphone on last close.
.br
.ns
.TP 
.B 0 
hang up phone line immediately
.br
.ns
.TP
.B  "50 75 110 134 150 200 300 600 1200 1800 2400 4800 9600 exta extb"
.br
Set terminal baud rate to the number given, if possible.
(These are the speeds supported by the DH-11 interface).
.dt
.SH "SEE ALSO"
ioctl(2), tabs(1), tset(1), stty(1)
