.TH UL 1 9/23/79
.UC
.SH NAME
ul \- do underlining
.SH SYNOPSIS
.B ul
[
.B \-t
.I terminal
]
[
.I name
\&...
]
.SH DESCRIPTION
.I Ul
reads the named files (or standard input if none are given)
and translates occurances of underscores to the sequence
which indicates underlining.
If
.B \-t
is present,
.I terminal
is used as the terminal kind.
Otherwise, the environment is looked in and
.I /etc/termcap
read to determine
the appropriate sequences for underlining.
If none of the fields
.BR us ,
.BR ue ,
or
.BR uc
is present, and if
.B so
and
.B se
are present, standout mode is used to indicate underlining.
If the terminal can overstrike,
or handles underlining automatically,
.I ul
behaves like
.IR cat (1).
If the terminal cannot underline, underlining is ignored.
.SH "SEE ALSO"
iul(1), man(1), nroff(1)
.SH AUTHOR
Mark Horton
.SH BUGS
.I Nroff
usually outputs a series of backspaces and underlines intermixed
with the text to indicate underlining.  No attempt is made to optimize
the backward motion.
