.\" Copyright (c) 1980 Regents of the University of California.
.\" All rights reserved.  The Berkeley software License Agreement
.\" specifies the terms and conditions for redistribution.
.\"
.\"	@(#)uptime.1	6.2 (Berkeley) %G%
.\"
.TH UPTIME 1 ""
.UC
.SH NAME
uptime \- show how long system has been up
.SH SYNOPSIS
.B uptime
.SH DESCRIPTION
Uptime prints the current time, the length of time the system has been up,
and the average number of jobs in the run queue over the last 1, 5 and
15 minutes.
It is, essentially, the first line of a
.IR w (1)
command.
.SH FILES
/vmunix	system name list
.SH SEE ALSO
w(1)
