.\" Copyright (c) 1991, 1993
.\"	The Regents of the University of California.  All rights reserved.
.\"
.\" %sccs.include.redist.man%
.\"
.\"     @(#)asin.3	8.1 (Berkeley) %G%
.\"
.Dd 
.Dt ASIN 3
.Os
.Sh NAME
.Nm asin
.Nd arc sine function
.Sh SYNOPSIS
.Fd #include <math.h>
.Ft double
.Fn asin "double  x"
.Sh DESCRIPTION
The
.Fn asin
function computes the principal value of the arc sine of
.Fa x .
A domain error occurs for arguments not in the range [-1, +1].
For a discussion of error due to roundoff, see
.Xr math 3 .
.Sh RETURN VALUES
The
.Fn asin
function returns the arc sine in the range
.Bk -words
.Bq -\*(Pi/2, +\*(Pi/2
.Ek
radians.
On the
.Tn VAX ,
and Tahoe ,
if:
.Bd -unfilled -offset indent
.Pf \&| Ns Ar x Ns \&| > 1
.Ed
.Pp
the
global variable
.Va errno
is set to
.Er EDOM
and
a reserved operand fault generated.
.Sh SEE ALSO
.Xr acos 3 ,
.Xr atan 3 ,
.Xr atan2 3 ,
.Xr cos 3 ,
.Xr cosh 3 ,
.Xr sin 3 ,
.Xr sinh 3 ,
.Xr tan 3 ,
.Xr tanh 3 ,
.Xr math 3 ,
.Sh STANDARDS
The
.Fn asin
function conforms to
.St -ansiC .
