.TH SIN 3M  "8 May 1985"
.UC 4
.SH NAME
sin, cos, tan, asin, acos, atan, atan2 \- trigonometric functions
.SH SYNOPSIS
.nf
.B #include <math.h>
.PP
.B double sin(x)
.B double x;
.PP
.B double cos(x)
.B double x;
.PP
.B double tan(x)
.B double x;
.PP
.B double asin(x)
.B double x;
.PP
.B double acos(x)
.B double x;
.PP
.B double atan(x)
.B double x;
.PP
.B double atan2(y, x)
.B double y, x;
.fi
.SH DESCRIPTION
.I Sin, cos
and
.I tan
return trigonometric functions of radian arguments.
.PP
.I Asin
returns the arc sin in the range \-\(*p/2 to \(*p/2.
.PP
.I Acos
returns the arc cosine in the range 0 to \(*p.
.PP
.I Atan
returns the arc tangent of
.I x
in the range \-\(*p/2 to \(*p/2.
.PP
.I Atan2
returns
.I atan(y/x)
if
.I x
> 0,
.br
.I sign(y)*(\(*p \- atan(|y/x|))
if
.I x
< 0,
.br
.I zero
if
.I x
= 
.I y
= 0 and
.br
.I sign(y)*\(*p/2
if
.I x
= 0 but
.I y
not equal to 0.
.SH SEE ALSO
intro(3M)
.SH DIAGNOSTICS
Arguments of magnitude greater than 1 cause
.I asin
and
.I acos
to return the reserved operand on the VAX;
.I errno
is set to EDOM.
.SH AUTHOR
Robert P. Corbett, W. Kahan, Stuart McDonald, Kwok-Choi Ng
