.TH SINH 3M "8 May 1985"
.UC 4
.SH NAME
sinh, cosh, tanh \- hyperbolic functions
.SH SYNOPSIS
.nf
.B #include <math.h>
.PP
.B double sinh(x)
.B double x;
.PP
.B double cosh(x)
.B double x;
.PP
.B double tanh(x)
.B double x;
.fi
.SH DESCRIPTION
These functions compute the designated hyperbolic functions for real arguments.
.SH SEE ALSO
intro(3M)
.SH DIAGNOSTICS
.I Sinh
and
.I cosh
return the reserved operand on the VAX if the correct value would overflow.
.SH AUTHOR
W. Kahan, Kwok-Choi Ng
