.\" Copyright (c) 1987 The Regents of the University of California.
.\" All rights reserved.
.\"
.\" %sccs.include.redist.roff%
.\"
.\"	@(#)wall.1	6.4 (Berkeley) %G%
.\"
.UC 7
.TH WALL 1 ""
.UC 4
.SH NAME
wall \- write a message to users
.SH SYNOPSIS
.B wall
[ file ]
.SH DESCRIPTION
.I Wall
displays the contents of
.I file
or, by default, its standard input, on the terminals of all
currently logged in users.
.PP
Appropriate permissions are often required to override protections
user's place on their terminals.
.SH "SEE ALSO"
mesg(1), talk(1), write(1), shutdown(8)
