.TH XTREK 6 "1 December 1986" "X Version 10"
.SH NAME
xtrek - Multiplayer startrek game for X window system
.SH SYNOPSIS
.B xfax
[ options ] [ \fIhost\fP:\fInumber\fP ] file
.SH DESCRIPTION
.I Xtrek
.PP
is an addictive multiplayer star trek game.
The program "/usr/games/daemon" must already be running on the
machine which is supporting the game.
The argument to \fIxtrek\fP specifies which display to display the
game on.
.PP
See the \fIxtrek\fP document for a detailed explanation of how to run the
game.
.SH BUGS
Requires System V shared memory.  All parts of the game must run on a
single machine, though display can be anywhere.
.SH AUTHOR
Chris Guthrie (chris@ic.berkeley.edu) is guilty of this version.
.SH "SEE ALSO"
X(1), xtrek/doc
