.\" Copyright (c) 1989 The Regents of the University of California.
.\" All rights reserved.
.\"
.\" %sccs.include.redist.man%
.\"
.\"	@(#)caesar.6	5.2 (Berkeley) %G%
.\"
.TH CAESAR 6 ""
.UC 7
.SH NAME
caesar \- decrypt caesar cyphers
.SH SYNOPSIS
.B caesar
[
.B rotation
]
.SH DESCRIPTION
The
.I caesar
utility attempts to decrypt caesar cyphers using letter frequency
statistics.
.I Caesar
reads from the standard input and writes to the standard output.
.PP
The optional numerical argument
.I rotation
may be used to specify a specific rotation value.
For example,
.B "caesar 13"
may be used to decrypt rotated postings to USENET
as well as some of the databases used with the
.I fortune
program.
