.TH ROSY 1 "07 Sep 1987"
.\" $Header: /f/osi/rosy/RCS/rosy.1,v 7.2 91/02/22 09:41:46 mrose Interim $
.\"
.\"
.\" $Log:	rosy.1,v $
.\" Revision 7.2  91/02/22  09:41:46  mrose
.\" Interim 6.8
.\" 
.\" Revision 7.1  90/07/01  21:06:19  mrose
.\" pepsy
.\" 
.\" Revision 7.0  89/11/23  22:21:50  mrose
.\" Release 6.0
.\" 
.SH NAME
rosy \- RO stub\-generator (yacc\-based)
.SH SYNOPSIS
.in +.5i
.ti -.5i
.B rosy
\%[\-defs]
\%[\-pepsy]
\%[\-b\0prefix]
\%[\-d]
\%[\-o\0module.py]
\%[\-s]
\%[-T\0tablename]
\%[-O\0operationlist]
\fImodule.ry\fR
.in -.5i
.SH DESCRIPTION
The \fIrosy\fR program reads a description of a \fIremote operations\fR
module and produces \fIC\fR routines and definitions suitable for use with
the \fIlibrosy\fR\0(3n) library.
.PP
The `\-pepsy' switch tells \fIrosy\fR that it's output will be
processed by \fIpepsy\fR not \fIposy\fR.
.PP
The `\-defs' switch tells \fIrosy\fR to provide function names for \fIpepsy\fR.
.PP
The `\-b' switch sets the prefix used for the output file.
If this option is not given,
the ASN.1 module name is used.
.PP
The `\-d' switch directs \fIrosy\fR to ignore most \fIpepy\fR\-style
augmentations.
.PP
The `\-o' switch sets the name of the output file,
which is normally derived from the name of the input file.
The distinguished file \*(lq\-\*(rq can be used to force the use of the
standard output.
.PP
Normally, \fIrosy\fR prints the name of each operation, error, or type
as it works.
The `\-s' switch disables this behavior.
.PP
It is sometimes useful to produce subsets of the full lists of the
operations to reduce code sizes. The following switches can be used
together with the `\-o' switch to achieve this affect.
.PP
The `\-T' option specifies a different table name to be used. This is
used to build a separate list of operations - usually a subset of the
full list.
.PP
The `\-O' option takes a comma separated list of operation names. If
this argument is present, only those operations listed here will be
processed. All other operations will be ignored and will not be placed
in the table. Currently all errors are output however.
.SH FILES
.nf
.ta \w'\fIprefix\fR-stubs.c  'u
\fIprefix\fR-ops.h	operation definitions
\fIprefix\fR-ops.c	operation tables
\fIprefix\fR-stubs.c	operation stubs
.re
.fi
.SH "SEE ALSO"
pepsy(1), pepy(1),
.br
\fIThe ISO Development Environment: User's Manual\fR,
.br
ISO DIS 9072/1:
\fIInformation Processing \-\- Text Communication \-\- MOTIS \-\- Remote
Operations Part 1: Model, Notation and Service Definition\fR,
.br
CCITT Draft Recommendation X.410:
\fIRemote Operations: Model, Notation and Service Definition\fR,
.br
ECMA Technical Report 31:
\fIRemote Operations: Concepts, Notation and Connection\-Oriented Mappings\fR,
.br
CCITT Recommendation X.410:
\fIMessage Handling Systems:
Remote Operations and Reliable Transfer Server\fR
.SH AUTHORS
Julian P. Onions,
Nottingham University
.br
Marshall T. Rose
.SH BUGS
The \fBBIND\fR and \fBUNBIND\fR macros are currently unrecognized,
along with the newer (\fBOBJECT\fR \fBIDENTIFIER\fR) notation for operation
codes.
.PP
The \fBLINKED\fR clause is currently unrecognized for the \fBOPERATION\fR
macro.
