# include	"scanner.h"
# include	<sccs.h>

SCCSID(@(#)s_cmap.c	7.1	2/5/81)


/* CHARACTER TYPE MAP */
char	Cmap[] =
{
	CNTRL, CNTRL, CNTRL, CNTRL, CNTRL, CNTRL, CNTRL, CNTRL,
	CNTRL, PUNCT, PUNCT, CNTRL, CNTRL, PUNCT, CNTRL, CNTRL,
	CNTRL, CNTRL, CNTRL, CNTRL, CNTRL, CNTRL, CNTRL, CNTRL,
	CNTRL, CNTRL, CNTRL, CNTRL, CNTRL, CNTRL, CNTRL, CNTRL,
	PUNCT, OPATR, OPATR, OPATR, OPATR, OPATR, OPATR, OPATR,
	OPATR, OPATR, OPATR, OPATR, OPATR, OPATR, OPATR, OPATR,
	NUMBR, NUMBR, NUMBR, NUMBR, NUMBR, NUMBR, NUMBR, NUMBR,
	NUMBR, NUMBR, OPATR, OPATR, OPATR, OPATR, OPATR, OPATR,
	OPATR, ALPHA, ALPHA, ALPHA, ALPHA, ALPHA, ALPHA, ALPHA,
	ALPHA, ALPHA, ALPHA, ALPHA, ALPHA, ALPHA, ALPHA, ALPHA,
	ALPHA, ALPHA, ALPHA, ALPHA, ALPHA, ALPHA, ALPHA, ALPHA,
	ALPHA, ALPHA, ALPHA, OPATR, OPATR, OPATR, OPATR, ALPHA,
	OPATR, ALPHA, ALPHA, ALPHA, ALPHA, ALPHA, ALPHA, ALPHA,
	ALPHA, ALPHA, ALPHA, ALPHA, ALPHA, ALPHA, ALPHA, ALPHA,
	ALPHA, ALPHA, ALPHA, ALPHA, ALPHA, ALPHA, ALPHA, ALPHA,
	ALPHA, ALPHA, ALPHA, OPATR, OPATR, OPATR, OPATR, OPATR,
	0
};
