.\" Copyright (c) 1983, 1990 The Regents of the University of California.
.\" All rights reserved.
.\"
.\" Redistribution and use in source and binary forms are permitted provided
.\" that: (1) source distributions retain this entire copyright notice and
.\" comment, and (2) distributions including binaries display the following
.\" acknowledgement:  ``This product includes software developed by the
.\" University of California, Berkeley and its contributors'' in the
.\" documentation or other materials provided with the distribution and in
.\" all advertising materials mentioning features or use of this software.
.\" Neither the name of the University nor the names of its contributors may
.\" be used to endorse or promote products derived from this software without
.\" specific prior written permission.
.\" THIS SOFTWARE IS PROVIDED ``AS IS'' AND WITHOUT ANY EXPRESS OR IMPLIED
.\" WARRANTIES, INCLUDING, WITHOUT LIMITATION, THE IMPLIED WARRANTIES OF
.\" MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE.
.\"
.\"     @(#)rsh.1	6.8 (Berkeley) 7/24/90
.\"
.Dd July 24, 1990
.Dt RSH 1
.Os BSD 4.2
.Sh NAME
.Nm rsh
.Nd remote shell
.Sh SYNOPSIS
.Ar rsh
.Op Fl Kdnx
.Op Fl k Ar realm
.Op Fl l Ar username
.Ar host
.Op command
.Sh DESCRIPTION
.Nm Rsh
executes
.Ar command
on
.Ar host  .
.Pp
.Nm Rsh
copies its standard input to the remote command, the standard
output of the remote command to its standard output, and the
standard error of the remote command to its standard error.
Interrupt, quit and terminate signals are propagated to the remote
command;
.Nm rsh
normally terminates when the remote command does.
The options are as follows:
.Tp Fl K
The
.Fl K
option turns off all Kerberos authentication.
.Tp Fl d
The
.Fl d
option turns on socket debugging (using
.Xr setsockopt  2  )
on the TCP sockets used for communication with the remote host.
.Tp Fl k
The
.Fl k
option causes
.Nm rsh
to obtain tickets for the remote host in
.Ar realm
instead of the remote host's realm as determined by
.Xr krb_realmofhost  3  .
.Tp Fl l
By default, the remote username is the same as the local username.
The
.Fl l
option allows the remote name to be specified.
Kerberos authentication is used, and authorization is determined
as in
.Xr rlogin  1  .
.Tp Fl n
The
.Fl n
option redirects input from the special device
.Pa /dev/null
(see the BUGS section of this manual page).
.Tp Fl x
The
.Fl x
option turns on DES encryption for all data exchange.
This may introduce a significant delay in response time.
.Tp
.Pp
If no
.Ar command
is specified, you will be logged in on the remote host using
.Xr rlogin  1  .
.Pp
Shell metacharacters which are not quoted are interpreted on local machine,
while quoted metacharacters are interpreted on the remote machine.
For example, the command
.Pp
.Dl rsh otherhost cat remotefile >> localfile
.Pp
appends the remote file
.Ar remotefile
to the local file
.Ar localfile ,
while
.Pp
.Dl rsh otherhost cat remotefile \&">>\&" other_remotefile
.Pp
appends
.Ar remotefile
to
.Ar other_remotefile .
.\" .Pp
.\" Many sites specify a large number of host names as commands in the
.\" directory /usr/hosts.
.\" If this directory is included in your search path, you can use the
.\" shorthand ``host command'' for the longer form ``rsh host command''.
.Sh FILES
.Dw /etc/hosts
.Di L
.Dp Pa /etc/hosts
.Dp
.Sh SEE ALSO
.Xr rlogin 1 ,
.Xr kerberos 3 ,
.Xr krb_sendauth 3 ,
.Xr krb_realmofhost 3
.Sh HISTORY
.Nm Rsh
appeared in 4.2 BSD
.Sh BUGS
If you are using
.Xr csh  1
and put a
.Nm rsh
in the background without redirecting its input away from the terminal,
it will block even if no reads are posted by the remote command.
If no input is desired you should redirect the input of
.Nm rsh
to
.Pa /dev/null
using the
.Fl n
option.
.Pp
You cannot run an interactive command
(like
.Xr rogue  6
or
.Xr vi  1  )
using
.Nm rsh  ;
use
.Xr rlogin  1
instead.
.Pp
Stop signals stop the local
.Nm rsh
process only; this is arguably wrong, but currently hard to fix for reasons
too complicated to explain here.
