#
#       @(#)tests.init	1.4 90/01/09 NFS Rev 2 testsuite
#
MNTOPTIONS="rw,hard,intr"
MNTPOINT="/mnt"
MOUNT="./domount"
UMOUNT="./domount -u"
PATH="/bin:/usr/bin:/usr/ucb:/etc:/usr/etc:.:$PATH"
SERVER=""
SERVPATH="/server"
TESTS="-a"
TESTARG="-f"

# -----------------------------------------------
#  Defines for various variables used in scripts

#  Define NFS3_2 for Sun NFS 3.2 compatibility
# COMPAT = -DNFS3_2

# Use with Sys V Release 3 systems.
# SYSTYPE=-DSVR3
# LIBS=-lrpc
# COMPAT = -DSVR3 
# UTS=-TR2

# Use with BSD systems.
SYSTYPE=
LIBS=
COMPAT=
UTS=
# -----------------------------------------------

export PATH SYSTYPE LIBS COMPAT UTS
