.\" Copyright (c) 1991, 1991 Regents of the University of California.
.\" All rights reserved.
.\"
.\" %sccs.include.redist.roff%
.\"
.\"	@(#)mprotect.2	8.1 (Berkeley) %G%
.\"
.Dd 
.Dt MPROTECT 2
.Os
.Sh NAME
.Nm mprotect
.Nd control the protection of pages
.Sh SYNOPSIS
.Fn mprotect "caddr_t addr" "int len" "int prot"
.Sh DESCRIPTION
The
.Fn mprotect
system call
changes the specified pages to have protection
.Fa prot .
Not all implementations will guarantee protection on a page basis;
the granularity of protection changes may be as large as an entire region.
.Sh SEE ALSO
.Xr msync 2 ,
.Xr munmap 2 ,
.Xr madvise 2 ,
.Xr mincore 2
.Sh HISTORY
The
.Fn mprotect
function call is
.Ud .
