.\" (c) Copyright 1986 Xerox Corporation
.\" All rights reserved.
.TH MAKEXTDEV 1 1/15/86
.CM 2
.SH "NAME"
makextdev \- create tables to allow iptroff to access 16 bit characters
.SH "SYNOPSIS"
.B makextdev
file
.SH "DESCRIPTION"
.I makextdev
creates extended tables for use with
.I iptroff
so that full 16 bit characters can be addressed.
.PP
The Xerox Character Encoding Standard specifies a character set of 65K
characters.  Typesetter-Independent
.I troff
only uses 8 bit characters in its internal representation.  Therefore,
the postprocessor
.I dipress
must be able to map from 8 bit characters to 16 bit characters.  The
work-around is based on the fact that
.I makedev
will ignore any text beyond the fourth data field in a font description file.
If the typesetting code (the fourth field) is octal 0377 then
.I makextdev
expects a fifth field which contains the octal code 
for the true 16 bit character.
.PP
This program uses information created by
.I makedev
and thus must be run after
.I makedev .
.SH "FILES"
.ta \w'$LIB/fonts/*  'u
DESC	fonts
.br
*.out	mapping files
.DT
.SH "SEE ALSO"
The Interpress Toolkit manual,
.br
dipress(1),
.br
ipmetrics(1),
.br
makedev(1),
.br
troff(1)
.SH "BUGS"
