#	@(#)Makefile	5.3 (Berkeley) %G%

PROG=	mkey
SRCS=	deliv2.c mkey1.c mkey2.c mkey3.c
CFLAGS+=-I${.CURDIR}/../refer
BINDIR=	/usr/old/libexec
NOMAN=	noman
.PATH:	${.CURDIR}/../deliv

.include <bsd.prog.mk>
