#	@(#)Makefile	5.8.1.1 (Berkeley) 5/8/91

SUBDIR=	ar biff basename cal calendar \
	checknr chpass cksum cmp col colcrt colrm column comm compress \
	cpio ctags cut dirname du env \
	expand false find finger fmt fold from ftp \
	g++ gas gcc gdb groff groups head hexdump id \
	ktrace last ld leave lex locate lock logger \
	login logname m4 machine mail make man mesg mkdep mkfifo \
	mkstr more nfsstat nice nm nohup pagesize \
	passwd paste printenv printf ranlib \
	rdist renice rlogin rsh script \
	shar showmount size soelim split strings \
	strip su symorder talk tee telnet tftp time \
	tip tn3270 touch tput tr true tsort tty ul unexpand unifdef uniq \
	unvis users uudecode uuencode vacation vis \
	wall wc what whereis which who whoami whois \
	write xargs xinstall xstr yacc yes

.include <bsd.subdir.mk>
