/* vi: set tabstop=4 : */

/*
 * Configuration
 */

#define BSD42			1	/* BSD 4.[23] */
/* #define ATARI			1	/* Atari ST */
/* #define SYSV				1	/* System V */

/*
 * If you don't have random() and srandom() #define what you have
 */
/* #define random			lrand48	/* Sys V */
/* #define srandom			srand48	/* Sys V */

/* #define random			rand	/* Not good but generally available */
/* #define srandom(x)		srand((int) x)	/* */

#define TIMER			1	/* Use tty polling (see timer.c) */
#define LOADDICT		1	/* Load the dictionary for speed */

/*
 * Locations for the dictionary (generated by mkdict), index (generated by
 * mkindex), and helpfile
 */
#define DICT			"/grads/brachman/lib/bog/dict"
#define DICTINDEX		"/grads/brachman/lib/bog/dictindex"
#define HELPFILE		"/grads/brachman/lib/bog/helpfile"

/*
 * The theoretical maximum for MAXWORDLEN is ('a' - 1) == 96
 */
#define MAXWORDLEN		40		/* Maximum word length */
#define MAXPWORDS		200		/* Maximum number of player's words */
#define MAXMWORDS		200		/* Maximum number of machine's words */
#define MAXPSPACE		2000	/* Space for player's words */
#define MAXMSPACE		4000	/* Space for machines's words */

#define MAXCOLS			20

/*
 * The following determine the screen layout
 */
#define PROMPT_COL		20
#define PROMPT_LINE		2

#define BOARD_COL		0
#define BOARD_LINE		0

#define SCORE_COL		20
#define SCORE_LINE		0

#define LIST_COL		0
#define LIST_LINE		10

#define TIMER_COL		20
#define TIMER_LINE		2

/*
 * Internal dictionary index
 * Initialized from the file created by mkindex
 */
struct dictindex {
    long start;
	long length;
};

