#	@(#)Makefile	5.2 (Berkeley) 6/29/90

PROG=	style3
CFLAGS+=-I${.CURDIR} -I${.CURDIR}/../style1
SRCS=	part.c pscan.c outp.c
CLEANFILES=part.c
NOMAN=	noman
BINDIR=	/usr/libexec

.include <bsd.prog.mk>
