CONFIG=	up2rp
#
#	%M%		%I%	%G%
#
# Makefile for Berkeley Virtual Vax/Unix, November 1980
#
# -DUCB		for UCB mods: suid bit dropping and monitoring, ...
# -DERNIE	for mods specific to development site
# -DPGINPROF	gather statistics about pagein/pageout activity
# -DDISKMON	monitor disk cacheing activity (bio.c)
# -DFASTVAX	compile in special mods for speed on VAX
# -DINTRLVE	compile in code for file systems interleaved across drives
# -DKPROF	count clock ticks in system in ``kcount'' (sloppy profiling)
# -DTRACE	compile in trace() routine and buffer
#
IDENT=	-DUCB -DERNIE

COPTS=	${IDENT} -DVAX -DFASTVAX -DKERNEL
CFLAGS=	-O ${COPTS}
AHEADS=	../h/mtpr.m ../h/trap.m ../h/psl.m ../h/pcb.m ../h/clock.m \
	../h/cons.m ../h/page.m ../h/mba.m ../h/uba.m ../h/cmap.m \
	../h/proc.m ../h/vm.m

FILES=	locore.o acct.o alloc.o clock.o fio.o iget.o ioctl.o \
	machdep.o main.o malloc.o nami.o partab.o pipe.o prf.o prim.o \
	rdwri.o sig.o slp.o subr.o swtch.o sys.o \
	sys1.o sys2.o sys3.o sys4.o sysent.o \
	text.o trap.o vmdrum.o vmmem.o vmmon.o vmpage.o \
	vmproc.o vmpt.o vmsched.o vmsubr.o vmswap.o vmsys.o

FILES2= ../conf/univec.o ../conf/udiv.o ../conf/urem.o

FILES3=	../dev/bio.o ../dev/bk.o ../dev/cons.o ../dev/dh.o ../dev/dhfdm.o \
	../dev/dkleave.o ../dev/dsort.o ../dev/dz.o ../dev/flp.o \
	../dev/hp.o ../dev/ht.o ../dev/mba.o ../dev/mem.o \
	../dev/mx1.o ../dev/mx2.o ../dev/sw.o ../dev/tdump.o \
	../dev/tty.o ../dev/ttynew.o ../dev/ttyold.o ../dev/uba.o ../dev/up.o \
	../dev/va.o ../dev/vp.o

CFILES=	acct.c alloc.c clock.c fio.c iget.c ioctl.c \
	machdep.c main.c malloc.c nami.c partab.c pipe.c prf.c prim.c \
	rdwri.c sig.c slp.c subr.c swtch.c sys.c \
	sys1.c sys2.c sys3.c sys4.c sysent.c \
	text.c trap.c vmdrum.c vmmem.c vmmon.c vmpage.c \
	vmproc.c vmpt.c vmsched.c vmsubr.c vmswap.c vmsys.c

CFILES3=../dev/bio.c ../dev/bk.c ../dev/cons.c ../dev/dh.c ../dev/dhfdm.c \
	../dev/dkleave.c ../dev/dsort.c ../dev/dz.c ../dev/flp.c \
	../dev/hp.c ../dev/ht.c ../dev/mba.c ../dev/mem.c \
	../dev/mx1.c ../dev/mx2.c ../dev/sw.c ../dev/tdump.c \
	../dev/tty.c ../dev/ttynew.c ../dev/ttyold.c ../dev/uba.c ../dev/up.c \
	../dev/va.c ../dev/vp.c

vmunix: ${FILES}
	@cd ../conf; make
	@cd ../dev; make
	@echo loading...
	@ld -n -o vmunix -e start -x -T 80000000 ${FILES} ${FILES2} ${FILES3} \
	    ../conf/conf${CONFIG}.o
	@echo rearranging symbols...
	@-symorder ../conf/symbols.sort vmunix
	size vmunix
	@chmod 755 vmunix
	ls -l vmunix

allvmunix: ${FILES}
	@cd ../conf; make
	@cd ../dev; make
	@echo loading hpvmunix..
	@ld -n -o hpvmunix -e start -x -T 80000000 ${FILES} ${FILES2} ${FILES3} \
	    ../conf/confrp.o
	@echo loading upvmunix...
	@ld -n -o upvmunix -e start -x -T 80000000 ${FILES} ${FILES2} ${FILES3} \
	    ../conf/confup.o
	@echo loading up2rpvmunix...
	@ld -n -o up2rpvmunix -e start -x -T 80000000 ${FILES} ${FILES2} ${FILES3} \
	    ../conf/confup2rp.o
	@echo rearranging symbols...
	@-/usr/ucb/symorder ../conf/symbols.sort hpvmunix
	@-/usr/ucb/symorder ../conf/symbols.sort upvmunix
	@-/usr/ucb/symorder ../conf/symbols.sort up2rpvmunix
	size hpvmunix upvmunix up2rpvmunix
	@chmod 755 hpvmunix upvmunix up2rpvmunix
	ls -l hpvmunix upvmunix up2rpvmunix

.c.o:
	cc -c -S ${COPTS} $*.c
	/lib/c2 $*.s | sed -f asm.sed | as -o $*.o
	rm $*.s

clean:
	rm -f eddep *vmunix* tags *.o

lint: /tmp
	@lint -hbxn ${COPTS} ${IDENT} Locore.c ${CFILES} \
	    ../conf/conf${CONFIG}.c ../conf/univec.c ${CFILES3} | \
	    grep -v 'struct/union .* never defined' | \
	    grep -v 'possible pointer alignment problem'

locore.o: ${AHEADS}
	@echo as -o locore.o $${AHEADS} locore.s
	@as -o locore.o ${AHEADS} locore.s

depend:
	grep '^#include' ${CFILES} \
		| sed 's/:[^"]*"\([^"]*\)".*/: \1/' \
		| sed 's/\.c/.o/' >makedep
	echo '/^# DO NOT DELETE THIS LINE/+2,$$d' >eddep
	echo '$$r makedep' >>eddep
	echo 'w' >>eddep
	cp makefile makefile.bak
	ed - makefile < eddep
	rm eddep makedep
	echo '# DEPENDENCIES MUST END AT END OF FILE' >> makefile
	echo '# IF YOU PUT STUFF HERE IT WILL GO AWAY' >> makefile
	echo '# see make depend above' >> makefile

tags:
	/usr/ucb/ctags ${CFILES} ${CFILES2} ${CFILES3}
	rm -f ../dev/tags ../conf/tags
	ln tags ../conf
	ln tags ../dev

print:
	@pr -l84 makefile TODO linterrs
	@/usr/ucb/cxref ${CFILES} ${CFILES2} ${CFILES3} | pr -l84 -h XREF
	@(size vmunix *.o) | pr -l84 -h sizes
	@ls -ls | pr -l84
	@cd ../h; ls -ls | pr -l84 ; pr -l84 *.m *.h
	@pr -l84 asm.sed Locore.c locore.s ${CFILES} ${CFILES2} ${CFILES3}

../h/param.h: /usr/include/signal.h
../h/tty.h: /usr/include/sgtty.h
../h/tty.h: ../h/ioctl.h
../h/user.h: ../h/pcb.h ../h/dmap.h ../h/vtimes.h /usr/include/errno.h
../h/vm.h: ../h/vmclust.h ../h/vmklust.h ../h/vmmac.h ../h/vmmeter.h \
    ../h/vmparam.h ../h/vmsystm.h ../h/vmtotal.h ../h/vmtune.h
sysent.c: vmsysent.c

# DO NOT DELETE THIS LINE -- make depend uses it

acct.o: ../h/param.h
acct.o: ../h/systm.h
acct.o: ../h/acct.h
acct.o: ../h/dir.h
acct.o: ../h/user.h
acct.o: ../h/inode.h
acct.o: ../h/proc.h
acct.o: ../h/seg.h
alloc.o: ../h/param.h
alloc.o: ../h/systm.h
alloc.o: ../h/mount.h
alloc.o: ../h/filsys.h
alloc.o: ../h/fblk.h
alloc.o: ../h/conf.h
alloc.o: ../h/buf.h
alloc.o: ../h/inode.h
alloc.o: ../h/ino.h
alloc.o: ../h/dir.h
alloc.o: ../h/user.h
clock.o: ../h/param.h
clock.o: ../h/systm.h
clock.o: ../h/dk.h
clock.o: ../h/callo.h
clock.o: ../h/seg.h
clock.o: ../h/dir.h
clock.o: ../h/user.h
clock.o: ../h/proc.h
clock.o: ../h/reg.h
clock.o: ../h/psl.h
clock.o: ../h/vm.h
clock.o: ../h/buf.h
clock.o: ../h/text.h
clock.o: ../h/vlimit.h
clock.o: ../h/mtpr.h
clock.o: ../h/clock.h
clock.o: ../conf/dh.h
clock.o: ../conf/dz.h
fio.o: ../h/param.h
fio.o: ../h/systm.h
fio.o: ../h/dir.h
fio.o: ../h/user.h
fio.o: ../h/filsys.h
fio.o: ../h/file.h
fio.o: ../h/conf.h
fio.o: ../h/inode.h
fio.o: ../h/reg.h
fio.o: ../h/acct.h
iget.o: ../h/param.h
iget.o: ../h/systm.h
iget.o: ../h/mount.h
iget.o: ../h/dir.h
iget.o: ../h/user.h
iget.o: ../h/inode.h
iget.o: ../h/ino.h
iget.o: ../h/filsys.h
iget.o: ../h/conf.h
iget.o: ../h/buf.h
iget.o: ../h/inline.h
ioctl.o: ../h/param.h
ioctl.o: ../h/systm.h
ioctl.o: ../h/dir.h
ioctl.o: ../h/user.h
ioctl.o: ../h/tty.h
ioctl.o: ../h/proc.h
ioctl.o: ../h/inode.h
ioctl.o: ../h/file.h
ioctl.o: ../h/conf.h
machdep.o: ../h/param.h
machdep.o: ../h/systm.h
machdep.o: ../h/dir.h
machdep.o: ../h/user.h
machdep.o: ../h/map.h
machdep.o: ../h/reg.h
machdep.o: ../h/mtpr.h
machdep.o: ../h/clock.h
machdep.o: ../h/pte.h
machdep.o: ../h/vm.h
machdep.o: ../h/proc.h
machdep.o: ../h/psl.h
machdep.o: ../h/uba.h
machdep.o: ../h/cons.h
machdep.o: ../h/reboot.h
main.o: ../h/param.h
main.o: ../h/systm.h
main.o: ../h/dir.h
main.o: ../h/user.h
main.o: ../h/filsys.h
main.o: ../h/mount.h
main.o: ../h/map.h
main.o: ../h/proc.h
main.o: ../h/inode.h
main.o: ../h/seg.h
main.o: ../h/conf.h
main.o: ../h/buf.h
main.o: ../h/mtpr.h
main.o: ../h/pte.h
main.o: ../h/clock.h
main.o: ../h/vm.h
main.o: ../h/cmap.h
main.o: ../h/text.h
main.o: ../h/vlimit.h
malloc.o: ../h/param.h
malloc.o: ../h/systm.h
malloc.o: ../h/map.h
malloc.o: ../h/dir.h
malloc.o: ../h/user.h
malloc.o: ../h/proc.h
malloc.o: ../h/mtpr.h
malloc.o: ../h/text.h
nami.o: ../h/param.h
nami.o: ../h/systm.h
nami.o: ../h/inode.h
nami.o: ../h/mount.h
nami.o: ../h/dir.h
nami.o: ../h/user.h
nami.o: ../h/buf.h
pipe.o: ../h/param.h
pipe.o: ../h/systm.h
pipe.o: ../h/dir.h
pipe.o: ../h/user.h
pipe.o: ../h/inode.h
pipe.o: ../h/file.h
pipe.o: ../h/reg.h
pipe.o: ../h/inline.h
pipe.o: ../h/proc.h
prf.o: ../h/param.h
prf.o: ../h/systm.h
prf.o: ../h/seg.h
prf.o: ../h/buf.h
prf.o: ../h/conf.h
prf.o: ../h/mtpr.h
prf.o: ../h/reboot.h
prim.o: ../h/param.h
prim.o: ../h/tty.h
prim.o: ../h/systm.h
prim.o: ../h/conf.h
prim.o: ../h/buf.h
rdwri.o: ../h/param.h
rdwri.o: ../h/systm.h
rdwri.o: ../h/inode.h
rdwri.o: ../h/dir.h
rdwri.o: ../h/user.h
rdwri.o: ../h/buf.h
rdwri.o: ../h/conf.h
rdwri.o: ../h/cmap.h
rdwri.o: ../h/vlimit.h
rdwri.o: ../h/proc.h
sig.o: ../h/param.h
sig.o: ../h/systm.h
sig.o: ../h/dir.h
sig.o: ../h/user.h
sig.o: ../h/proc.h
sig.o: ../h/inode.h
sig.o: ../h/reg.h
sig.o: ../h/text.h
sig.o: ../h/seg.h
sig.o: ../h/mtpr.h
sig.o: ../h/pte.h
sig.o: ../h/psl.h
sig.o: ../h/vm.h
sig.o: ../h/buf.h
sig.o: ../h/vlimit.h
slp.o: ../h/param.h
slp.o: ../h/systm.h
slp.o: ../h/dir.h
slp.o: ../h/user.h
slp.o: ../h/proc.h
slp.o: ../h/file.h
slp.o: ../h/inode.h
slp.o: ../h/vm.h
slp.o: ../h/pte.h
slp.o: ../h/inline.h
subr.o: ../h/param.h
subr.o: ../h/systm.h
subr.o: ../h/conf.h
subr.o: ../h/inode.h
subr.o: ../h/dir.h
subr.o: ../h/user.h
subr.o: ../h/buf.h
subr.o: ../h/proc.h
swtch.o: ../h/param.h
swtch.o: ../h/systm.h
swtch.o: ../h/dir.h
swtch.o: ../h/user.h
swtch.o: ../h/proc.h
swtch.o: ../h/file.h
swtch.o: ../h/inode.h
swtch.o: ../h/vm.h
swtch.o: ../h/pte.h
sys.o: ../h/param.h
sys.o: ../h/systm.h
sys.o: ../h/conf.h
sys.o: ../h/dir.h
sys.o: ../h/user.h
sys.o: ../h/tty.h
sys.o: ../h/proc.h
sys1.o: ../h/param.h
sys1.o: ../h/systm.h
sys1.o: ../h/map.h
sys1.o: ../h/mtpr.h
sys1.o: ../h/dir.h
sys1.o: ../h/user.h
sys1.o: ../h/proc.h
sys1.o: ../h/buf.h
sys1.o: ../h/reg.h
sys1.o: ../h/inode.h
sys1.o: ../h/seg.h
sys1.o: ../h/acct.h
sys1.o: /usr/include/wait.h
sys1.o: ../h/pte.h
sys1.o: ../h/vm.h
sys1.o: ../h/text.h
sys1.o: ../h/psl.h
sys1.o: ../h/vlimit.h
sys1.o: ../h/file.h
sys2.o: ../h/param.h
sys2.o: ../h/systm.h
sys2.o: ../h/dir.h
sys2.o: ../h/user.h
sys2.o: ../h/reg.h
sys2.o: ../h/file.h
sys2.o: ../h/inode.h
sys2.o: ../h/pte.h
sys2.o: ../h/vm.h
sys2.o: ../h/buf.h
sys2.o: ../h/mtpr.h
sys2.o: ../h/proc.h
sys2.o: ../h/inline.h
sys3.o: ../h/param.h
sys3.o: ../h/systm.h
sys3.o: ../h/mount.h
sys3.o: ../h/ino.h
sys3.o: ../h/reg.h
sys3.o: ../h/buf.h
sys3.o: ../h/filsys.h
sys3.o: ../h/dir.h
sys3.o: ../h/user.h
sys3.o: ../h/inode.h
sys3.o: ../h/file.h
sys3.o: ../h/conf.h
sys3.o: ../h/stat.h
sys3.o: ../h/inline.h
sys4.o: ../h/param.h
sys4.o: ../h/systm.h
sys4.o: ../h/dir.h
sys4.o: ../h/user.h
sys4.o: ../h/reg.h
sys4.o: ../h/inode.h
sys4.o: ../h/proc.h
sys4.o: ../h/clock.h
sys4.o: ../h/mtpr.h
sys4.o: ../h/timeb.h
sys4.o: ../h/times.h
sys4.o: ../h/reboot.h
sysent.o: ../h/param.h
sysent.o: ../h/systm.h
sysent.o: ../h/vmsysent.h
sysent.o: vmsysent.c
text.o: ../h/param.h
text.o: ../h/systm.h
text.o: ../h/map.h
text.o: ../h/dir.h
text.o: ../h/user.h
text.o: ../h/proc.h
text.o: ../h/text.h
text.o: ../h/inode.h
text.o: ../h/buf.h
text.o: ../h/seg.h
text.o: ../h/pte.h
text.o: ../h/mtpr.h
text.o: ../h/vm.h
text.o: ../h/cmap.h
trap.o: ../h/param.h
trap.o: ../h/systm.h
trap.o: ../h/dir.h
trap.o: ../h/user.h
trap.o: ../h/proc.h
trap.o: ../h/reg.h
trap.o: ../h/seg.h
trap.o: ../h/trap.h
trap.o: ../h/psl.h
trap.o: ../h/pte.h
trap.o: ../h/inline.h
vmdrum.o: ../h/param.h
vmdrum.o: ../h/systm.h
vmdrum.o: ../h/dir.h
vmdrum.o: ../h/user.h
vmdrum.o: ../h/proc.h
vmdrum.o: ../h/buf.h
vmdrum.o: ../h/text.h
vmdrum.o: ../h/map.h
vmdrum.o: ../h/pte.h
vmdrum.o: ../h/vm.h
vmdrum.o: ../h/cmap.h
vmmem.o: ../h/param.h
vmmem.o: ../h/systm.h
vmmem.o: ../h/pte.h
vmmem.o: ../h/cmap.h
vmmem.o: ../h/dir.h
vmmem.o: ../h/user.h
vmmem.o: ../h/proc.h
vmmem.o: ../h/mtpr.h
vmmem.o: ../h/text.h
vmmem.o: ../h/vm.h
vmmem.o: ../h/file.h
vmmem.o: ../h/inode.h
vmmem.o: ../h/buf.h
vmmem.o: ../h/mount.h
vmmon.o: ../h/param.h
vmmon.o: ../h/systm.h
vmmon.o: ../h/dir.h
vmmon.o: ../h/user.h
vmmon.o: ../h/vmmon.h
vmpage.o: ../h/param.h
vmpage.o: ../h/systm.h
vmpage.o: ../h/inode.h
vmpage.o: ../h/dir.h
vmpage.o: ../h/user.h
vmpage.o: ../h/proc.h
vmpage.o: ../h/reg.h
vmpage.o: ../h/pte.h
vmpage.o: ../h/buf.h
vmpage.o: ../h/text.h
vmpage.o: ../h/mtpr.h
vmpage.o: ../h/cmap.h
vmpage.o: ../h/vm.h
vmpage.o: ../h/vmmon.h
vmpage.o: ../h/file.h
vmproc.o: ../h/param.h
vmproc.o: ../h/systm.h
vmproc.o: ../h/dir.h
vmproc.o: ../h/user.h
vmproc.o: ../h/proc.h
vmproc.o: ../h/mtpr.h
vmproc.o: ../h/pte.h
vmproc.o: ../h/map.h
vmproc.o: ../h/cmap.h
vmproc.o: ../h/text.h
vmproc.o: ../h/vm.h
vmpt.o: ../h/param.h
vmpt.o: ../h/systm.h
vmpt.o: ../h/dir.h
vmpt.o: ../h/user.h
vmpt.o: ../h/proc.h
vmpt.o: ../h/map.h
vmpt.o: ../h/mtpr.h
vmpt.o: ../h/pte.h
vmpt.o: ../h/cmap.h
vmpt.o: ../h/vm.h
vmpt.o: ../h/buf.h
vmpt.o: ../h/text.h
vmpt.o: ../h/mount.h
vmsched.o: ../h/param.h
vmsched.o: ../h/systm.h
vmsched.o: ../h/seg.h
vmsched.o: ../h/dir.h
vmsched.o: ../h/user.h
vmsched.o: ../h/proc.h
vmsched.o: ../h/text.h
vmsched.o: ../h/vm.h
vmsched.o: ../h/cmap.h
vmsubr.o: ../h/param.h
vmsubr.o: ../h/systm.h
vmsubr.o: ../h/dir.h
vmsubr.o: ../h/user.h
vmsubr.o: ../h/vm.h
vmsubr.o: ../h/proc.h
vmsubr.o: ../h/mtpr.h
vmsubr.o: ../h/pte.h
vmsubr.o: ../h/cmap.h
vmsubr.o: ../h/inode.h
vmsubr.o: ../h/buf.h
vmsubr.o: ../h/text.h
vmswap.o: ../h/param.h
vmswap.o: ../h/systm.h
vmswap.o: ../h/dir.h
vmswap.o: ../h/user.h
vmswap.o: ../h/proc.h
vmswap.o: ../h/text.h
vmswap.o: ../h/map.h
vmswap.o: ../h/buf.h
vmswap.o: ../h/pte.h
vmswap.o: ../h/mtpr.h
vmswap.o: ../h/cmap.h
vmswap.o: ../h/vm.h
vmsys.o: ../h/param.h
vmsys.o: ../h/systm.h
vmsys.o: ../h/dir.h
vmsys.o: ../h/user.h
vmsys.o: ../h/proc.h
vmsys.o: ../h/reg.h
vmsys.o: ../h/file.h
vmsys.o: ../h/inode.h
vmsys.o: ../h/vm.h
vmsys.o: ../h/buf.h
vmsys.o: ../h/pte.h
vmsys.o: ../h/cmap.h
vmsys.o: ../h/tty.h
vmsys.o: ../h/mtpr.h
vmsys.o: ../h/vlimit.h
# DEPENDENCIES MUST END AT END OF FILE
# IF YOU PUT STUFF HERE IT WILL GO AWAY
# see make depend above
