.\" Copyright (c) 1983 Regents of the University of California.
.\" All rights reserved.  The Berkeley software License Agreement
.\" specifies the terms and conditions for redistribution.
.\"
.\"	@(#)il.4	6.4 (Berkeley) 6/1/86
.\"
.TH IL 4 "June 1, 1986"
.UC 5
.SH NAME
il \- Interlan NI1010 10 Mb/s Ethernet interface
.SH SYNOPSIS
.B "device il0 at uba0 csr 164000 vector ilrint ilcint"
.SH DESCRIPTION
The
.I il
interface provides access to a 10 Mb/s Ethernet network through
an Interlan 1010 or 1010A controller.
.PP
Each of the host's network addresses
is specified at boot time with an SIOCSIFADDR
ioctl.  The
.I il
interface employs the address resolution protocol described in
.IR arp (4P)
to dynamically map between Internet and Ethernet addresses on the local
network.
.PP
The interface normally tries to use a ``trailer'' encapsulation
to minimize copying data on input and output.
The use of trailers is negotiated with ARP.
This negotiation may be disabled, on a per-interface basis,
by setting the IFF_NOTRAILERS
flag with an SIOCSIFFLAGS ioctl.
.SH DIAGNOSTICS
\fBil%d: input error\fP.  The hardware indicated an error
in reading a packet off the cable or an illegally sized packet.
.PP
\fBil%d: can't handle af%d\fP.  The interface was handed
a message with addresses formatted in an unsuitable address
family; the packet was dropped.
.PP
\fBil%d: setaddr didn't work\fP.  The interface was unable to reprogram
its physical ethernet address.
This may happen with very early models of the interface.
This facility is used only when
the controller is not the first network interface configured for XNS.
The oldest interface tested (2.7.1.0.1.45) has never failed in this way.
.PP
The following messages indicate a probable hardware error performing
the indicated operation during autoconfiguration or initialization.
The status field in the control and status register (the low-order four bits)
should indicate the nature of the failure.
See the hardware manual for details.
.PP
\fBil%d: reset failed, csr=%b\fP.
.PP
\fBil%d: status failed, csr=%b\fP.
.PP
\fBil%d: hardware diag failed, csr=%b\fP.
.PP
\fBil%d: verifying setaddr, csr=%b\fP.
.PP
\fBil%d: stray xmit interrupt, csr=%b\fP.
.PP
\fBil%d: can't initialize\fP.
.SH SEE ALSO
intro(4N), inet(4F), arp(4P)
