#	@(#)Makefile.inc	5.2 (Berkeley) %G%
#
.include "${.CURDIR}/db/db/Makefile.inc"
.include "${.CURDIR}/db/btree/Makefile.inc"
.include "${.CURDIR}/db/hash/Makefile.inc"
.include "${.CURDIR}/db/recno/Makefile.inc"
.include "${.CURDIR}/db/man/Makefile.inc"
