.\" Copyright (c) 1989, 1991, 1993
.\"	The Regents of the University of California.  All rights reserved.
.\"
.\" %sccs.include.redist.man%
.\"
.\"     @(#)isascii.3	8.1 (Berkeley) %G%
.\"
.Dd 
.Dt ISASCII 3
.Os
.Sh NAME
.Nm isascii
.Nd test for ASCII character
.Sh SYNOPSIS
.Fd #include <ctype.h>
.Ft int
.Fn isascii "int c";
.Sh DESCRIPTION
The
.Fn isascii
function tests for an
.Tn ASCII
character, which is any character with a value less than than or
equal to 0177.
.Sh SEE ALSO
.Xr ctype 3 ,
.Xr ascii 7
.Sh STANDARDS
The
.Fn isascii
function conforms to
.St -ansiC .
