.\" Copyright (c) 1991, 1993
.\"	The Regents of the University of California.  All rights reserved.
.\"
.\" This code is derived from software contributed to Berkeley by
.\" the American National Standards Committee X3, on Information
.\" Processing Systems.
.\"
.\" %sccs.include.redist.man%
.\"
.\"	@(#)ispunct.3	8.1 (Berkeley) %G%
.\"
.Dd 
.Dt ISPUNCT 3
.Os
.Sh NAME
.Nm ispunct
.Nd punctuation character test
.Sh SYNOPSIS
.Fd #include <ctype.h>
.Ft int
.Fn ispunct "int c";
.Sh DESCRIPTION
The
.Fn ispunct
function tests for any printing character except for space (' ') or a
character for which
.Xr isalnum 3
is true.
In the ASCII character set, this includes the following characters:
.sp
.Bl -column \&000_``0''__ \&000_``0''__ \&000_``0''__ \&000_``0''__ \&000_``0''__
.It \&041\ ``!'' \t042\ ``"'' \t043\ ``#'' \t044\ ``$'' \t045\ ``%''
.It \&046\ ``&'' \t047\ ``''' \t050\ ``('' \t051\ ``)'' \t052\ ``*''
.It \&053\ ``+'' \t054\ ``,'' \t055\ ``-'' \t056\ ``.'' \t057\ ``/''
.It \&072\ ``:'' \t073\ ``;'' \t074\ ``<'' \t075\ ``='' \t076\ ``>''
.It \&077\ ``?'' \t100\ ``@'' \t133\ ``['' \t134\ ``\'' \t135\ ``]''
.It \&136\ ``^'' \t137\ ``_'' \t140\ ```'' \t173\ ``{'' \t174\ ``|''
.It \&175\ ``}'' \t176\ ``~''
.El
.Sh RETURN VALUES
The
.Fn ispunct
function returns zero if the character tests false and
returns non-zero if the character tests true.
.Sh SEE ALSO
.Xr ctype 3 ,
.Xr ascii 7
.Sh STANDARDS
The
.Fn ispunct
function conforms to
.St -ansiC .
