_divert__(-1)
_define__(<_I960__>,<1>)
_define__(<_AOUT__>,<0>)
_define__(<_BOUT__>,<1>)
_define__(<_COFF__>,<1>)
_define__(<_AS__>,<gas960>)
_define__(<_GCC__>,<gcc960>)
_define__(<_LD__>,<gld960>)
_define__(<_GDB__>,<gdb960>)
_define__(<_HOST__>,<Intel 960>)
_define__(<_MACH_DEP__>,<i960 Dependent>)
_divert__<>