.\" Copyright (c) 1983 The Regents of the University of California.
.\" All rights reserved.
.\"
.\" %sccs.include.redist.man%
.\"
.\"	@(#)networks.5	6.4 (Berkeley) %G%
.\"
.TH NETWORKS 5  ""
.UC 5
.SH NAME
networks \- network name data base
.SH DESCRIPTION
The
.I networks
file contains information regarding
the known networks which comprise the DARPA Internet.
For each network a single line should be present with the following information:
.HP 10
official network name
.br
.ns
.HP 10
network number
.br
.ns
.HP 10
aliases
.PP
Items are separated by any number of blanks and/or tab characters.
A ``#'' indicates the beginning of a comment; characters up to the end of
the line are not interpreted by routines which search the file.
This file is normally created from the official network data base
maintained at the Network Information Control Center (NIC), though local
changes may be required to bring it up to date regarding unofficial aliases
and/or unknown networks.
.PP
Network number may be specified in the conventional
``.'' notation using the \fIinet_network\fP() routine
from the Internet address manipulation library,
.IR inet (3N).
Network names may contain any printable character other than a field
delimiter, newline, or comment character.
.SH FILES
/etc/networks
.SH "SEE ALSO"
getnetent(3N)
.SH BUGS
A name server should be used instead of a static file.
