/* Copyright (c) 1979 Regents of the University of California */
#define AUTOINDENT      0
#define AUTOPRINT       1
#define BEAUTIFY        2
#define DIRECTORY       3
#define ERRORBELLS      4
#define IGNORECASE      5
#define LISP            6
#define LIST            7
#define MAGIC           8
#define NUMBER          9
#define OPEN            10
#define OPTIMIZE        11
#define PARAGRAPHS      12
#define PROMPT          13
#define REDRAW          14
#define REPORT          15
#define SCROLL          16
#define SECTIONS        17
#define SHELL           18
#define SHIFTWIDTH      19
#define SHOWMATCH       20
#define SLOWOPEN        21
#define TABSTOP         22
#define TTYTYPE         23
#define TERM            24
#define TERSE           25
#define WARN            26
#define WINDOW          27
#define WRAPSCAN        28
#define WRAPMARGIN      29
#define WRITEANY        30

#define	NOPTS	31
