.\" Copyright (c) 1980 The Regents of the University of California.
.\" All rights reserved.
.\"
.\" Redistribution and use in source and binary forms are permitted
.\" provided that the above copyright notice and this paragraph are
.\" duplicated in all such forms and that any documentation,
.\" advertising materials, and other materials related to such
.\" distribution and use acknowledge that the software was developed
.\" by the University of California, Berkeley.  The name of the
.\" University may not be used to endorse or promote products derived
.\" from this software without specific prior written permission.
.\" THIS SOFTWARE IS PROVIDED ``AS IS'' AND WITHOUT ANY EXPRESS OR
.\" IMPLIED WARRANTIES, INCLUDING, WITHOUT LIMITATION, THE IMPLIED
.\" WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE.
.\"
.\"	@(#)adduser.8	6.5 (Berkeley) %G%
.\"
.TH ADDUSER 8 ""
.UC 4
.SH NAME
adduser \- procedure for adding new users
.SH DESCRIPTION
A new user must choose a login name, which must not already appear in
\fI/etc/passwd\fP or \fI/usr/lib/aliases\fP.  It must also not begin with
the hyphen (``-'') character.  An account can be added by editing a line
into the passwd file; this must be done with the password file locked
e.g. by using
.IR chpass (1)
or
.IR vipw (8).
.PP
A new user is given a group and user id.
User id's should be unique for the system, since they are used to
control access to files.
Typically, users working on similar projects will be put in the same groups.
At UCB we have groups for system staff, faculty, graduate students, and
special groups for large projects.
.PP
A skeletal account for a new user \*(lqernie\*(rq might look like:
.IP
ernie::25:30:none:0:0:Ernie Kovacs,508 Evans Hall,x7925,642-8202:/a/users/ernie:/bin/csh
.PP
For a description of each of these fields, see
.IR passwd (5).
.PP
It is useful to give new users some help in getting started, supplying
them with a few skeletal files such as
.I \&.profile
if they use \*(lq/bin/sh\*(rq, or
.I \&.cshrc
and
.I \&.login
if they use \*(lq/bin/csh\*(rq.
The directory
\*(lq/usr/skel\*(rq contains skeletal definitions of such files.
New users should be given copies of these files which, for instance,
use
.IR tset (1)
automatically at each login.
.SH FILES
.ta 2i
/etc/master.passwd	user database
.br
/usr/skel	skeletal login directory
.SH SEE ALSO
chpass(1), finger(1), passwd(1), aliases(5), passwd(5), mkpasswd(8), vipw(8)
.SH BUGS
User information should (and eventually will) be stored elsewhere.
