.\" Copyright (c) 1983 Regents of the University of California.
.\" All rights reserved.  The Berkeley software License Agreement
.\" specifies the terms and conditions for redistribution.
.\"
.\"	@(#)kill.3	5.1 (Berkeley) %G%
.\"
.TH KILL 3F "18 July 1983"
.UC 5
.SH NAME
kill \- send a signal to a process
.SH SYNOPSIS
.B function kill (pid, signum)
.br
.B integer pid, signum
.SH DESCRIPTION
.I Pid
must be the process id of one of the user's processes.
.I Signum
must be a valid signal number (see sigvec(2)).
The returned value will be 0 if successful; an error code otherwise.
.SH FILES
.ie \nM /usr/ucb/lib/libU77.a
.el /usr/lib/libU77.a
.SH "SEE ALSO"
kill(2), sigvec(2), signal(3F), fork(3F), perror(3F)
