.so tmac.ilib
.TH I-HIER 7 "The University of Arizona \- 8/17/84"
.SH NAME
i-hier \- Icon hierarchy
.SH DESCRIPTION
The following outline gives a sketch of the Icon hierarchy.
.nf
.ta 1i 2i 3i 4i
.sp 1
\*Mv5g\fR	root of the Icon system (location may vary from site to site)
	\*M/src\fR	source code for Icon library programs
		\*M/cmd\fR	source code for application programs and games
		\*M/lib\fR	source code for procedure libraries
	\*M/man\fR	manual
		\*M/man0\fR	front matter
		\*M/man1\fR	application programs
		\*M/man2\fR	procedures
		\*M/man3\fR	C functions
		\*(El	\*(El
		\*M/man7\fR	miscellaneous
		\*M/man8\fR	library maintenance
		\*M/cat0\fR	formatted front matter for manual
		\*M/cat1\fR	formatted pages for application programs
		\*(El
	\*M/ibin\fR	executable binaries for application programs and games
	\*M/ilib\fR	linkable code for procedure libraries
	\*M/pifuncs\fR	source code for Icon library C functions
	\*M/pilib\fR	code for building personalized interpreters
	\*M/docs\fR	Icon documentation
	\*M/book\fR	source code for procedures from the Icon book
	\*M/bin\fR	executable portions of Icon
	\*M/tran\fR	source code for the Icon translator
	\*M/link\fR	source code for the Icon linker
	\*M/h\fR	header files for the Icon system
	\*M/functions\fR	source code for built-in functions
	\*M/operators\fR	source code for operators
	\*M/rt\fR	source code for run-time support routines
	\*M/lib\fR	source code for routines called by the Icon interpreter
	\*M/iconx\fR	source code for the Icon interpreter
	\*M/pidemo\fR	sample personalized interpreter
	\*M/samples\fR	Icon installation test programs
	\*M/libtest\fR	Icon library test programs
	\*M/test\fR	Icon test suite
	\*M/port\fR	Icon porting test suite
.SH SEE ALSO
Griswold, Ralph E. and William H. Mitchell. \fIInstallation and Maintenance
Guide for Version 5.9 of Icon\fR, TR 84-13, Department of Computer Science,
The University of Arizona, 1984.
