.\" Copyright (c) 1983 The Regents of the University of California.
.\" All rights reserved.
.\"
.\" Redistribution and use in source and binary forms are permitted
.\" provided that the above copyright notice and this paragraph are
.\" duplicated in all such forms and that any documentation,
.\" advertising materials, and other materials related to such
.\" distribution and use acknowledge that the software was developed
.\" by the University of California, Berkeley.  The name of the
.\" University may not be used to endorse or promote products derived
.\" from this software without specific prior written permission.
.\" THIS SOFTWARE IS PROVIDED ``AS IS'' AND WITHOUT ANY EXPRESS OR
.\" IMPLIED WARRANTIES, INCLUDING, WITHOUT LIMITATION, THE IMPLIED
.\" WARRANTIES OF MERCHANTIBILITY AND FITNESS FOR A PARTICULAR PURPOSE.
.\"
.\"	@(#)comsat.8	6.3 (Berkeley) 9/19/88
.\"
.TH COMSAT 8 "September 19, 1988"
.UC 5
.SH NAME
comsat \- biff server
.SH SYNOPSIS
.B /etc/comsat
.SH DESCRIPTION
.I Comsat
is the server process which receives reports of incoming mail
and notifies users if they have requested this service.
.I Comsat
receives messages on a datagram port associated with the ``biff'' service
specification (see
.IR services (5)
and
.IR inetd (8)).
The one line messages are of the form
.PP
.ti +0.5i
user@mailbox-offset
.PP
If the
.I user
specified is logged in to the system and the associated terminal has
the owner execute bit turned on (by a ``biff y''), the
.I offset
is used as a seek offset into the appropriate mailbox file and
the first 7 lines or 560 characters of the message are printed
on the user's terminal.  Lines which appear to be part of
the message header other than the ``From'', ``To'', ``Date'',
or ``Subject'' lines are not included in the displayed message.
.SH FILES
.DT
/etc/utmp	to find out who's logged on and on what terminals
.SH "SEE ALSO"
biff(1), inetd(8)
.SH BUGS
The message header filtering is prone to error.
The density of the information presented is near the theoretical minimum.
.PP
Users should be notified of mail which arrives on other
machines than the one to which they are currently logged in.
.PP
The notification should appear in a separate window so it
does not mess up the screen.
